### ISSUE TITLE
YouTube no-cookie embeds are broken

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix.org#1000]
When trying to embed a video from YouTube using their "privacy preserving" iframe, our Content Security Policy settings block the element. The iframe embed code looks like:

```html
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/yQomSqGLQaM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

The browser's JS console reports:

Content Security Policy: The page’s settings blocked the loading of a resource at https://www.youtube-nocookie.com/embed/4vr9RRYNWWE (“frame-src”).

So it seems that we need to add youtube-nocookie.com to a config somewhere.

**Comment by ibrahim1520** [comment]
Hello
can I fix it

**Comment by MadLittleMods** [comment]
@ibrahim1520 Go for it 👍

**Comment by thibaultamartin** [comment]
It looks like [YouTube nocookie doesn't bring much to the table](https://www.stefanjudis.com/notes/the-lie-of-youtubes-privacy-enhanced-embed-mode/). Please reopen if you think we should use youtube nocookie for embeds!
