### ISSUE TITLE
Better guide to setting up synapse with Letsencrypt

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix.org#101]
https://matrix.org/jira/browse/ORG-48 said: "Turn https://matrix.org/blog/2016/02/10/advanced-synapse-setup-with-lets-encrypt/ into a proper guide."

I'd suggest omitting the stuff on using the letsencrypt cert for the federation port, however. Experience suggests it confuses more people than it helps...

We also have https://matrix.org/docs/guides/lets-encrypt.html, which should be replaced with something more comprehensive.

**Comment by thibaultamartin** [comment]
Duplicating project-specific documentation on matrix.org does more harm than good. Such a documentation should probably be in https://matrix-org.github.io/synapse/latest/setup/installation.html instead?

**Comment by richvdh** [comment]
totally agreed.
