### ISSUE TITLE
Links inside code tags are not styled distinctly from plain code tags

### ISSUE THREAD

**Issue by callahad** [matrix-org/matrix.org#1013]
Looking at https://matrix.org/blog/2021/06/14/adventures-in-fuzzing-libolm, one of the `<code>` blocks in this screenshot is a link... but can you tell which one? 🧐 
![Screen Shot 2021-06-15 at 09 39 08](https://user-images.githubusercontent.com/24193/122031649-ce1a9780-cdc6-11eb-9a03-ebef349e1c91.png)

**Comment by thibaultamartin** [comment]
<img width="588" alt="Screenshot 2023-04-28 at 15 30 57" src="https://user-images.githubusercontent.com/1688309/235161131-b11bec3b-6c2a-4885-85cf-53ee0935c10d.png">

Yep, looks less terrible and is still readable
