### ISSUE TITLE
Add project website field (and other niceties)

### ISSUE THREAD

**Issue by Matrixcoffee** [matrix-org/matrix.org#103]
I finally have some time to make FAQBot a reality. I am parsing the project files, but one issue I ran into is that there's no good way to automatically extract a link to the project's main web site. They are buried in the free-form description part, and if there is more than one link, it's anyone's guess which is the right one.

So, I propose to add a website field to the template and the project files.

While we're adding fields, we could add some other niceties as well, a la F-Droid:
* Web Site
* Source Code
* Issue Tracker
* License

Comments?

**Comment by turt2live** [comment]
I like this idea, although I'm not sure the license or issue tracker parts are actually needed. Surely a link to Github/Gitlab/Gitea/Bitbucket/whatever would be enough given everything supports READMEs.

**Comment by benparsons** [comment]
A lot of this is now done on apr18 branch, coming asap.

**Comment by Matrixcoffee** [comment]
Looking good so far. The one thing I'm missing is the actual website field though.

**Comment by benparsons** [comment]
Ah whoops, there are fields missing from the output as they're not used on the page yet. I have separate fields for repo and homepage. Of course, a lot of projects don't have homepages beyond the repo so this can be used instead.

**Comment by benparsons** [comment]
Where we have them stored, there is a "home:" field on all the markdown source files. @Matrixcoffee where does your bot read from? Is it necessary to output this to the HTML?

**Comment by Matrixcoffee** [comment]
@benparsons the extractor reads directly from git. I'll also have that code on-line very soon.

**Comment by benparsons** [comment]
@Matrixcoffee in that case we can close this issue, and you can assume that these fields will be populated incrementally as they become available.
