### ISSUE TITLE
Question: Where are the room versions and their changelogs?

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix.org#1043]
I have [a script for manually updating rooms](https://gitea.blesmrt.net/mikaela/scripts/src/branch/master/bash/matrix-upgrade-room.bash) where I advice people to check what is the current room version before using it. However the list on the website is missing room version 7 entirely while [recent Synapse is already on version 8](https://github.com/matrix-org/synapse/releases/tag/v1.40.0).

* https://matrix.org/docs/spec/#complete-list-of-room-versions

Where can I find room version 7, what changed with it and where will version 8 and future room versions be explained?

Finnish Matrix user group tells me that the docs/spec is no longer updated and the replacement isn't released yet (is this correct?), but can be previewed from /unstable/ which again doesn't have an equivalent page. 

* https://spec.matrix.org/unstable/rooms/

In addition to not telling me what has changed at a glance or whether the room version is stable, I am not sure if I should link production users to somewhere saying /unstable/ and

!["You're looking at an unstable version of this specification. Unstable specifications may change at any time without notice."](https://user-images.githubusercontent.com/831184/128897100-745fc0d5-0c91-4d1e-911f-854da24bf064.png)

**Comment by MadLittleMods** [comment]
https://spec.matrix.org/unstable/#complete-list-of-room-versions seems to be what you're looking for. It has room version 7 listed and I assume room version 8 will come "soon" now that the [MSC has merged](https://github.com/matrix-org/matrix-doc/pull/3289).

**Comment by Mikaela** [comment]
Thank you, will [the first link](https://matrix.org/docs/spec/#complete-list-of-room-versions) automatically point there or will all links need to be updated when the new spec is released? Is there a timeline for that somewhere?

**Comment by MadLittleMods** [comment]
@Mikaela I am not sure what the final URL of the new spec redesign will be or how the redirects will be setup from the old spec. I think the new canonical spec home will be `spec.matrix.org` but with a proper version instead of `unstable`.

For a plan/timeline of the new spec redesign release, see https://github.com/matrix-org/matrix-doc/issues/3095

**Comment by MTRNord** [comment]
@Mikaela is this issue still relevant or can it be closed? :)

**Comment by Mikaela** [comment]
Yes, I think this has became clearer since then, thank you.
