### ISSUE TITLE
Remove leftovers from WordPress

### ISSUE THREAD

**Issue by afranke** [matrix-org/matrix.org#1048]
In the same vein as #1047 I had noticed a while ago that the [`wp-content/`](tree/f363d9536bac0526144cdc3efcd04bc79433376a/content/blog/wp-content) is still around, and had it in my notes but filing an issue is probably a better idea. It is fine when it comes to ensuring files that might be linked to from anywhere are still available but:

* [ ] such files belong in a subdirectory of [`static/`](../tree/f363d9536bac0526144cdc3efcd04bc79433376a/gatsby/static)
* [ ] there is much content that is actually irrelevant now and should simply be removed (probably all of `plugins` and `themes`, which means we’d only keep `uploads`)

The cleanup should happen before the move.

As for [`wp-includes`](../tree/f363d9536bac0526144cdc3efcd04bc79433376a/content/blog/wp-includes), some bits in other places rely on its jQuery. I suppose we have another copy of jQuery somewhere else that we could use instead. Where is it?

* [ ] replace use of jQuery from `wp-includes` with another copy
* [ ] remove `wp-includes`

**Comment by thibaultamartin** [comment]
@laurencegill are you confident we can close this issue?

**Comment by laurencegill** [comment]
@thibaultamartin I'm not entirely sure what you're asking :smile: 

There isn't any `wp-{content,includes}` content in the `main` branch if that's what you mean?

**Comment by thibaultamartin** [comment]
I indeed mean nothing `wp-*` on the `main` branch, and no script/CI relying on it to deploy anything on matrix.org :)

**Comment by laurencegill** [comment]
> I indeed mean nothing `wp-*` on the `main` branch, and no script/CI relying on it to deploy anything on matrix.org :)

I believe this is the case, closing :smile:
