### ISSUE TITLE
Check Xonotic presentation accuracy

### ISSUE THREAD

**Issue by afranke** [matrix-org/matrix.org#1056]
I stumbled upon [the Xonotic project presentation](https://matrix.org/docs/projects/other/xonotic) which was added in 2018 and got [some details added recently](https://github.com/matrix-org/matrix.org/commit/e9336ee6e5cb2496f3fd1e82da7f864d06330a64). I got curious and dug up a bit.

The [history of changes](https://gitlab.com/xonotic/xonotic-data.pk3dir/-/commits/master/qcsrc/lib/matrix) show little recent activity, but it’s still been touched after its addition to matrix.org so now I’m wondering if it actually got “merged into their mainline branch”. Our description also makes it unclear whether that is just an experiment or whether it is what powers the chat that is currently used by players in the released game.

@timepath would you mind clarifying whether the “not actively maintained” status we have is still accurate and whether it actually made into the game?

**Comment by TimePath** [comment]
Hi, the "not actively maintained" status is accurate.
It was "just an experiment" which was merged into mainline and received some light use to demonstrate the concept.
There were some plans for further use in a non-chat capacity, but they have not since materialized.

**Comment by MadLittleMods** [comment]
Thanks for the update 🙂
