### ISSUE TITLE
Is upgrading a room still not recommended?

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/matrix.org#1060]
Currently, the note about State Resets mentions that upgrading a room is not recommended,

> `/upgraderoom 6` command - but please note this is not recommended, as we are still testing the final room algorithm and upgrade mechanism for Matrix 1.0.
>
> *-- [`gatsby/content/docs/2019-04-29-moderation.mdx`](https://github.com/matrix-org/matrix.org/blob/c01cd843eb108106df2a236ec33969437a66d69e/gatsby/content/docs/2019-04-29-moderation.mdx#a-note-on-state-resets)*

Is this still the case nowadays as we seem to be doing it a lot without a problem for Spaces stuff in room versions, v7 and v8?

---

*Spawned from recommending this section to someone: https://gitlab.com/gitterHQ/webapp/-/issues/2792#note_658288382*

**Comment by aaronraimist** [comment]
Element definitely still has bugs where it doesn't notify you that a room upgrade has occurred https://github.com/vector-im/element-web/issues/11932

**Comment by MadLittleMods** [comment]
Thanks @aaronraimist!

From some out of band discussion with @turt2live as well, the upgrade mechanism itself is fine nowadays but as you mentioned the UX around upgrades has many bugs, https://github.com/vector-im/element-web/labels/A-Room-Upgrades

And the goal being to make it seamless: stitching timelines together, autojoin people, etc.

I think it's probably worth updating the qualifying note around why it's not totally perfect, vs still in the testing stage.
