### ISSUE TITLE
Add https://github.com/matrix-hacks/matrix-puppet-slack

### ISSUE THREAD

**Issue by Matrixcoffee** [matrix-org/matrix.org#107]
Moving the directory part out of matrix-knowledge-base, and found a project that does not appear to be in the directory here. The [original link I have](https://github.com/kfatehi/matrix-appservice-slack) now redirects to https://github.com/matrix-hacks/matrix-puppet-slack.

Ping @matrix-hacks @kfatehi

(If you don't know what to do: https://github.com/matrix-org/matrix.org/blob/master/README.md)

**Comment by benparsons** [comment]
Added to https://matrix.org/docs/projects/try-matrix-now.html.
