### ISSUE TITLE
Site nav links are not clickable in Chrome 94+

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/matrix.org#1084]
The site nav at the top has items but none of them are clickable, can only select the text.

https://matrix.org/
![](https://user-images.githubusercontent.com/558581/134966655-1bd42f1f-f6c6-4ed5-bfab-0f04967472fa.png)

 - :x: Chrome 94.0.4606.54 on Windows 10
 - :x: Chrome 96.0.4655.0 on macOS
 - :x: Chrome 96.0.4655.0 on Windows 10
 - ✅ Chrome 93.0.4577.63 on macOS
 - ✅ Firefox 92.0.1

---

Looks to be a problem with `.mxnavbar` having `transform-style: preserve-3d; transform: translate3d(0px, 0px, 100px);` but [those styles](https://github.com/matrix-org/matrix.org/blame/9ae44a2a0f5921ef17f0615c1ea9b30cc391f856/gatsby/static/css/matrix-org.webflow.css#L67) aren't new 🤔

Probably related to the following in the Chrome 94 changelog:

> **Align transform-style: preserve-3d and perspective Property with the Spec**
> 
> [The transform-style: preserve-3d and perspective properties now align with the spec](https://www.chromestatus.com/feature/5640541339385856). The preserve-3d property allows child elements to participate in the parent's 3D scene, and the perspective property applies a perspective transform to child elements. Before this change, Chromium applied both of these effects based on the containing block hierarchy rather than the DOM tree, and allowed them to extend through elements without transform-related properties on them.
>
> https://blog.chromium.org/2021/08/chrome-94-beta-webcodecs-webgpu.html

**Comment by afranke** [comment]
I reckon that’s webflow crap, and it seems redundant with the `z-index` on `.w-nav` anyway. Disabling it in the Firefox inspector doesn’t seem to break anything (tested in adaptive too). Let’s remove it, shall we?
