### ISSUE TITLE
Swagger viewer adds a %20 (space) before the access token in the query string

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix.org#1093]
This makes all requests fail

![image](https://user-images.githubusercontent.com/1190097/137424471-acd8ced9-dc0c-499c-b992-82f6df1dd919.png)

**Comment by barodeur** [comment]
I was just affected by this bug and investigated.
This seems to come from a bug of [RapiDoc](https://github.com/mrin9/RapiDoc) and has already been reported here.
Unfortunately, the fix https://github.com/mrin9/RapiDoc/commit/06137450de5014435e90cbe76d7f7f7a262668a6 has not yet been released in a new version.  But there is a build that inclues the fix available on their `master` branch.

**Comment by afranke** [comment]
Indeed, I found https://github.com/mrin9/RapiDoc/issues/570 earlier today and I just left [this comment](https://github.com/mrin9/RapiDoc/discussions/546#discussioncomment-1576858) calling for a new release.
