### ISSUE TITLE
Clarify web vs native (mobile and desktop) apps on clients page

### ISSUE THREAD

**Issue by afranke** [matrix-org/matrix.org#1104]
This is a followup of the conversation at #1101, as I think it would be off topic there.

@aaronraimist said:
> I also noticed that Hydrogen is listed as supporting Linux, macOS, Windows, Android, and iOS even though it doesn't have an app for any of those. It is just a website that happens to run on all of those platforms. Cinny is another web only client but is only listed as supporting web. I'm not sure which of those is correct but those should be reconciled. To me it would make sense to keep Linux, macOS, Windows, Android, and iOS as meaning they are native apps for those platforms.

I don’t think it’s quite as clear-cut as that. Element Web is a Web application, but I would be very surprised it was usable on a phone browser. I haven’t tried it on a proper phone, but using it daily on my narrow (1050px wide) monitor already shows some limitations and I just tried it in the Firefox Responsive Design mode which shows it’s… not responsive at all. :rofl: There is a reason it is considered as “Element Web/Desktop”, and it’s not just because they are technically one thing packaged differently. I don’t know Cinny well enough, but I think the same reasoning applies as well.

Hydrogen on the other hand was, as far as I know, not only built to run well on such platforms, but also designed to be as usable as on desktop. Maybe @bwindels can confirm that. Maybe it even works as a PWA, making it really mobile friendly?

Categorisation is hard. In the same vein as the question of Web versus native mobile, there’s the debate of whether electron apps should count as desktop ones since they are not “native” either. I’m inclined to say that if it was designed to work well on a given platform, for our use case, the UI technology doesn’t really matter and we shouldn’t be too strict. That is not to say that the current presentation is perfect. Maybe on [the clients page](https://matrix.org/clients/) we could add icons for supported platforms, so that e.g. Element Web/Desktop would be in the Desktop section with a “web” icon, and Seaglass would be in Desktop with a macOS icon. Something in the spirit of the [Humble store](https://www.humblebundle.com/store):

![image](https://user-images.githubusercontent.com/117241/139209123-b93c6f2a-1eb4-4032-912d-e792d7c590b6.png)

**Comment by callahad** [comment]
I'd be in favor of explicitly labeling PWAs (there's even [a logo](https://medium.com/samsung-internet-dev/we-now-have-a-community-approved-progressive-web-apps-logo-823f212f57c9)) and treating them as a distinct platform from Web apps.

**Comment by callahad** [comment]
But more broadly, we need to think about the user experience of hitting that page. What job is a visitor trying to accomplish, and does the page serve that?

I suspect most people land on it looking for a Matrix client for their specific platform, which suggests that the hierarchy should be platform → client, not client → platforms like the Humble Store example.

...Perhaps sufficiently universal / multi-platform clients (Element, Fluffy) should be featured at the top? As a strawman, I'd deem "sufficiently universal" as being listed in both Android and iOS app stores, plus _either_ a webapp or a desktop version.

**Comment by thibaultamartin** [comment]
Since the new website was released, clients are now listed with the platform they support. At the moment the only caveat is that there is no indication of whether a web client is responsive or not.
