### ISSUE TITLE
switch from medium to ghost.org for riot.im blog?

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix.org#113]

**Comment by richvdh** [comment]
should this not be on https://github.com/matrix-org/riot-im ?

**Comment by Half-Shot** [comment]
This is tracked at https://github.com/matrix-org/riot-im/issues/47

**Comment by KitsuneRal** [comment]
I don't think such repo exists, at least GitHub shows me 404. Should it be somewhere under https://github.com/vector-im/ rather?

**Comment by ara4n** [comment]
for legacy reasons, github.com/matrix-org is the paid account with private repos on it, and github.com/vector-im is unpaid. the riot-im repo is private currently as it contains random NV stuff in it, so counterintuitively is stored on the matrix-org GH account. ideally we would switch it over.
