### ISSUE TITLE
matrix.org should not be pulling in https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.js 

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix.org#1142]
We should not be depending on external JS anywhere.  notyf.min.js should be self-hosted rather than pulled in from jsdelivr.net.

**Comment by afranke** [comment]
This dependency was introduced by 64265886c6 with the addition of the “Rate this page” popups. We have an open issue that suggests removing the widget (#809), and that would solve this issue as well.

**Comment by thibaultamartin** [comment]
We no longer depend on external js at all
