### ISSUE TITLE
Clicking a section header link brings too far down

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/matrix.org#1152]
**Describe the bug**
When clicking a section link in an article on matrix.org/blog, the title of the section is hidden because the window scrolls too far to the bottom.

**To Reproduce**
Example:
1. Click on https://matrix.org/blog/posts#the-process-of-improving-coverage
2. "The process of improving coverage" is too far up
 
**Expected behavior**
It would be expected to show the title of the section.

**Additional context**

callahad suggested:

> Yep. Setting scroll-padding-top: 5em; on html in the blog works well enough for me. I'll leave it as an exercise for the reader to figure out that best actual selector and value for this.
> 
> Whole article on how to make this happen at https://css-tricks.com/fixed-headers-on-page-links-and-overlapping-content-oh-my/

**Comment by tawandamoyo** [comment]
> Hello, I'm a first-time contributor and would like to help fix this anchor link issue. This could be resolved by moving the anchor link so that it is on the line before the heading.

Hey @raquelocasio , are you still interested in/ working on this?

**Comment by raquelocasio** [comment]
Hello, yes I'm still interested in fixing this. I'm a first-timer so I'm not quite sure how to access the HTML and CSS to fix it. Do I just "view source" to make a copy?

**Comment by raquelocasio** [comment]
> > Hello, I'm a first-time contributor and would like to help fix this anchor link issue. This could be resolved by moving the anchor link so that it is on the line before the heading.
> 
> Hey @raquelocasio , are you still interested in/ working on this?

Hello, yes I'm still interested in fixing this. I'm a first-timer so I'm not quite sure how to access the HTML and CSS to fix it. Do I just "view source" to make a copy?
