### ISSUE TITLE
Sydent article link broken

### ISSUE THREAD

**Issue by callahad** [matrix-org/matrix.org#1156]
The "last time" link in the header of https://matrix.org/blog/2021/12/10/type-coverage-for-sydent-annotation is broken. It should ultimately point to https://matrix.org/blog/2021/12/03/type-coverage-for-sydent-motivation but currently points to `2021-12-03-sydent-typing-1.mdx`

@DMRobertson this one's for you :)

**Comment by DMRobertson** [comment]
Well, I guess I never tested this properly. I assumed that the static site generator was clever enough to rename the link for me. I guess not.

Can we have a linter which checks that article links don't 404?
