### ISSUE TITLE
[site] Add more recent tweets

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix.org#1230]
The current tweets are from 2019, I think it'll add some creditability feeling to the site if tweets from 2020 and 2021 were added.

**Comment by thibaultamartin** [comment]
We no longer display tweets on the frontpage:

- From a SEO perspective they don't bring much
- They require regular maintenance (i.e. removing the tweet of someone who had changed their PP for a middle finger, updating them regularly)
- They make the client reach out to Twitter to get information, which is leaky
