### ISSUE TITLE
[site] Add rust-sdk to the prominent SDKs

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix.org#1232]
![image](https://user-images.githubusercontent.com/22740616/149942781-7135356c-2092-40ed-aae9-f10d1bbc3d6e.png)

It'd be nice if matrix-rust-sdk could be displayed here as well :)

**Comment by afranke** [comment]
You haven’t mentioned which page that screenshot was taken from. It doesn’t seem to be https://matrix.org/sdks/ (Homepage → Discover → SDKs) and I failed to find other places where this could live on matrix.org

**Comment by ShadowJonathan** [comment]
It's the homepage, scrolled down a bit

**Comment by afranke** [comment]
The new homepage doesn’t feature any SDK anymore. This can be closed as it has become irrelevant.

**Comment by thibaultamartin** [comment]
Good call, thanks Alexandre
