### ISSUE TITLE
On mobile, homepage is able to be scrolled to the side

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix.org#1244]
![image](https://user-images.githubusercontent.com/22740616/151787965-e1bf5487-1f3e-4f56-9c5f-1753c9fcb48b.png)

This is a few seconds into loading the page, I suspect the Twitter widget does not interact nicely with the CSS.

This is on an iPhone 11 resolution screen, 100% zoom.

**Comment by ShadowJonathan** [comment]
Fwiw, after exiting and returning to safari, the page seems to align the tweets like the following;

![image](https://user-images.githubusercontent.com/22740616/151788917-51727f66-2a91-4772-8b8f-1699f147f50e.png)

![image](https://user-images.githubusercontent.com/22740616/151788937-7398f58e-df87-4263-98b3-8de0df97828d.png)

**Comment by thibaultamartin** [comment]
This is fixed on the [upcoming version of matrix.org](https://matrix.turbo.fish), I'm closing the issue to keep track of what's left to do before the grand opening. Feel free to reopen if I missed something!
