### ISSUE TITLE
Curate the "try matrix now" page somehow

### ISSUE THREAD

**Issue by non-Jedi** [matrix-org/matrix.org#125]
It would be best to also hide some outdated and no longer developed projects
(looking especially at the homeserver section) on a separate page. Maybe we
could sort projects by recent activity somehow? The page right now is great for
people like me who kind of know what's out there and want to find something
specific, but I can't imagine its helpful to new users.

**Comment by ara4n** [comment]
@benparsons is working on precisely this atm, with some input from experiments that @uhoreg has been doing. perhaps we use this bug to collate everyone else’s input too? I know @Matrixcoffee has also been looking into it.

**Comment by benparsons** [comment]
@non-Jedi you're absolutely right, there are a few changes in form and content we can do to improve the state of that page, we'll also start including an indication of how recently maintained the projects are.

I have some changes I'm working on right now, which will also address some of the points @uhoreg has experimented with - particularly new metadata and sorting/filtering.

In the medium term, the features I'd like to produce for this page are:

- last updated timestamps
- sort by updated/maturity/category
- distinguish abandoned/alive/mature, but without actually removing "inactive" projects
- some way to include more user-contrib updates, possibly via a wiki (tbc)
- filter by maturity/type/language etc

@non-Jedi how does this sound? Is there anything else you'd like to see from this page?

**Comment by non-Jedi** [comment]
@benparsons all of that sounds great, especially compared to what we have now. I
think that in addition to what you described, it would also be really positive
from a marketing standpoint to have a manually curated set of the best, most
polished things the matrix world has to offer above the fold on that page. So
when a new potential user goes there, the first thing they see is a bunch of
clients, servers and apps that they can use right away (user or sys-admin facing
stuff only) and have a good experience with, but if they scroll down there's all
the other rich filtering and sorting on the rest of the matrix world.

I know doing manual curation like that introduces concerns about favoritism, but
I really do think it'd be a hugely positive thing. For the list, off the top of
my head:

- Riot
- nheko
- Quaternion
- Weechat script (?)
- t2bot.io
- Synapse
- mxisd
- go-neb (make sure blurb mentions all capabilities)
- IRC bridge
- Gitter bridge
- matrix-appservice-email (maybe?)

**Comment by Matrixcoffee** [comment]
Try Matrix Now already has a curated list of clients at the top, by the way. Perhaps update that as a quick first cut, before starting on more substantive changes.

**Comment by Matrixcoffee** [comment]
As for how I'm using the project -- [FAQBot](https://github.com/Matrixcoffee/FAQBot) pulls the projects information straight from git, and converts all the information into questions, so you can ask it things like "What is nheko?" "Where can I find nheko?" "Who is the author of nheko?" and so on.

This has not gone without problems (#103), so I'm very interested in how the project metadata will change, and @uhoreg's project (which I didn't know about before now) also looks very promising from my POV.

(If any of you wants to play with how FAQBot "sees" try-matrix-now, best do so in [#test-bot:matrix.org](https://matrix.to/#/#test-bot:matrix.org) so as not to spam people.)

**Comment by Matrixcoffee** [comment]
Finally, you might want to consider pulling https://matrix.to/ into this curation effort as well, as its list of clients is apparently entirely separate, and could benefit from all the information being managed in one single place.

**Comment by benparsons** [comment]
Really helpful, thanks @Matrixcoffee, I'm going to play with FAQBot now. I definitely intend to make more metadata (including everything you mention in #103) available in the project files ASAP.

@non-Jedi wrt the curation, I want to speak to @ara4n about this, may already be some thinking about what to include here.

**Comment by ara4n** [comment]
i’d prefer that we avoided manual creation entirely if we can help it, to avoid accusations of favouritism. A good example is a project like Fractal which looks to be an excellent client, now part of the core of GNOME if i understand correctly, but isn’t on the list above.  Instead it’d be much better if it could be crowdsourced through ratings or popularity or whatever and we show the top 10 in each category.

The original intention for matrix.to was to source the client list from the same datastore as Try Matrix Now - it would be fab to merge them, although i think matrix.to could do with some other niceness first (eg remembering your fav client and autoredirecting by default)

**Comment by non-Jedi** [comment]
Totally get that, and Fractal looks very neat (first time I've seen it). If only we had some sort of decentralized reputation and identity system for doing the rating/voting with... ;) I'm really excited that y'all are putting effort into this; let me know if there's anything I can do to help.

**Comment by benparsons** [comment]
Updates have been made to https://matrix.org/docs/projects/try-matrix-now.html.

Still more work needed, so pushing to a project for next month.

**Comment by aaronraimist** [comment]
There probably needs to be some kind of criteria that a project should meet before it gets added to Try Matrix Now. For example kacki only has 2 commits, both on the same day in January. https://github.com/synopia/kacki

Projects like that should maybe be added to a more exhaustive list but probably shouldn't be added to the Try Matrix Now page.

**Comment by benparsons** [comment]
I'm going to close this issue.

Now that separate pages are available for clients, bridges and SDKs (and bots, though page needs to be updated), try-matrix-now serves a more "complete list" function.

Also, this page now defaults to hiding `Not actively maintained` projects, which further thins the list. If there are inappropriate projects on this page then the solution is to update the data on those project pages, rather than further changing this page.
