### ISSUE TITLE
Client Server API guide discourages its usage, but proposes no alternative

### ISSUE THREAD

**Issue by tadzik** [matrix-org/matrix.org#1261]
**Describe the bug**

https://www.matrix.org/docs/guides/client-server-api is a page that commonly wins the SEO game when searching for Matrix API.

It greets the user with a warning: “This guide is badly outdated and should not be used anymore! It is only kept for posterity”.

It doesn't, however, say what the visitor should use instead, which is not very helpful.

**To Reproduce**
1. Go to https://www.matrix.org/docs/guides/client-server-api
2. Read the warning
3. Get frustrated

**Expected behavior**

The warning should say something along the lines of "consult https://spec.matrix.org/latest/client-server-api/ instead", or the guide page should redirect there straight away.

**Comment by thibaultamartin** [comment]
This is how this page is going to look like in the Zola rewrite.

![Screenshot 2022-10-25 at 10-21-09 🛠️ Matrix org - Client Server API](https://user-images.githubusercontent.com/1688309/197721955-0b957580-a018-444c-aab6-08f99fff9f0e.png)

The documentation page linked looks like this, at the time of writing this comment

![Screenshot 2022-10-21 at 11-14-06 🛠️ Matrix org](https://user-images.githubusercontent.com/1688309/197722307-7a3628b0-3d1b-4b33-9e23-b764174d0aa6.png)

Do you think it's explicit enough? The developer docs section hasn't been refreshed yet, but I definitely want to add a link to spec.matrix.org
