### ISSUE TITLE
Can't see past messages

### ISSUE THREAD

**Issue by mrlogick** [matrix-org/matrix.org#1315]
I did a video to explain the problem:
[[video](https://odysee.com/@mrlogick:8/matrix_org_bug:7?r=BmfALtvHo7ztiwsWGLpK7Ph2TbURuiU6)]

https://user-images.githubusercontent.com/558581/164349532-f517e6df-b8f5-4f58-8008-340d777c14fe.mp4

- `User A` creates a room, and invites `user B`
- `User B` joins the room, but he cannot see past messages
(even logging out and coming back with both users)

I think the problem is due to the fact that I tried everything within the same web browser. If I try with two browsers (one for each user), both online at the same time, past messages appear.

I re-tried with my own private server (with synapse), instead of matrix.org, and even with several matrix clients, but the problem still remains.

**Comment by MadLittleMods** [comment]
Please create an issue on https://github.com/vector-im/element-web/issues (I can't transfer an issue across GitHub organizations)

This issue tracker is for https://matrix.org/, the marketing site itself, not the `matrix.org` homeserver.

**Comment by mrlogick** [comment]
issue moved [here](https://github.com/vector-im/element-web/issues/21868).
