### ISSUE TITLE
Great discussion about new user onboarding docs/process

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix.org#134]
https://riot.im/develop/?#/room/#offtopic:matrix.org/$15235926071169POAUj:disroot.org

**Comment by benparsons** [comment]
> I think Matrix needs some introduction/entry-point website for new users, that is not linked (at least not clearly) to New Vector, and doesn't favor any homeserver (similar to how joinmastodon.org is)
05:10 riot.im is currently the entry point for most new users, and that funnels almost everyone to matrix.org and is literally the website of New Vector

**Comment by JokerGermany** [comment]
I think the ENTRY Site of matrix.org should be done more end user friendly.
The end User should be the target group and then guided away.
In my Opinion it's should be the opposite as the actual appearance.
The "Try Now" Button should be a button for developers and the other part of the website should be for end users.

**Comment by thibaultamartin** [comment]
This seems obsolete as of 2023:

- Try Matrix has been revamped (and will keep being improved)
- #1570 will allow users to pick a homeserver
- We seem to agree that the way to go is to lower the friction to entry (in practice: allow people to get set up quickly on matrix.org) and then both allow technically and incentivise people to move to another homeserver (with account portability being worked on right now)
