### ISSUE TITLE
FAQ advertises Element as only mobile Client

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/matrix.org#1342]
https://matrix.org/faq/#where-can-i-find-a-mobile-app%3F only mentions element as do some other sections while other sections of the FAQ also mention other community clients.

Due to the association of element and the matrix foundation this in particular makes it feel like advertisement and is probably not intended as such.

**Comment by thibaultamartin** [comment]
The FAQ has been deprecated, so this issue is no longer relevant :)
