### ISSUE TITLE
Favicon looks bad in the dark-themed browser

### ISSUE THREAD

**Issue by 532910** [matrix-org/matrix.org#1355]
![image](https://user-images.githubusercontent.com/14617699/172110368-77965c52-bf6f-4020-aa5c-522e79f925f2.png)

Square braces are dissipated.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/matrix-org/matrix.org/issues/741 where I've adapted that issue to be a more "modernize the favicon" type of issue
