### ISSUE TITLE
Define “glossy”

### ISSUE THREAD

**Issue by chloekek** [matrix-org/matrix.org#1359]
**Is your feature request related to a problem? Please describe.**

On the web page at https://matrix.org/clients-matrix/ some clients are said to be “glossy”. But it’s not clear what this means.

**Describe the solution you'd like**

For the web page at https://matrix.org/clients-matrix/ to define what a “glossy” client is.

**Describe alternatives you've considered**

I tried to look up the term “glossy” in the context of chat clients but could not find relevant definitions.

**Comment by MadLittleMods** [comment]
@chloekek It means polished, fancy, and slick feeling. Those clients look nice and are fully-featured.

For reference, the meaning of `glossy` is clear to me as a native English speaker.

**Comment by afranke** [comment]
FWIW non native here and it was clear to me as well.

**Comment by chloekek** [comment]
I see, thanks. I thought it was a technical term.
