### ISSUE TITLE
Remove mention of RPM builds

### ISSUE THREAD

**Issue by FlanOfHarmony** [matrix-org/matrix.org#1362]
On [this page](https://matrix.org/docs/projects/client/element), we're being told about the RPM package builds by Taw, but  those builds are no longer allowed for COPR because of non-free software and on March 1st Taw shut down the project as discussed [here](https://copr.fedorainfracloud.org/coprs/taw/element/).

**Comment by thibaultamartin** [comment]
There is no mention of rpms anymore in the new website
