### ISSUE TITLE
Add information about E2EE support in client details

### ISSUE THREAD

**Issue by MikeEdu** [matrix-org/matrix.org#1363]
**Is your feature request related to a problem? Please describe.**
Not a problem, but an inconvenience. As E2EE is a major marketing point, it would be nice to quickly see which clients do support it.

**Describe the solution you'd like**
An additional entry in client details like https://matrix.org/docs/projects/client/element-android.
Ideally it would look like this:
**E2EE**    <yes/yes (not audited)/partial/no>     (Or additional option i can't think of right now)

I don't know how much effort it would be to do so, so a basic version, which only say "yes" or "no" would be OK too for now.

**Describe alternatives you've considered**
The alternative is to search each clients website/github page, which is very time consuming.
Thus the overview would make it much easier for users.

**Comment by aaronraimist** [comment]
Yes it should probably be specified on the page for each client but https://matrix.org/clients-matrix/ does provide an overview of which clients support which features.

**Comment by opusforlife2** [comment]
The page you linked needs to be made more prominent on the website, I think. Right now it's 3 levels deep.

**Comment by thibaultamartin** [comment]
Information about E2EE is now part of the clients details
