### ISSUE TITLE
add timepath's xonotic chat client

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix.org#138]
https://xonotic.gitlab.io/-/xonotic-data.pk3dir/-/jobs/1145499/artifacts/public/d0/d44/lib_2matrix_2matrix_8qc.html

**Comment by benparsons** [comment]
Getting more info on what's been done.

**Comment by ara4n** [comment]
for stuff like this i'd probably just get at least a placeholder on the site.  In this instance I'd link to Xonotic (http://www.xonotic.org), describe it as in-game chat, and probably alpha grade.  We can then flesh it out with more details as it comes in. It'd be a shame to have the entry lost entirely due to lack of details. (ping @TimePath to provide some details though - istr there was a really fun screenshot of matrix embedded in the gameplay :)

**Comment by benparsons** [comment]
yep got a chat going :D

**Comment by TimePath** [comment]
Bit of an update, there's some ongoing work to pull the usual chat UI out of the engine and into the game code. Once that's complete, it might start being used more seriously once we can figure out how we want to map our users to matrix users

**Comment by aaronraimist** [comment]
This got added to the website at some point https://matrix.org/docs/projects/client/xonotic but it has basically no information on what it is
