### ISSUE TITLE
Posts are always released at UTC midnight

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix.org#1405]
#### Describe the bug
When trying to subscribe to a feed via [this feed link](https://matrix.org/blog/feed), all posts show (for some reason) that they’ve been published at 2 AM exactly in the morning.

I’m currently in the Amsterdam/Netherlands timezone, using Reeder, which produces this;

<img src="https://user-images.githubusercontent.com/22740616/185153691-024a60d4-3184-4086-9756-a4ed73355e2a.png" width="642">

The outcome of this is that I often miss matrix.org posts in my reader as they get pushed to the beginning of the day, below a bunch of other posts.

#### Expected behaviour
A realistic publication time, or at least UTC midnight.

**Comment by thibaultamartin** [comment]
This is no longer the case for (future) blog posts since the Zola migration :)
