### ISSUE TITLE
Unable to npm install on windows for multiple reasons

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/matrix.org#1413]
**Describe the bug**
Hi. It seems like the gatsby install fails for a few reasons.

First, the airbnb eslint rules cause a peer dependency error needing me to use `--legacy-peer-deps`.

Secondly, sharp fails to compile on windows. This seemingly is https://github.com/lovell/sharp/issues/2301 which was fixed 2 years ago.

~~It seems like updating sharp would fix this, but as this is pulled in by gatsby I assume it may actually be a lot harder to do :/~~

Seems like updating just `gatsby-plugin-sharp` may be enough

**Comment by MTRNord** [comment]
For reference sharp `0.26`+ fixes the issue and matrix.org depends on `0.25.1` according to the lockfile

**Comment by thibaultamartin** [comment]
No longer relevant since we don't rely on Gatsby anymore, long live Zola \o/
