### ISSUE TITLE
Upgrade to gatsby v4 - This is not an issue but more a hint on "how far did I get"

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/matrix.org#1416]
I tried to migrate this. I ended up not finishing it after 2 days of work as it seems that multiple MDX files in a single page (FAQ page) is not any more supported, and queries in templates are not executed anymore which makes all posts fail. Also, `MDXRenderer` was removed. Making `allMdx` not usable for rendering pages like used in here. After talking to the gatsby people it seems like this is and never was officially supported anyway. So I deem this migration impossible.

Either way, here is how far I got in case this will be of any use ever: https://github.com/matrix-org/matrix.org/compare/master...MTRNord:matrix.org:MTRNord/upgrade-gatsby

The commits do explain some stuff on what happens there.

**Comment by MTRNord** [comment]
(Feel free to close this. This is just to record this in case it ever gets useful for someone. So just that it does not get lost)

**Comment by MadLittleMods** [comment]
@MTRNord Create a pull request so it's easier to look at and then we can close that

**Comment by MTRNord** [comment]
> @MTRNord Create a pull request so it's easier to look at, reference, and comment and then we can close that.

Sure I can do that :)

**Comment by MTRNord** [comment]
@MadLittleMods Done at https://github.com/matrix-org/matrix.org/pull/1417

**Comment by MadLittleMods** [comment]
Thanks @MTRNord! I think the PR will track this better 👍
