### ISSUE TITLE
s/freenode/libera/

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix.org#1427]
Replace `freenode` with `libera` in things like https://matrix.org/docs/guides/types-of-bridging

**Comment by Chealer** [comment]
Greetings Matthew and thanks for your interest,
Being clear about the issue you report will help us process it. The report's title and description greatly influence its clarity. Using sentences - ideally written in English - in the description multiplies the chances that an issue can be solved.

**Comment by realvineeths** [comment]
hey @ara4n do we need to replace just in that  page or through out the code?

**Comment by thibaultamartin** [comment]
Obsolete since the deployment of the new website
