### ISSUE TITLE
"How do I get an account and get started?" is "recursive"

### ISSUE THREAD

**Issue by Chealer** [matrix-org/matrix.org#1466]
**Describe the bug**
[The _How do I get an account and get started?_ section of the _FAQ_ page](https://matrix.org/faq/#how-do-i-get-an-account-and-get-started%3F) does not explain how to get an account. Instead, it reads:

> The quickest way is to [pick a client](https://matrix.org/blog/try-matrix-now) and sign up.

I imagine "sign up" was supposed to link to some other page, but it doesn't.

**To Reproduce**
This is presumably not a behavioral defect.

**Expected behavior**
This is presumably not a behavioral defect.

**Screenshots**
![image](https://user-images.githubusercontent.com/486141/192808806-0dfb77dc-9edd-4586-a1e4-4970eca0f3c0.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows
 - Firefox
 - 105

**Smartphone (please complete the following information):**
N/A

**Additional context**
I just learned that Mozilla Thunderbird now supports Matrix and wondered if I should use it. After investigating the matter for 10 minutes, it remains most unclear whether this project has become mature enough to start testing it.

**Comment by Chealer** [comment]
Thank you Aaron
That could make sense. In that case, specifying that the client picked needs to allow account creation would solve or at least help with this.

**Comment by thibaultamartin** [comment]
I believe the new docs solve this
