### ISSUE TITLE
Consider adding a security.txt

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/matrix.org#1468]
While matrix.org has a security page, https://securitytxt.org/ seems to become a standard and helps to have the key points in a structured format which people can easily access and integrate in whatever tools people may be using.

It would be great if it could be added to the page. :) Google and others use it, and it is recommended by many people to have it :)

**Comment by MTRNord** [comment]
A valid one for matrix.org would probably be:

```
Contact: mailto:security@matrix.org
Expires: 2022-01-30T23:00:00.000Z
Encryption: https://matrix.org/.well-known/pgp-key.txt
Acknowledgments: https://matrix.org/hall-of-fame
Preferred-Languages: en
Canonical: https://matrix.org/.well-known/security.txt
Policy: https://matrix.org/security-disclosure-policy/
```

(I guess making a PR doesnt make sense as the well-known path likely is handled extra due to the matrix well-known files)

**Comment by aaronraimist** [comment]
@MTRNord You should be able to make a PR. The Matrix .well-known files are in this repo. https://github.com/matrix-org/matrix.org/tree/master/content/.well-known

**Comment by MTRNord** [comment]
> @MTRNord You should be able to make a PR. The Matrix .well-known files are in this repo. https://github.com/matrix-org/matrix.org/tree/master/content/.well-known

Oh I wasnt aware :D Well then I will do that tomorrow :)

**Comment by dkasak** [comment]
We've previously considered this internally, but...

> helps to have the key points in a structured format which people can easily access and integrate in whatever tools people may be using

This is a double-edged sword, since it can easily lead to increased automated spam. To quote Foudil/EdOverflow, the originator of security.txt:

> “This is actually stated in the specification itself, and it’s incredibly important to highlight that organizations that implement this are going to get flooded,” Foudil told KrebsOnSecurity.

That said, I'm inclined to try it out this time and roll back if things start to get ugly.
