### ISSUE TITLE
RSS-Feed Schema Error

### ISSUE THREAD

**Issue by mcnesium** [matrix-org/matrix.org#1470]
[The W3C Feed validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fmatrix.org%2Fblog%2Ffeed) claims:

> Schema Error: XML document with no namespace; cannot determine any schema to use for validation.

for `https://matrix.org/blog/feed`

**Comment by thibaultamartin** [comment]
https://support.google.com/webmasters/thread/54181005/w3-validator-is-throwing-schema-error-cannot-find-preset-schema-for-namespace-for-sitemap-xml-file?hl=en seems to suggest a common issue with W3C's validator itself

https://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2Fmatrix.org%2Fblog%2Ffeed considers that the feed is valid.

I'm closing the issue as resolved, please reopen if I missed something important.
