### ISSUE TITLE
RSS-Feed shows only fractions of post

### ISSUE THREAD

**Issue by mcnesium** [matrix-org/matrix.org#1471]
The [RSS feed](https://matrix.org/blog/feed) serves only a tiny fraction of a blog post ([again](https://github.com/matrix-org/matrix.org/issues/408)), e.g. recently:

> Synapse 1.68 released
> September 27, 2022 at 2:00 AM
> Hey everyone, it's time for a new Synapse release! Synapse 1.68 just dropped, let's have a look at what's inside. Dependency changes As…

It would be great to have the full post in feed readers again :smiley_cat:

**Comment by ptman** [comment]
Indeed, no longer a problem. Quite the opposite problem instead.
