### ISSUE TITLE
Rework the documentation

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/matrix.org#1505]
## Goal of the page

The documentation aim to be as product-agnostic as possible. In some specific cases (such as when talking to the general public), the flagship clients are used to make things more concrete and easier to understand.

Product-specific documentations belong to the products themselves and should not be hosted here.

Legacy documentations need to be ported to Zola, and redirections need to be set-up so the old links still work.

- Everyday People should find everything they need to get started using Matrix with their family and friends
  - Create a Matrix account (opinionated: on matrix.org because the general public doesn't care about homeservers, using Element because it's the flagship client), invite friends, create a small group chat
  - Follow a matrix.to link to join a small group chat
- Community Managers should be able to
  - Create an account on matrix.org (with an explanation that they can get their own domain eventually)
  - Create rooms
  - Understand aliases and matrix.to links
  - Understand Power Levels
  - Understand moderation
  - Switch providers (either by picking one from the hosting page, or by becoming one themselves)
- Developers should be redirected
  - To product-specific tutorials
  - To the ecosystem pages
  - To the spec
- Entrepreneurs TBD

## Content of the page

The landing page of the documentation section should contain tiles on top:

- One with a large 🧑, and the title "I want to start chatting using Matrix"
- One with a large 👪, and the title "I want to use Matrix for my community or organisation"
- One with a large ⚒️, and the title "I want to develop a client, bridge or bot"
- One with a large 🕸️, and the title "Legacy Docs"

**Comment by aaronraimist** [comment]
> The documentation aim to be as product-agnostic as possible. In some specific cases (such as when talking to the general public), the flagship clients are used to make things more concrete and easier to understand.

In some specific cases, such as the general case that most people fall into 🤔

I'm guessing you are already going to need to create two different versions for the getting started tutorial, one for Element mobile and another for Element Web/Desktop. It wouldn't be *that* much more work to create a couple more for let's say FluffyChat and Cinny.

> Create a Matrix account (opinionated: on matrix.org because the general public doesn't care about homeservers

They don't care because they don't know they should care. The whole point of documentation is to provide instructions and best practices for how to do something.

Most likely they are coming from another instant messaging app which has no concept of picking a server. The site should give a brief and gentle introduction to the topic. It doesn't have to be detailed and the site can still suggest matrix.org but it should also at least vaguely mention that you can pick a server  run by your friends, yourself, or an online community.

> Create an account on matrix.org (with an explanation that they can get their own domain eventually)

It should be honest and state that there is currently no simple way to switch to another domain

**Comment by thibaultamartin** [comment]
Hej Aaron, I turned my really early notes into an issue for transparency, and I'm glad you caught some issues from it.

Just to let you know the constraints I'm dealing with for the docs:
1. Matrix is very flexible, which allows a lot of combinations of several things. For complete newcomers who are not very tech-savvy and not necessarily interested in Matrix itself but just want an instant messaging that works, it can be a little overwhelming.
2. We need documentation which is maintained in the long run. The more documentation there is, the more there is to update. I would rather have concise and up to date docs than pages and pages of outdated ones

Your comment about "most people fall into" is entirely fair, the distinction was mostly between user docs and developer docs. Your suggestion to illustrate the documentation with one or two additional clients is a good idea. Adding new docs is not necessarily a lot of work, but monitoring the clients updates and re-taking the screenshots to keep the docs up to date is a significant effort. That's why I would want to limit the examples to two or three clients maximum.

You have another very good point about getting users to care about homeservers and why they would want to use something other than Matrix.org. There is definitely a need for a high level description of the concepts behind Matrix and how it works. I'm trying to make the barrier to entry to Matrix as low as possible so people can quickly get their hands on it, before diving deeper in the concepts. What I need to balance is:
- Making things concrete rapidly enough so people can play with Matrix
- Not explaining federation and homeservers concepts too late, because as you mentioned account portability is not a thing. The longer we wait, the higher the cost of switching away from Matrix.org, and I definitely don't want Matrix.org to be the Gmail of Matrix

I believe the best way to achieve it is to have a "Matrix Concepts" section to which we should route users [when they reach this paragraph](https://github.com/matrix-org/matrix.org/pull/1497/files#diff-f7bdfcb18a610eed86d52084e061b42c43ef2ad402c2361e907022d93a91661bR26-R31). I would also like to get a "For individuals" section in the Hosting pages of Matrix.org

> It should be honest and state that there is currently no simple way to switch to another domain

Here again good catch, this also comes from my notes quickly jotted down without too much context. What I had in mind here is that it's possible to create a Space and rooms with a Matrix.org account (and thus `:matrix.org` aliases) and transfer ownership (hand over PL100 in these rooms) and update aliases to your domain if you pick your own provider. At this point, I will route users to the hosting page too.

Thanks again for voicing your concerns, and I hope this addresses them. Keep the suggestions coming if you see more issues, it's truly helpful :)

**Comment by aaronraimist** [comment]
Thank you. That all sounds good to me. I am looking forward to the new site :)

**Comment by aaronraimist** [comment]
Here's an idea. As a precursor to creating several tutorials, you could have one tutorial that shows how to create an account, find your friend, and send them a DM using Element; but then at the end of the tutorial there is a screenshot from the receiving person's perspective showing them receiving the message in [FluffyChat, Cinny, Fractal, Nheko, gomuks, Syphon, etc].

That would at least help to introduce the idea that there are multiple interoperable clients while reducing the number of screenshots you have to take and copies of the tutorial you have to maintain.

**Comment by thibaultamartin** [comment]
That sounds like a clever way to do it indeed, I’ll definitely do that
