### ISSUE TITLE
Nonfunctional menu button in narrow view

### ISSUE THREAD

**Issue by AndrewKvalheim** [matrix-org/matrix.org#1508]
On [/faq/](https://matrix.org/faq/), when the window is less than 992px wide, a menu button appears at the top right corner:

> <img alt="screenshot of 991px wide viewport" src="https://user-images.githubusercontent.com/1844746/196057782-03a4bd54-8c4f-4d46-b94e-cee989fb2f35.png" width="991">

It does nothing when clicked. The browser console reports what looks to be a malformed jQuery selector tracing back to Webflow:

```
Uncaught Error: Syntax error, unrecognized expression: #what-is-matrix%3F
```

**Comment by Prakhar1701** [comment]
Hi @AndrewKvalheim, I am interested to work on this issue, please assign me this issue.

**Comment by snehilchhabria** [comment]
I can work on this issue if I am guided with clear instructions on the required solution.

**Comment by AshishPandagre** [comment]
I believe PR #1629 will fix this.

**Comment by harshlancer** [comment]
Is this issue still open to work?

**Comment by horizenight** [comment]
Still open for work ?

**Comment by indrasn0wal** [comment]
Please assign me the issue

**Comment by tony83033** [comment]
Hii @AndrewKvalheim sir could you pls assign me this issue

**Comment by anurag464** [comment]
Please brief, what the menu button should show?

**Comment by realvineeths** [comment]
U can check the readme for building after u have cloned it

How to build

    Make sure you have the prerequisites:
        Node.js and npm
        git clone https://github.com/matrix-org/matrix.org && cd matrix.org
    cd gatsby
    Run npm i to install dependencies
    npm run develop - It will take a while on your first build

Now you can visit the page you want to work on in the browser. For example: http://127.0.0.1:8000/docs/projects/try-matrix-now/

**Comment by VaibhavAPatil** [comment]
I am **interested** in **this Issue**. Can I do **Pull Request** or you can **assign** this **issue to Me**.

**Comment by Chaitu-Tatipamula** [comment]
hii i wanna get into this can you people help me out

**Comment by ABHIXIT2** [comment]
Am ii am using it on browser and it is working operfectly fine..

**Comment by B1TSH3LL** [comment]
i would like to work on this issue. please assign this to me.

**Comment by richvdh** [comment]
> i would like to work on this issue. please assign this to me.

I have hidden a large number of comments along these lines. As a reminder, in most open source projects, including this one, you do not need to request permission to work on an issue: just open a pull-request with your solution. (However, note that this project is in the middle of a rewrite so please raise any pull-requests against the `zola` branch).

**Comment by gitabhisingh** [comment]
^ PR has been created please review: @richvdh

**Comment by gitabhisingh** [comment]
PR for this fix: https://github.com/matrix-org/matrix.org/pull/1696

**Comment by gitabhisingh** [comment]
@AndrewKvalheim I am not able to find these HTML changes in zola repo, I see they got migrated to md file. If that's intentional then we can close this issue then.

**Comment by AbhiJain2196** [comment]
[[FIX] Nonfunctional menu button in narrow view #1508 #1699](https://github.com/matrix-org/matrix.org/pull/1699)

**Comment by AbhiJain2196** [comment]
#[[FIX] Nonfunctional menu button in narrow view #1508 #1699](https://github.com/matrix-org/matrix.org/pull/1699)

**Comment by AbhiJain2196** [comment]
**[FIX] Nonfunctional menu button in narrow view #1508 #1699**(https://github.com/matrix-org/matrix.org/pull/1699)

**Comment by AbhiJain2196** [comment]
**[[FIX] Nonfunctional menu button in narrow view #1508 #1699]**(https://github.com/matrix-org/matrix.org/pull/1699)

**Comment by AbhiJain2196** [comment]
**[[FIX] Nonfunctional menu button in narrow view]**(https://github.com/matrix-org/matrix.org/pull/1699)

**Comment by gitabhisingh** [comment]
@AndrewKvalheim please be professional enough to at least reply instead of just responding by emojis. There are a lot of contributors I see in the comments who spent their precious time to fix this issue and you all don't even care to reply or provide a direction!

**Comment by thibaultamartin** [comment]
With the new website this issue is now obsolete
