### ISSUE TITLE
Deploy a CI check to make sure zola builds and there are no dead links

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/matrix.org#1521]

**Comment by jplatte** [comment]
Build check is there, link check is probably not a good idea because we have *many* links so the check will take very long and has a high chance to fail because of spurious issues or external changes.

**Comment by MTRNord** [comment]
> Build check is there, link check is probably not a good idea because we have *many* links so the check will take very long and has a high chance to fail because of spurious issues or external changes.

How about doing a weekly ci job for link checks? Which could open an issue on deaf links. Might be a little more work to setup but nice to them go and replace the dead links with webarchive links
