### ISSUE TITLE
Rework the Bots page

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/matrix.org#1540]
## Goal of the page

- Not very relevant for everyday people?
- Make Matrix attractive as a platform for community managers by showing a range of bots they can deploy to serve their community
- Show developers that there is already a mature bot ecosystem and that they can easily develop one of their own
- Show entrepreneurs that there is already a mature bot ecosystem and that they can build commercial products for that ecosystem

## Content of the page

A set of bot cards, à la https://t2bot.io (but probably a larger grid, with for each card a name, two lines description, link to project)

For each bot we would like to at least have the following data, even if not everything is displayed.
- Bot name
- Maintainer
- Description
- Link to documentation
- Last release date
- Maturity
- Licence

**Comment by imbev** [comment]
What if each bot had a category/tags field? Unlike tbot.io's "suite" of bots, the matrix.org bot selection is sourced from a more disorganized community of bot developers. It could be useful to filter by "fun", "moderation", "subscription", "tool", etc.

**Comment by thibaultamartin** [comment]
The implementation is very basic as of now, but at least it's not blocking the grand opening. I'm open to ideas on how to make the page better!
