### ISSUE TITLE
Style the Zola site header

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix.org#1545]
The site header on the zola branch has a new feature: Sub-items for a few of the header links. We need to write some CSS to make it look good, both on desktop and on mobile.

**Comment by jplatte** [comment]
To clarify, this is about the following two things:

![Screenshot_2022-11-02_111737](https://user-images.githubusercontent.com/951129/199464585-8a3f2dda-218c-405e-8527-6e8f8db4f6a7.png)
![Screenshot_2022-11-02_111721](https://user-images.githubusercontent.com/951129/199464660-e1a62aa7-4ffc-454e-8f40-eca59c596133.png)

**Comment by shivakr07** [comment]
hey @jplatte i would like to work on this issue. could you please assign this task to me ?

**Comment by thibaultamartin** [comment]
Hi @shivakr07, we develop in the open. If you want to help us with this issue, you can give it a go. I suggest getting familiar with https://www.getzola.org/, the framework we use for the new version of matrix.org. Then you can start a new branch based on the `zola` branch of this repository.

All help is welcome, but for the sake of expectations management I must say that the Matrix.org Foundation doesn't plan internships around the Matrix.org website for this summer :)
