### ISSUE TITLE
Connectivity to the server has been lost.

### ISSUE THREAD

**Issue by Yadiel9p** [matrix-org/matrix.org#1602]
my element was working just fine from this morning to 7:21pm im not sure if the company of element is aware of this but im hoping it can be fixed and my internet is working well and is always on

![Screenshot (602)](https://user-images.githubusercontent.com/122074136/210933241-b55e3572-3250-47f4-8c14-a9b95d34c21e.png)

**Comment by turt2live** [comment]
Thanks for reporting this issue. This will be related to an ongoing incident at matrix.org - please follow https://github.com/matrix-org/matrix.org/issues/1601 for updates.
