### ISSUE TITLE
my element on my phone is having issues 

### ISSUE THREAD

**Issue by Yadiel9p** [matrix-org/matrix.org#1603]
i have idea what is going on with element but i hope it can be fixed as soon as possible

![Screenshot_20230105-212821_Element](https://user-images.githubusercontent.com/122074136/210934619-4380b54b-88ab-483a-8ad4-2edbd618535e.jpg)

**Comment by turt2live** [comment]
Thanks for reporting this issue. This will be related to an ongoing incident at matrix.org - please follow https://github.com/matrix-org/matrix.org/issues/1601 for updates.
