### ISSUE TITLE
Navigation Bar layout issue on small screen sizes

### ISSUE THREAD

**Issue by kanishkcs** [matrix-org/matrix.org#1615]
## Description
Upon accessing the website on a device with a screen size between 1059px to 993px, I noticed that the navigation bar slides underneath the main content. This can negatively impact the user experience, as it makes the navigation options less accessible and harder to locate.

I would like to suggest a solution to this issue by potentially adjusting the CSS and/or media query to ensure that the navigation bar remains visible and accessible on all screen sizes.

I have attached a screenshot of the issue for reference: 

![Screenshot of navigation bar [issue]
![image](https://user-images.githubusercontent.com/34246727/214027792-29db97a3-f721-42fd-8de6-07861ff685f3.png)

## Steps to reproduce
1. Access the website on a device with a screen size between 1059px to 993px (e.g. iPhone SE)
2. Observe the navigation bar sliding underneath the main content

## Expected outcome
The navigation bar should be visible and accessible at all times, regardless of the screen size.

## Severity
Medium

## Notes
- Kindly provide any additional information that may help in resolving this issue
- Thank you for your attention to this matter and I look forward to contributing to the resolution of this issue.

**Comment by dassudip2001** [comment]
can i solve this issue plz assign me

**Comment by kanishkcs** [comment]
bro , kindly look for any another issue , i have created a PR allready

**Comment by dassudip2001** [comment]
I think you can say  the issue is fixed right

**Comment by richvdh** [comment]
> bro , kindly look for any another issue , i have created a PR allready

If you have already proposed a fix, please link it here so that others can see it.

We do not assign issues in this project; anyone who would like to is welcome to contribute changes.

**Comment by Vansh-31** [comment]
is the issue still open?

**Comment by thibaultamartin** [comment]
The new website makes this issue obsolete
