### ISSUE TITLE
Features matrix is a bit overwhelming.

### ISSUE THREAD

**Issue by Scary-Guy** [matrix-org/matrix.org#1621]
I love the ability to see all of the different features, but it's a bit hard to compare everything.  So I have some suggestions...

The ability to select multiple platforms (like Linux and Android, because I want to install it on both) would be nice.  So tick boxes instead of the ratio buttons.

The ability to select by desired features would also be nice.  For example E2EE is a must.

Maybe the ability to click on a category headder and sort by that category?  Kind of like Wikipedia tables do.

**Comment by thibaultamartin** [comment]
You are absolutely right! That's something we intend to fix in the new version of Matrix.org, and this is tracked in #1538

I'm closing this issue as a duplicate.
