### ISSUE TITLE
E2EE guide: Correct the json object definition of an olm encrypted event

### ISSUE THREAD

**Issue by mujx** [matrix-org/matrix.org#163]
The e2ee guide currently states that the content of an event encrypted with olm should have the following structure (https://matrix.org/docs/guides/e2e_implementation.html#encrypting-an-event-with-olm)
```
{
  "algorithm": "m.olm.v1.curve25519-aes-sha2",
  "sender_key": "<our curve25519 identity key>",
  "ciphertext": "<encrypted payload>"
}
```
which is inconsistent with the previous paragraphs.

The ciphertext should be an object mapping from the Curve25519 identity key for the recipient device,
as it is already explained in https://matrix.org/docs/guides/e2e_implementation.html#m-olm-v1-curve25519-aes-sha2.
```
{
  "content": {
    "algorithm": "m.olm.v1.curve25519-aes-sha2",
    "ciphertext": {
      "ljb1QTjaFixBF9Z0v+vkqDFUeez8Y9AqV9QQ4HPc6G8": {
        "body": "Awog2xyRyO+VNbg2BfF7SFgzqWmQG ... K3Ps",
        "type": 0
      }
    },
    "sender_key": "a3tA5yqMRFHnqJ92AgStNgmJIQSgdcGzPPyb2Ec/snM"
  },
  "sender": "@bob:localhost",
  "type": "m.room.encrypted"
}
```

**Comment by benparsons** [comment]
@mujx so do you think it would be best to just replace the code block in https://matrix.org/docs/guides/e2e_implementation.html#encrypting-an-event-with-olm with yours?

**Comment by mujx** [comment]
@benparsons There is already an open PR for this https://github.com/matrix-org/matrix-doc/pull/1284/files#diff-97393012192762792a39fbd40349eaa5

**Comment by benparsons** [comment]
There is, but that PR references the matrix-docs repo, where the spec and API docs are stored, the guide you linked to in the first comment is in this repo (as it's just part of the website, not transcluded in the way the other repo is.)

I'm still (!) getting to grips with the docs myself, so I'm wondering if you think we can improve that page just by replacing that one code block, or if there needs to be a larger change.

**Comment by mujx** [comment]
I haven't thought too much about it so I don't have a more concrete set of changes for the e2ee guide but I think it will be best for implementors if it looked more like a tutorial.

It could be from a client point of view with pseudocode examples (using libolm) while referencing the actual spec which will have the struct definitions like the one above. Furthermore it could include diagrams (https://github.com/matrix-org/olm/issues/6), data flows & scenarios that clients should be aware of.

**Comment by benparsons** [comment]
Ok, thanks. Sounds like we need to really re-think the E2E related docs.

**Comment by uhoreg** [comment]
This is fixed already by linking to the spec, which now documents the event correctly.
