### ISSUE TITLE
SEO-optimise the new m.org

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/matrix.org#1630]
Google Page speed says [we're bad and we should feel bad](https://pagespeed.web.dev/report?url=https%3A%2F%2Fmatrix.turbo.fish%2F&form_factor=mobile).

Recommendations are:
- [x] Using a `<meta description="…">` tag for pages ([described here](https://developer.chrome.com/docs/lighthouse/seo/meta-description/?utm_source=lighthouse&utm_medium=lr))
- [x] Avoiding "Learn more"/"Read more" etc in links
- [x] [Create and serve a `robots.txt`](https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt) (relevant Zola doc: https://www.getzola.org/documentation/templates/robots/)

**Comment by whynesspower** [comment]
Consider assigning this Issue to me 🤚

**Comment by whynesspower** [comment]
@thibaultamartin Pull Request #1639 Solves this. Thank you!

**Comment by thibaultamartin** [comment]
Depends on #1770
