### ISSUE TITLE
Link broken and no detection software

### ISSUE THREAD

**Issue by ShalokShalom** [matrix-org/matrix.org#1631]
Hi there :) 

The documentation itself seems to be hard to find, or is again hosted somewhere else.

There seems to be no service installed, that tracks broken links. 

 This is the broken link, that I initially tried to fix. 

Old: https://matrix.org/docs/projects/server/synapse

"Arch Linux package from Johannes Löthberg:" 

New: https://archlinux.org/packages/community/x86_64/matrix-synapse/

**Comment by ShalokShalom** [comment]
Well, that just moves the problem. How would you detect a broken link in this case? 

At some point, you have to check if the link is valid

**Comment by MTRNord** [comment]
> Well, that just moves the problem. How would you detect a broken link in this case? 
> 
> At some point, you have to check if the link is valid

The software used for the new page (https://getzola.org) does come with a link checker that could be integrated in the Ci. This could at least notify about dead links.

**Comment by ShalokShalom** [comment]
Oh, you might want to add a tag on this one?

I can also reopen it for tracking.
