### ISSUE TITLE
Page cards don't behave like inline elements

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/matrix.org#1640]
In docs I can use a shortcode to create a "page card" (a more visible link to another page) like follows:

```markdown
### Rolling your own

People who either want or need to have on-premises can either pick a [server
implementation](/ecosystem/servers) they are comfortable with and install it
themselves, or get an on-premises support plan from [one of the providers the
Foundation knows](/ecosystem/hosting).

{{ page_card(
    title="Servers",
    path="/ecosystem/servers",
    summary="Browse all the server implementations, find the best suited for
             your needs and how to install it yourself.")
}}

{{ page_card(
    title="Another Card",
    path="/ecosystem/servers",
    summary="Oh no this card doesn't behave like an inline element.")
}}
```

Page cards are generated as

```html
<div class="page_card">
    <a href="{{ path }}" alt="Link to {{ title }}">
        <div class="wrapper">
            <div class="card_content">
                <h4>{{ title }}</h4>
                <p>{{ summary }}</p>
            </div>
            <div class="arrow"></div>
        </div>
    </a>
</div>
```

Unsurprisingly they behave like block elements.

![Screenshot 2023-02-01 at 13-33-00 🛠️ Matrix org - Switching Providers](https://user-images.githubusercontent.com/1688309/216043556-5220b3ae-22c7-436a-98f7-1d4fbeee5d54.png)

I tried using `.page_card { display: inline; }`, but the results are far from optimal.

![image](https://user-images.githubusercontent.com/1688309/216044115-cd8e90df-72f7-4d62-aba9-d5da8bd90b23.png)

I'm wondering how to make the cards behave like inline elements, without being completely cramped.

**Comment by jplatte** [comment]
Have you tried `display: inline-block`?

**Comment by thibaultamartin** [comment]
It does solve it mostly, though the cards are then not consistent in terms of height which is either fixed by using a min-height, or wrapping them around a flex. Unassigning Jonas to give me some time to think about it :)

**Comment by abhijain2003** [comment]
can i work on this?

**Comment by indrasn0wal** [comment]
May I work on this?
