### ISSUE TITLE
Website was not updated when master was updated

### ISSUE THREAD

**Issue by H-Shay** [matrix-org/matrix.org#1643]
I merged this commit https://github.com/matrix-org/matrix.org/commit/387f76cfd1bfc3a4957d8864faf25e2c36d120e7 into mater yesterday to add the 1.76 blogpost, but it seems that the live website has not been updated with the post. I don't see any failed runs in the github actions so I am not sure what happened...

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/216507503-debf5e64-67dc-41f0-ac69-5711366c8173.png)

it's in the artifact at least. Might be an error with the poke script that actually downloads & deploys?

**Comment by richvdh** [comment]
Rather odd. The webhook listener script had this to say:

```
Feb 01 17:44:50 horme.matrix.org matrixsite-redeploy-gha-webhook-listener[3097571]: INFO:root:Successful run of workflow '🌐 Build the matrix.org website' triggered by 'push' on branch master
Feb 01 17:44:50 horme.matrix.org matrixsite-redeploy-gha-webhook-listener[3097571]: INFO:root:Fetching https://api.github.com/repos/matrix-org/matrix.org/actions/runs/4067118426/artifacts
Feb 01 17:44:50 horme.matrix.org matrixsite-redeploy-gha-webhook-listener[3097571]: INFO:root:No suitable artifacts found
Feb 01 17:44:50 horme.matrix.org matrixsite-redeploy-gha-webhook-listener[3097571]: INFO:werkzeug:127.0.0.1 - - [01/Feb/2023 17:44:50] "POST / HTTP/1.1" 200 -
```

It is looking for an artifact whose name matches the regex `merged-content-artifact`; and there is (now) clearly one at https://api.github.com/repos/matrix-org/matrix.org/actions/runs/4067118426/artifacts. Indeed, I redelivered the webhook and it worked fine.

I can only imagine there is some race where the full artifact list is not immediately available, though we can clearly see from the logs on https://github.com/matrix-org/matrix.org/actions/runs/4067118426/jobs/7004131962 that ` Artifact merged-content-artifact has been successfully uploaded!` at 17:44:46, a clear 4 seconds before the deploy script tried to access it.

I'm going to write this off as "github being weird" unless it happens again.
