### ISSUE TITLE
Menu Button(navbar) not working properly in mobile view

### ISSUE THREAD

**Issue by rohinish404** [matrix-org/matrix.org#1659]
The menu button in mobile view is not working properly. When once clicked, i have to reload the whole page to open that menu again otherwise it is not getting opened.
Attaching a video below of the issue.

https://user-images.githubusercontent.com/92542124/219560361-2af18828-1568-4009-bca0-4a7b2dea0b67.mov

**Comment by OmAvhad** [comment]
I'm interested in this issue and would like to contribute to the project. Is it possible for me to be assigned to work on it?

**Comment by nsundriyal62** [comment]
i think this issue is still open because i checked it right ...

so i want to resolve it.

if you can not assign issue to anyone specificallly then i will generate a pull request other wise assign it to me,

i can solve this issue...

thanks..

**Comment by adarsh8848** [comment]
Can I have a chance to look into the issue and make any necessary changes?
If the issue has been resolved, could you please let me know what steps you took to fix it? Additionally, if there are any other improvements or suggestions you have for the navbar, I would be happy to implement them.

**Comment by thibaultamartin** [comment]
The issues has been solved when deploying the new site
