### ISSUE TITLE
Firefox: visiting blogs automatically offers matrix-dma-slides.pdf to download

### ISSUE THREAD

**Issue by enekonieto** [matrix-org/matrix.org#1691]
If I go to https://matrix.org/blog/posts in Firefox a popup appears asking where to save matrix-dma-slides.pdf

Firefox 111.0.1 (64-bit) (package from Mozilla Team's PPA instead of snap)
Ubuntu 22.04

**Comment by thibaultamartin** [comment]
I cannot reproduce on my machine but someone else mentioned this happened. Thanks for the report, I'll try to see how to fix it

**Comment by enekonieto** [comment]
Can I help in any way?

**Comment by Johennes** [comment]
Doesn't happen anymore to me after applying this setting (it was "always ask" before):

<img width="707" alt="Screenshot 2023-05-02 at 10 01 49" src="https://user-images.githubusercontent.com/1137962/235612128-37616df9-99e4-4c24-8f6f-2e2ebd744903.png">

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1662216

**Comment by enekonieto** [comment]
I does not happen anymore to me with no changes, it seems solved.
