### ISSUE TITLE
animations broken on front page of matrix.org on Safari

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix.org#17]
According to https://matrix.org/jira/browse/ORG-33

**Comment by aaronraimist** [comment]
Which animations? I don't see anything broken on current versions of the website and Safari.

**Comment by benparsons** [comment]
They must be referring to the animates at https://matrix.org/blog/home/#about (the d3.js network diagram.) Assuming that's right, I'm closing this. thanks @aaronraimist for pulling this back to the top of the list :D
