### ISSUE TITLE
Bots scrape author page instead of homepage (benpa to contact discord CS)

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix.org#170]
When posting https://matrix.org in a Discord message, Discord randomly finds https://matrix.org/blog/author/toml/ and displays the title of that page, instead of the homepage.

**Comment by benparsons** [comment]
@anoadragon453 can you still repro this?

`$ curl -I https://matrix.org/` leads to https://matrix.org/blog/home/

`curl -I https://matrix.org/blog/home/` 200s the homepage - no mention of toml anywhere.

**Comment by anoadragon453** [comment]
Indeed.

![image](https://user-images.githubusercontent.com/1342360/42885441-cc4b0956-8a55-11e8-8129-6e17e1772037.png)

Not sure how they're getting it. It's likely happening server-side as well so don't think we can sniff the request. Might be worth just pinging customer service.

**Comment by benparsons** [comment]
damn you @lampholder 

ok looks like the problem is their side, I'll contact them.

**Comment by anoadragon453** [comment]
Awesome, thanks.

**Comment by lampholder** [comment]
Are you sure this needs fixing? I kinda like it how it is 😛

**Comment by benparsons** [comment]
We're desperately trying to erase you from the platform

**Comment by anoadragon453** [comment]
Did we get anywhere with this?

**Comment by MTRNord** [comment]
I guess microdata tags would maybe fix this too from matrix.org side of things. As if they do it correct they may parse thoose for the url previews. And doing a simple test in browser matrix.org doesnt have any microdata on its main page

**Comment by turt2live** [comment]
/me waves the +1 flag

Had a minor accident when trying to link to matrix.org today where someone thought I was Tom.

**Comment by anoadragon453** [comment]
This is no longer an issue :)

![image](https://user-images.githubusercontent.com/1342360/95242278-dfa6ab00-0806-11eb-8e3f-f9f9cda84f7d.png)
