### ISSUE TITLE
Optimize the hero image for size

### ISSUE THREAD

**Issue by deepbluev7** [matrix-org/matrix.org#1717]
https://matrix.turbo.fish/assets/frontpage/hero_dancing_lines.svg is just a few lines, but it amounts to a 250kB download, which does cause a noticeable pop-in here. It should be possible to fit lines into 50kB.

**Comment by thibaultamartin** [comment]
https://css-tricks.com/tools-for-optimizing-svg/ has useful resources when it comes to optimising svgs

`scour` is usually quite useful, though I wonder if we could automate it either at the SSG or CI level

**Comment by deepbluev7** [comment]
Half of the points in that graphic are not even in the view boundary. Here I just deleted a few of them and then saved it as an optimized PNG using inkscape:

![hero_dancing_lines_smaller_exp](https://github.com/matrix-org/matrix.org/assets/16312324/b8b8f639-df93-4878-9714-98ff9a0d88a4)

You can probably do better if you spend more than 5 minutes on it, but basically 70% of the geometry in the image isn't visible and even more of the geometry is useless and you could just replace the 2 lines with a thicker line.

See this part for example:

![image](https://github.com/matrix-org/matrix.org/assets/16312324/68993834-803b-4838-b81e-b3fcc1c5dcb1)

There are about 5 such layers to the image.

**Comment by thibaultamartin** [comment]
Fixed for the desktop one, leaving open for the mobile one. Figma doesn't have an obvious way to make it happen. @deepbluev7 can I bribe you into giving the same treatment to the mobile image 😇  ?

**Comment by deepbluev7** [comment]
![hero_dancing_lines_mobile_no_dupes_exp](https://github.com/matrix-org/matrix.org/assets/16312324/ed4c57bc-ac09-4a06-b2ca-bc34c8b77e41)

Here is a somewhat optimized version of the hero image for mobile. Basically the steps that I did there:

- Merge the duplicate paths into 1:
  - The image is basically composed from 2 paths, the left and the right half.
  - These paths however are duplicated and both inserted with an alpha of 0.3.
  - I just deleted one of them and set the alpha of the other to 0.6. That isn't quite correct, however the visual difference is very hard to spot for me and it halfs the file size pretty much
- Then I deleted the invisible half of the image.
  - The whole image is clipped multiple times and has a gradient, which makes more than half of the points not visible. In the image in my previous comment you can see all the points that compose one of the paths. As you can see, most of those are outside of the clip rectangle. So I just deleted them.
-  Then I exported them from Inkscape as an optimized SVG. I set the accuracy to 4 digits, deleted and shortened all ids as well as removed comments, etc. That didn't save that much, but still decreases filesize by a almost a third.

Result is a 10x reduction in filesize for the mobile image. I think I missed some things in the desktop image and it could be shrunk a bit more as well :)

**Comment by thibaultamartin** [comment]
Many thanks @deepbluev7! That will probably do for starters, happy to revisit it later if the desktop version needs further shrinking :)
