### ISSUE TITLE
Some sections have quite a lot of padding and I am not sure if that is intentional

### ISSUE THREAD

**Issue by deepbluev7** [matrix-org/matrix.org#1720]
Take this for example:

<img width="1680" alt="grafik" src="https://user-images.githubusercontent.com/16312324/235091992-b8f07c64-83b8-4ab6-b103-e52ab0271cf0.png">

It has 250 pixels padding above the content and 435 below it. Which makes it bigger than the view height and there is very little content below it. Possibly the section should either be view-height without the nav-bar height, there should be some content there, the content centered or just less padding.

**Comment by thibaultamartin** [comment]
Thanks for reporting! It would probably make sense for this screen to fit in a full screen browser… which is not the case right now. The issue seems to be less prominent on mobile.

I'll play with padding and media queries to try to make it more compact.

**Comment by thibaultamartin** [comment]
How does it look now on the preview at https://matrix.turbo.fish?

**Comment by deepbluev7** [comment]
Yep, looks much better. It still has quite a bit of padding, but it isn't so weirdly off center anymore!
