### ISSUE TITLE
Split the spec website from the matrix.org website

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/matrix.org#1725]
As reported by @anoadragon453 internally

> Old versions of the spec (that are still linked all over the place, such as https://matrix.org/docs/spec/client_server/r0.4.0) still live on [matrix.org](http://matrix.org/). They currently live as rendered html/css/js in the old [matrix.org](http://matrix.org/) repo, i.e. https://github.com/matrix-org/matrix.org/tree/master/unstyled_docs/spec/client_server
> 
> We should move them to the matrix-org/matrix-spec repo, and then probably redirect https://matrix.org/docs/spec/client_server/r0.4.0 to https://spec.matrix.org/r0.4.0/client-server-api to match the new spec URLs.

**Comment by richvdh** [comment]
> We should move them to the matrix-org/matrix-spec repo, and then probably redirect https://matrix.org/docs/spec/client_server/r0.4.0 to https://spec.matrix.org/r0.4.0/client-server-api to match the new spec URLs.

I'm not *entirely* convinced that matrix-spec is the best place for snapshots of old spec versions - they will clutter up the repo structure. Maybe a separate repo?

**Comment by richvdh** [comment]
The historical spec pages have now been moved over, with 302s from the old site, so it should be safe to cull all that stuff from this repository.

Rapidoc is really a separate thing, so I'm going to consider this done.

**Comment by clokep** [comment]
> I'm not entirely convinced that matrix-spec is the best place for snapshots of old spec versions - they will clutter up the repo structure. Maybe a separate repo?

Can they be zips uploaded to matrix-spec as releases?

**Comment by richvdh** [comment]
> we also need to do something with the rapidoc deployment, currently hosted at https://matrix.org/docs/api

cf #1764
