### ISSUE TITLE
[zola] RSS feed for blog is broken due to old broken posts

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/matrix.org#1736]
https://matrix.turbo.fish/atom.xml is broken due to broken posts. Need to check which ones those were but iirc some in the tech category were broken.

**Comment by thibaultamartin** [comment]
Depends on #1520

**Comment by thibaultamartin** [comment]
Can you give it a go? I think I found the culprit and it's fixed, but different clients can be sensitive to different things

**Comment by thibaultamartin** [comment]
Closing, please reopen if it didn't fix the issue

**Comment by MTRNord** [comment]
Didnt get to it fast enough. Firefox seems happy now :) So I consider it fixed as well
