### ISSUE TITLE
Broken layout around the Element Call GIF

### ISSUE THREAD

**Issue by robintown** [matrix-org/matrix.org#1739]
At a viewport size of 1130px, the area around the Element Call GIF on the homepage looks like this:

![Screenshot 2023-04-28 at 09-51-47 Matrix org](https://user-images.githubusercontent.com/48614497/235169015-4e60334a-d7e6-42b3-8b44-f240c8f33478.png)

**Comment by thibaultamartin** [comment]
Fixed in #1780, will be deployed on https://matrix.turbo.fish in a few minutes
