### ISSUE TITLE
No padding around content on the documentation page

### ISSUE THREAD

**Issue by robintown** [matrix-org/matrix.org#1740]
At a viewport size of 1130px, the main content area on the documentation page has no padding, which looks broken:

![Screenshot 2023-04-28 at 09-56-37 Matrix org - Getting Started](https://user-images.githubusercontent.com/48614497/235169174-72236a5c-b382-4ab2-a204-836a7560884d.png)

**Comment by thibaultamartin** [comment]
Fixed on `zola`, the preview will be deployed in a few minutes
