### ISSUE TITLE
Make sure legal documents are up to date, date removed from footer replaced by link to copyright notice

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/matrix.org#1743]

**Comment by deniseal** [comment]
Related to this issue, there are some formatting issues in the Copyright notice: 
![Screenshot 2023-05-09 at 07 24 25](https://user-images.githubusercontent.com/51328716/237011655-c8d63026-ac3b-4c41-9f85-a3327aca2fd0.png)

@thibaultamartin do you want me to just open PRs on the legal docs?

**Comment by thibaultamartin** [comment]
Yes please, and can you prod me when they're updated so I can refresh it?
