### ISSUE TITLE
Replace Element Call GIF with an equivalent WEBM (or similar format)

### ISSUE THREAD

**Issue by LorenDB** [matrix-org/matrix.org#1746]
In my experience, GIF as a format tends to have larger file sizes and lower quality. In this case, the GIF is 22+ MB and has noticable compression artifacts (or something; you can see it, but I have no idea what the proper term for it is in this case). I'm guessing that a WEBM would give you much better image quality with a reduced filesize.

**Comment by thibaultamartin** [comment]
Absolutely, the gif was stolen from a blog post and is still placeholder-ish at this point. It's way too low quality to be acceptable on a front page.

Thanks for opening an issue to keep track of it!

**Comment by koyuawsmbrtn** [comment]
Yes, I am also for this change. My first regression was the dithering on the call GIF. That didn't look professional.
