### ISSUE TITLE
Beta matrix.org embedded videos are very small

### ISSUE THREAD

**Issue by ifeeltiredboss** [matrix-org/matrix.org#1748]
Steps to reproduce:
1. Go to https://matrix.turbo.fish/blog/

Additional info:
Chrome 112 on MacOS Apple Silicon
<img width="897" alt="image" src="https://user-images.githubusercontent.com/111905360/235237922-700be8a2-492c-4f23-ac02-ac998348183e.png">

**Comment by MTRNord** [comment]
Hm thats a regression. I think the css that made them responsive got lost :/

**Comment by thibaultamartin** [comment]
Fixed by #1752
