### ISSUE TITLE
[new matrix.org] Syphon does have multiaccount support

### ISSUE THREAD

**Issue by 0x1a8510f2** [matrix-org/matrix.org#1750]
[As of 2 years ago actually!](https://github.com/syphon-org/syphon/pull/303)

![Screenshot_20230428-204933~2](https://user-images.githubusercontent.com/83190128/235240069-7dc6e346-1c85-4d34-a19d-5ae3aa02bf79.png)

**Comment by thibaultamartin** [comment]
Thanks for checking this, will fix!

**Comment by thibaultamartin** [comment]
Fixed, will be deployed on the preview in a few minutes

**Comment by 0x1a8510f2** [comment]
Thanks!
