### ISSUE TITLE
Enable GitHub Discussion.

### ISSUE THREAD

**Issue by rokejulianlockhart** [matrix-org/matrix.org#1773]
My rationale is available at https://github.com/8go/matrix-commander/issues/68#issue-1237645245.

**Comment by MTRNord** [comment]
I feel like your rationale doesn't apply. With little effort you could have seen the link to the matrix room from the readme. It's directly at the start of the readme.
 https://matrix.to/#/#matrix.org-website:matrix.org

**Comment by MTRNord** [comment]
> @MTRNord, https://matrix.to/#/#matrix.org-website:matrix.org isn't a forum, though. If you had a Discourse instance, I'd understand, but chatrooms are very different, even with threading enabled.

Yes it is not a forum. However in your linked message you wanted a communication channel that is not issues and doesn't require triaging. This would be the chat room. It's the best way to communicate quickly and efficiently with others working on the website. It wasn't clear that you want a forum. However I still think that the room is the correct venue for this project.

**Comment by strypey** [comment]
@MTRNord 
> However in your linked message you wanted a communication channel that is not issues and doesn't require triaging. This would be the chat room

A forum-like view of a chat room does not and cannot serve the same purpose as a static forum, for [reasons given in another thread requesting a forum](https://github.com/matrix-org/matrix.org/issues/43#issuecomment-1763539294). The fact that requests for a matrix community forum keep getting made, by different people, in different forms, suggests there is a need, and people who would be willing to do the minimal admin and mod work for an official forum on HitGub or on an instance of Lemmy/ KBin.
