### ISSUE TITLE
Outdated copyright in the footer

### ISSUE THREAD

**Issue by ifeeltiredboss** [matrix-org/matrix.org#1776]
1. Go to https://matrix.turbo.fish/
2. Scroll down to the footer
3. Outdated copyright
<img width="300" alt="image" src="https://user-images.githubusercontent.com/111905360/236406149-0c98fe8f-324b-44c6-b0c3-257a906c90ff.png">

**Comment by MTRNord** [comment]
This is somewhat a duplicate of #1743

**Comment by thibaultamartin** [comment]
Closing as duplicate of #1743
