### ISSUE TITLE
Links in headers are impossible to distinguish

### ISSUE THREAD

**Issue by JacksonChen666** [matrix-org/matrix.org#1782]
https://matrix.turbo.fish/blog/2023/05/05/this-week-in-matrix-2023-05-05/#dept-of-ops

There's currently ABSOLUTELY no indication that the text "website" is a link (except for well, the text. but that doesn't help)

![Link in header, the website link looks like text](https://user-images.githubusercontent.com/50755746/236617357-a96f392f-9da6-468f-8c40-492fa2dd06b9.png)

![Link in header is hovered over, there's underlining of the link.](https://user-images.githubusercontent.com/50755746/236617375-b3fcef88-98f7-4d93-8200-1ca6adc0534c.png)

**Comment by thibaultamartin** [comment]
Good catch, thanks for the issue. This is already tracked in #1529
