### ISSUE TITLE
Add threads to the client matrix

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix.org#1783]
I'm not sure what exactly happened, because while [this issue](https://github.com/matrix-org/matrix.org/issues/1767) talks about Cinny not having thread support, on the [actual client matrix](https://matrix.org/clients-matrix), I can't find descriptions for thread support.

I recently started using Threads more actively, and was disappointed by the lack of support across the board, but I was more surprised by the fact that Threads is not on the official feature matrix, was this deliberately removed? If so, why?

**Comment by thibaultamartin** [comment]
The issue links to the new matrix.org website, which is where I fixed it :)

https://matrix.turbo.fish/ecosystem/clients/cinny/ should display it accurately

**Comment by ShadowJonathan** [comment]
Ah, never mind, on the [new site](https://matrix.turbo.fish/ecosystem/clients/) i'm seeing that this has moved to a dropdown with checkmarks, i think this is a bit not discoverable, but it is there, i see

**Comment by ShadowJonathan** [comment]
Ah, we seem to have replied at the same time :)
