### ISSUE TITLE
Ship an open font for consistent look across platform

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/matrix.org#1786]
Helvetica Neue is the font usually used by the Matrix brand, but we can't distribute it freely.

Looking at [this comparison](https://www.learnui.design/blog/helvetica-similar-fonts.html), it looks like [Nimbus Sans](https://www.fontsquirrel.com/fonts/nimbus-sans-l) could be a good replacement.

Not sure it's worth blocking the release on it though?

**Comment by thibaultamartin** [comment]
| Helvetica Neue | Nimbus Sans  |
|----------------|---------------|
| ![image](https://github.com/matrix-org/matrix.org/assets/1688309/ecbb0484-d742-44a4-a2d2-7c3d0f096def) |  ![image](https://github.com/matrix-org/matrix.org/assets/1688309/ffc993a0-0028-4827-9795-93abeb9003e1) |
| ![image](https://github.com/matrix-org/matrix.org/assets/1688309/f86666dd-45a8-4b8a-9ea5-e57748e250c0) |  ![image](https://github.com/matrix-org/matrix.org/assets/1688309/9a7f9eab-101a-4c1b-b72d-9fd3906bffe4) |
| ![image](https://github.com/matrix-org/matrix.org/assets/1688309/ee7db3fa-a6e3-4ed1-9972-c2dcdc355e90) | ![image](https://github.com/matrix-org/matrix.org/assets/1688309/4cb48625-f912-4415-9865-89035d8c9a36) |

Looks good enough?

**Comment by MTRNord** [comment]
Hm is it just me or is the free one slightly smaller?
