### ISSUE TITLE
FAQ recommends unmaintained XMPP bridges missing Bifrøst entirely

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix.org#1817]
> Meanwhile, rather than competing, an XMPP Bridge like [Skaverat's xmpptrix beta](https://github.com/SkaveRat/xmpptrix) or [jfred's matrix-xmpp-bridge](https://github.com/jfrederickson/matrix-xmpp-bridge) or Matrix.org's own [purple-matrix](https://github.com/matrix-org/purple-matrix/) has potential to let both environments coexist and make the most of each other's benefits.

- https://github.com/SkaveRat/xmpptrix latest commit is 1st of August 2015
- https://github.com/jfrederickson/matrix-xmpp-bridge _This repository has been archived by the owner on Jun 3, 2019. It is now read-only._
- https://github.com/matrix-org/purple-matrix/ _This project is essentially unmaintained. It may still work for you, in which case good luck to you; however, it lacks many important features that are critical to a modern Matrix client (not least of which is https://github.com/matrix-org/purple-matrix/issues/18)._

---

As far as I know of [matrix-bifrost](https://github.com/matrix-org/matrix-bifrost) is the least unmaintained XMPP bridge, while I have an impression that it's not considered a priority for Element's business strategies and thus it's developers are often assigned to different projects such as the IRC bridge.

**Comment by thibaultamartin** [comment]
Hej Mikaela, thanks for helping us tidying up the website. The FAQ is indeed in a very dire state and has been for a while. This is why I want to get rid of the FAQ entirely in the new version of the website: you can see a preview at https://matrix.turbo.fish

As you can see in https://matrix.turbo.fish/ecosystem/bridges/xmpp/, I didn't port the obsolete projects to the XMPP bridges section so it's not misleading for people looking for a bridge. I'm going full steam on the new website to get it to replace our current crufty matrix.org as soon as possible, so I'm not spending too much time fixing the current website :)

**Comment by Mikaela** [comment]
Could there be a warning at the FAQ about it going away?
