### ISSUE TITLE
Homepage hero misaligned

### ISSUE THREAD

**Issue by nadonomy** [matrix-org/matrix.org#1836]
<img width="1912" alt="Screenshot 2023-06-16 at 09 39 55" src="https://github.com/matrix-org/matrix.org/assets/4626865/474817e8-f570-42aa-85d3-438946d50ab3">

The main hero content is vertically misaligned. It should be offset higher to be aligned optically.

**Comment by nadonomy** [comment]
I'd align it vertically within the black area (i.e. treating where the white starts as the bottom bound).

**Comment by ara4n** [comment]
+1e100
