### ISSUE TITLE
Additional feed redirect may be needed

### ISSUE THREAD

**Issue by jryans** [matrix-org/matrix.org#1849]
For some reason, my feed reader was aimed at `https://matrix.org/blog/feed/`, which is now a 404... Seems like `https://matrix.org/blog/feed` (without slash) was the intended value, since that now redirects to the new feed. In any case, maybe both forms should be redirected if possible.

**Comment by clokep** [comment]
I seem to also have the trailing slash in my RSS reader FWIW...

**Comment by thibaultamartin** [comment]
The redirect was added, please let me know if that's still an issue :)
