### ISSUE TITLE
Non-flatpak clients don't have Linux label in client list

### ISSUE THREAD

**Issue by tulir** [matrix-org/matrix.org#1852]
like gomuks, iamb, kazv https://matrix.org/ecosystem/clients/

![image](https://github.com/matrix-org/matrix.org/assets/4224639/5454b2d1-e8ba-4821-a159-1200bfa8a4c5)

**Comment by bertvandepoel** [comment]
Oh wow, this explains a lot. Seems like a small accident with pretty big effects. And here's me thinking I barely had any options for Linux desktop clients. Thanks for pointing this out and I hope it gets solved really soon!
