### ISSUE TITLE
jira archive went missing

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix.org#1878]
eg: https://matrix.org/jira/browse/SPEC-432

We used to have a static archive of this for historical context and links (matrix used jira before it used github)

**Comment by richvdh** [comment]
I think it just lived in a local directory on the old `matrix.org` web server. We could do with another home for it.

**Comment by thibaultamartin** [comment]
@laurencegill did you see anything about about this in the apache? Do you know where this jira archive lived, and can we get it back to life?

**Comment by thibaultamartin** [comment]
@laurencegill I'm being told the Jira static archive lived in `horme:/home/matrixsite/overlay/jira`

**Comment by laurencegill** [comment]
@thibaultamartin yes they still exist on `horme` as I haven't cleaned up yet :broom: 

What do you want to do with them? If they are OK to publicly visible we can probably add them to the repo?
