### ISSUE TITLE
FAQ page has bad layout on mobile as it doesn't reflow

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix.org#189]
> From https://matrix.org/jira/browse/ORG-45

Source: https://github.com/matrix-org/matrix-doc/issues/843

**Comment by benparsons** [comment]
@turt2live is this something you've seen, or are you moving it from matrix-doc? I can't repro on Chrome Android.

**Comment by turt2live** [comment]
Just moving it. Having tested it myself, it does appear fixed. Apologies for the noise.
