### ISSUE TITLE
RSS/Atom feed no longer works with The Old Reader

### ISSUE THREAD

**Issue by andrewshadura** [matrix-org/matrix.org#1897]
Hi,

The new Atom feed (https://matrix.org/atom.xml) is being returned without a content type set. Some RSS readers fail to recognise it.
```
< HTTP/2 200 
< date: Tue, 27 Jun 2023 10:18:01 GMT
< content-type: application/xml
< cache-control: public, max-age=0, must-revalidate
< etag: W/"f0bc5313c81bd619ed28216f5d418546"
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< referrer-policy: strict-origin-when-cross-origin
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=3kDHK6akNTIOxiLl5YGEza0ex%2FXuWqgnIMQnFT%2F0pTwl3FcbTMTdXJ9WJrJgUHazkN7xH9jConr0jVIxs%2FLeaHTv4TW36v7o06Noq06jL%2Bw43SUUgRsW%2FFpMbDUNMXZLxkP%2FzdGHvcl1y%2F2yLGlFOpgXHKzPPNE%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< vary: Accept-Encoding
< permissions-policy: interest-cohort=()
< cf-cache-status: DYNAMIC
< server: cloudflare
< cf-ray: 7ddcf1902fffb330-PRG
```

**Comment by laurencegill** [comment]
> < content-type: application/xml

@andrewshadura doesn't this mean that the `content-type` was returned? I'm assuming this is `curl` output?

Apologies if I am mistaken, but I cannot reproduce it with `curl` either:

```
<= Recv header, 37 bytes (0x25)
0000: date: Tue, 27 Jun 2023 11:54:13 GMT
<= Recv header, 31 bytes (0x1f)
0000: content-type: application/xml
```

Could you give me an example of an RSS reader that doesn't work?

**Comment by andrewshadura** [comment]
Indeed, I missed the header. Nevertheless, my reader still fails to recognise it.

**Comment by laurencegill** [comment]
https://matrix.org/category/security/atom.xml works in the reader above, but https://matrix.org/atom.xml does not.

I'm not sure how these are generated, @thibaultamartin any ideas?

**Comment by MTRNord** [comment]
> I'm not sure how these are generated, @thibaultamartin any ideas?

Currently zola generates those "automatically" using this template https://github.com/getzola/zola/blob/8dd1b30594dcfa5344ba36b6b057a5b0aa9bd277/components/templates/src/builtins/atom.xml

Some (but not much) info is also at https://www.getzola.org/documentation/templates/feeds/

If you are interested in how it works there is https://github.com/getzola/zola/blob/8dd1b30594dcfa5344ba36b6b057a5b0aa9bd277/components/site/src/feed.rs#L30-L90 which seems to render it.

**Comment by MTRNord** [comment]
I do wonder if this is maybe due to #1848 since the section one will have a title while the global one currently has no title.

**Comment by thibaultamartin** [comment]
I merged a fix for #1848

**Comment by andrewshadura** [comment]
Not sure if the feed’s been updated, but it still doesn’t work.

**Comment by MTRNord** [comment]
It seems like the service says explicitly when the url is invalid. I also noticed https://matrix.org/category/this-week-in-matrix/atom.xml is not accepted with the same error. Possibly its a content issue instead? (As in there is some post breaking the parser of that page)

**Comment by MTRNord** [comment]
I wrote an email to the support asking if they can help with further logging on this to help debugging the issue.

**Comment by thibaultamartin** [comment]
@andrewshadura are you still facing the issue? The feed now only returns the 15 last entries. It previously returned the whole history of articles, which made some RSS reader blow up

**Comment by laurencegill** [comment]
@thibaultamartin FTR this works for me using the old reader now

**Comment by thibaultamartin** [comment]
Closing as fixed given the feedback, feel free to reopen in case the issue remains

**Comment by andrewshadura** [comment]
```xml
<entry xml:lang="en">
    <title>The future of Synapse and Dendrite</title>
    <published>2023-11-06T00:00:00+00:00</published>
    <updated>2023-11-06T00:00:00+00:00</updated>
    <author>
    <name>Unknown</name>
    </author>
    <link rel="alternate" href="https://matrix.org/blog/2023/11/06/future-of-synapse-dendrite/" type="text/html"/>
    <id>
        https://matrix.org/blog/2023/11/06/future-of-synapse-dendrite/
    </id>
…
```

**Comment by MTRNord** [comment]
> ```
> <entry xml:lang="en">
>     <title>The future of Synapse and Dendrite</title>
>     <published>2023-11-06T00:00:00+00:00</published>
>     <updated>2023-11-06T00:00:00+00:00</updated>
>     <author>
>         <name>Unknown</name>
>     </author>
>     <link rel="alternate" href="https://matrix.org/blog/2023/11/06/future-of-synapse-dendrite/" type="text/html"/>
>     <id>https://matrix.org/blog/2023/11/06/future-of-synapse-dendrite/</id>
> …
> ```

For clarity opened a dedicated issue for that so it doesnt get lost :)
