### ISSUE TITLE
Less confusing legacy notice

### ISSUE THREAD

**Issue by solarkraft** [matrix-org/matrix.org#1916]
The current notice for legacy documentation (https://github.com/matrix-org/matrix.org/blob/2dd22ddc929c0f86cacbfad75e8bc298ef42e055/templates/docs/legacy.html#L6-L11) is very alarming and potentially confusing. 

[The JS SDK guide](https://matrix.org/docs/legacy/usage-of-the-matrix-js-sdk/) in particular (but seemingly others too) seem to largely still apply and, more importantly, have no replacements in the current documentation.

Maybe it would make sense to make the disclaimer look less alarming (yellow instead of red) and the wording less prescriptive ("use with caution" rather than "don't use this"). 

This also applies to [the legacy documentation page on the new site](https://matrix.org/docs/legacy/), for which I can't find the source right now.

**Comment by solarkraft** [comment]
Wording suggestion:

Legacy documentation
This article is not actively maintained anymore, so it may be outdated. There may be more current information in the new documentation section.

**Comment by thibaultamartin** [comment]
That's a good call, thanks for the suggestion and thanks for helping us improving the website :)
