### ISSUE TITLE
RSS feed broken for Inoreader

### ISSUE THREAD

**Issue by clokep** [matrix-org/matrix.org#1937]
I mentioned this to @thibaultamartin yesterday, but filing an issue for tracking. It seems adding the last couple of blog posts broke the RSS feed for Inoreader, the first missing blog post is https://matrix.org/blog/2023/07/make-sure-libera-bridge-keeps-working/. So it seems something changed between July 4 and July 7 (or the July 7th post broke it).

The error I see is:

![image](https://github.com/matrix-org/matrix.org/assets/517124/b9294b01-aacd-47c8-9ad4-a95a9b5a3c54)

I suspect limiting the size of the feed would fix this issue.

**Comment by thibaultamartin** [comment]
Likely related to https://github.com/matrix-org/matrix.org/issues/1918

**Comment by clokep** [comment]
I have a suspicion that #1903 broke this, it was merged on July 5th so fits the time window.

**Comment by thibaultamartin** [comment]
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2F0a9f81c0.matrix-website.pages.dev%2F seems to consider the feed valid, but it looks like inoreader is still not happy with it.

It might be because of the iframe… which we might have to get rid of anyway according to #2000

**Comment by yajo** [comment]
For feedly it's working again, thanks.

**Comment by clokep** [comment]
Looks like this is now working again!

**Comment by thibaultamartin** [comment]
FWIW there are duplicate feeds in Inoreader and some of them are not up to date. I reached out to get the issue fixed :)
