### ISSUE TITLE
status.matrix.org missed outage caused by invalid SSL certificate on server

### ISSUE THREAD

**Issue by alphapapa** [matrix-org/matrix.org#1938]
Please see: https://github.com/vector-im/element-web/issues/25798.  

https://status.matrix.org/ shows "All Systems Operational" with only green bars.  The outage is/was for the entire matrix.org homeserver, so it seems like the status tracker should have caught it.

**Comment by SolninjaA** [comment]
I have also gone to https://status.matrix.org, and I can confirm that it has green bars but Element is still not working for me (invalid SSL certificate, 404 error). See: https://github.com/vector-im/element-web/issues/25798

**Comment by alphapapa** [comment]
@SolninjaA What is your location?  Maybe consider posting a traceroute to matrix-client.matrix.org.

**Comment by SolninjaA** [comment]
> I have also gone to https://status.matrix.org, and I can confirm that it has green bars but Element is still not working for me (invalid SSL certificate, 404 error). See: [vector-im/element-web#25798](https://github.com/vector-im/element-web/issues/25798)

As of now it appears that everything is working for me.

**Comment by thibaultamartin** [comment]
Thanks for the report, we're going to add the incident retrospectively. The SRE team is also updating its incident response playbook to make sure the page gets updated when there's such an outage
