### ISSUE TITLE
Newest TWIM has weird image alignment in element android X post

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/matrix.org#1940]
![image](https://github.com/matrix-org/matrix.org/assets/1374914/32aaa594-b202-46e5-abdd-0b4ec3f49018)

**Comment by thibaultamartin** [comment]
Is this still the case? I can't reproduce on https://matrix.org/blog/2023/07/twim/

![image](https://github.com/matrix-org/matrix.org/assets/1688309/4f0c5900-6b65-4f50-bfaf-73b3c1fec02e)

**Comment by MTRNord** [comment]
seems to be fine by now
