### ISSUE TITLE
Blog category URLs changed

### ISSUE THREAD

**Issue by clokep** [matrix-org/matrix.org#1955]
See matrix-org/synapse#16005, it seems that the blog categories used to be available at things like https://matrix.org/blog/category/releases, but are now at https://matrix.org/category/releases (note the missing `/blog`).

**Comment by thibaultamartin** [comment]
Relevant context in the advocacy internal channel: https://matrix.to/#/!wIPEfqhDsTwAzqFGvi:matrix.org/$AZoQ49bhS3ud0j0ToTdRnKWHQ1tY_xBdwd5erqOf7ZQ?via=matrix.org&via=element.io&via=t2l.io

**Comment by clokep** [comment]
Thanks for fixing this so fast. 👍
