### ISSUE TITLE
Consider ReDoc as a swagger viewer

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix.org#197]
I ran across this thanks to the new github dashboard. It's pretty, and advertises mobile support (#192). No other investigation done though.

https://github.com/Rebilly/ReDoc

**Comment by turt2live** [comment]
It's not too bad with the current JSON: https://redoc.matrix.c2s.temp.t2host.io

**Comment by afranke** [comment]
We went with Rapidoc (see #1081).
