### ISSUE TITLE
Update thunderbird.svg

### ISSUE THREAD

**Issue by Commandcracker** [matrix-org/matrix.org#1979]
[current logo](https://github.com/matrix-org/matrix.org/blob/main/content/ecosystem/clients/thunderbird.svg)
new thunderbird log: https://github.com/thundernest/thunderbird-website/blob/master/media/svg/logo.svg

**Comment by NmN03jain** [comment]
![Screenshot (28)](https://github.com/AlaSQL/alasql/assets/90062260/abd103d9-2b70-473a-925e-a9b1bc881c93)

**Comment by mohit1523** [comment]
Sir, I can resolve this issue.
