### ISSUE TITLE
Hash/fragment not kept when redirecting

### ISSUE THREAD

**Issue by gabrc52** [matrix-org/matrix.org#1980]
https://matrix.org/faq/#what-is-a-homeserver%3F redirects to https://matrix.org/docs/legacy/faq/ and the #what-is-a-homeserver part is dropped.

Example: 

1. go to https://app.element.io
2. click on "Sign in"
3. click on "edit" for the homserver
4. Click on "about homeservers"
5. You get redirected to old documentation but the # is dropped

Related: https://github.com/vector-im/element-web/issues/25931

**Comment by thibaultamartin** [comment]
@laurencegill anything we can do about it to your knowledge?

**Comment by laurencegill** [comment]
@thibaultamartin yes we can probably add a rule to cater for this and keep that part of the request.

Although, it does look like the app has been updated to go instead to:

https://matrix.org/docs/matrix-concepts/elements-of-matrix/#homeserver 

Also https://github.com/vector-im/element-web/issues/25931 is closed so maybe nothing to do here?

**Comment by thibaultamartin** [comment]
Indeed, let's close it. Thanks Laurence!
