### ISSUE TITLE
matrix.org's css for the spec removes margin on numbered lists

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix.org#200]
Expected:
![image](https://user-images.githubusercontent.com/1190097/43600438-d2f8bcaa-9647-11e8-9450-4842a1a86948.png)

Actual:
![image](https://user-images.githubusercontent.com/1190097/43600424-c5ab6de0-9647-11e8-88e8-1c4626b99bf1.png)

**Comment by richvdh** [comment]
See also https://github.com/matrix-org/matrix.org/issues/22.

**Comment by benparsons** [comment]
Fixed.
