### ISSUE TITLE
Add "Out of your Element" Discord bridge

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix.org#2026]
I came across this today, a Matrix<->Discord bridge: https://gitdab.com/cadence/out-of-your-element.

We should add it to https://matrix.org/ecosystem/bridges/discord/.

**Comment by cloudrac3r** [comment]
This is my bridge! I'd be glad to go on the matrix ecosystem web page. Here's some more details:

- Name: Out Of Your Element
- Access needed to set up a new copy: "Manage Server" permission in Discord, and Matrix homeserver admin
- Licence: AGPL 3.0 or later
- Space: #out-of-your-element:cadence.moe
