### ISSUE TITLE
Update the sponsors/foundation members

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/matrix.org#2036]
Per https://matrix.org/membership/

Silver should have a logo on the sponsors page
Gold should have a bigger logo on the sponsors page
Platinum should have a logo on the frontpage

**Comment by joshsimmons** [comment]
One logo: ![beeper](https://github.com/matrix-org/matrix.org/assets/200770/3e507bee-bbb7-4ecf-9573-2cafef1c26dd)

Looking into getting gematik's.
