### ISSUE TITLE
Add a license... again

### ISSUE THREAD

**Issue by JacksonChen666** [matrix-org/matrix.org#2043]
The license is gone again. *Insert "no license" template here*

[Last time](https://github.com/matrix-org/matrix.org/issues/1449), it was implemented, but then I guess the rewrite just threw it away (by accident).

**Comment by thibaultamartin** [comment]
I'm not convinced Apache 2.0 was the best licence choice here, let me loop in the legal team. I think a CC commons licence would make more sense, but I want to make sure we're not throwing away our trademark policy efforts by accident (the point of the trademark policy being to avoid seeing deceptive usage of the matrix logo and name)

**Comment by thibaultamartin** [comment]
We're likely going to use two different licences:

- Apache 2.0 for the website code
- A Creative Commons licence for the content (docs, blog posts, etc)

The legal team is checking to make sure we're not shooting ourselves in the foot, and we should be able to deploy that in the next few weeks :)
