### ISSUE TITLE
[Bug] Matrix Bridge for GroupMe links to the wrong repository

### ISSUE THREAD

**Issue by ekirchman** [matrix-org/matrix.org#2064]
The link on [this Matrix bridge](https://matrix.org/ecosystem/bridges/groupme/) for GroupMe links to the [kakaotalk](https://src.miscworks.net/fair/matrix-appservice-kakaotalk.git) Matrix bridge, not the GroupMe one. This link should either be updated to the upstream version of the correct GroupMe bridge, or this webpage should be removed if the upstream bridge no longer works.

**Comment by thibaultamartin** [comment]
Thanks for catching it, will fix shortly!

**Comment by ekirchman** [comment]
Is this the right repo? The one you included in your commit says that this is an archived project.

**Comment by thibaultamartin** [comment]
Arh you're right, the data is right but the project has been archived since. I need to remove the groupme bridge section

**Comment by ekirchman** [comment]
Darn it. :( I was hoping that there was an active fork somewhere that someone knew of. But thanks for helping sort this out
