### ISSUE TITLE
what about the perspectives.servers parameter. Is it needed??

### ISSUE THREAD

**Issue by Unsourire** [matrix-org/matrix.org#207]
Hello,
i finish to configurate my own HS and install my own IS (mxisd).
everything is working well.

After making a lot of changing and configuration I have a last question regarding the perspectives.servers: parameter on the synapse configuration file.

Do I really need to setup this parameter? what do exacly this parameter?

Thanks in advance for your help

**Comment by Half-Shot** [comment]
I don't know how this hasn't been redirected yet, but this is a question for https://github.com/matrix-org/synapse
