### ISSUE TITLE
Incorrect UpCloud mention in the home page

### ISSUE THREAD

**Issue by omame** [matrix-org/matrix.org#2078]
On the main page, towards the bottom, I can see this:

![image](https://github.com/matrix-org/matrix.org/assets/1301328/f5b22db7-9d23-4e8d-9994-8af41096cd3d)

To the best of my knowledge, I haven't seen any free hosting nor credits from UpCloud in the almost two years I've been approving their bills. I'm not sure how it used to be in the past, but I can certainly tell that we pay for our usage just like every other customers of theirs.

Besides, most of the matrix.org infrastructure is hosted on Mythic Beasts.

Can we review that part?

**Comment by MTRNord** [comment]
This seems to have been removed fully by now
