### ISSUE TITLE
Broken link in SDK page.

### ISSUE THREAD

**Issue by mjgarton** [matrix-org/matrix.org#2079]
The page at https://matrix.org/ecosystem/sdks/ says "If you are a developer and are not sure what the difference between clients and appservices, please head to [the developers documentation](https://matrix.org/docs/developers/). " but that link is broken leading to 404.

**Comment by SjxSubham** [comment]
I have tried to Solve that issue PR #2080

**Comment by SjxSubham** [comment]
@mjgarton , 
It's fixed now so U can close this issue
