### ISSUE TITLE
Add a feed button/icon to make it obvious a feed exists for one or several pages/categories

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix.org#2107]
Sites offering feeds should take care to announce them so people notice and actually subscribe :) since browsers rarely point it out anymore...

**Comment by thibaultamartin** [comment]
Yep, great idea! I believe a RSS icon in the footer would be a good starting point

**Comment by tawandamoyo** [comment]
Hi @thibaultamartin , I'd like to work on this
