### ISSUE TITLE
Issue with presentation on the "Elements of Matrix" page

### ISSUE THREAD

**Issue by mpeter50** [matrix-org/matrix.org#2134]
The following paragraph is shown at the end of multiple slides, until the 7th where it actually should be.

> Bob sends a response to Alice's message, and his server adds his message into his copy of the room's history, linking it to the most recent unlinked object in the graph - Alice's last message.

After that slide it is not shown anymore. Even when the start over button is clicked at the end, the first slide now only has the text that was actually written for that slide.
Until you notice this, it makes the presentation quite confusing.

A few screenshots to make it clear what is the problem:
|First slide|Second slide|First slide after starting over|
|-|-|-|
|![image](https://github.com/matrix-org/matrix.org/assets/83356418/dd5c40aa-3881-4904-85a8-ff706e7c4b89)|![image](https://github.com/matrix-org/matrix.org/assets/83356418/917e08e1-2a95-413d-833c-d9517e1a8462)|![image](https://github.com/matrix-org/matrix.org/assets/83356418/5ad8f82f-6d3e-45a9-9c93-0a1c296f62e2)|

**Comment by tawandamoyo** [comment]
It appears there is a missing class name of `hidden` on that slide. I would like to submit a PR for this.
