### ISSUE TITLE
Add new sponsors from FOSDEM's logos

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix.org#2168]

**Comment by thibaultamartin** [comment]
<img width="883" alt="Screenshot 2024-02-07 at 09 56 09" src="https://github.com/matrix-org/matrix.org/assets/1688309/86492108-d065-48e5-b688-54e983275f9b">

@joshsimmons those were unveiled during FOSDEM, should I add them to m.org as well?

**Comment by HarHarLinks** [comment]
cryptpad is missing as of right now

**Comment by MTRNord** [comment]
https://matrix.to/#/!kOXQjUbOfdYNCtRmZv:matrix.org/$TQ9_3z6gVSFEsLLqxlSLEeiG0YnC5Jxjlpr7rou0fcA?via=matrix.org&via=element.io&via=envs.net
