### ISSUE TITLE
Bulleted lists don't show up correctly

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix.org#22]
See for example, https://matrix.org/docs/projects/other/sydent.html and https://matrix.org/docs/projects/other/mxisd.html.

The problem here is that the CSS on matrix.org is a complete rat's nest, and for some reason it disables bullets on lists. (It appears we bluntly apply the complete CSS for the [Wordpress Divi builder](https://www.elegantthemes.com/gallery/divi/) to every page, which apart from making me want to weep, also includes `ol, ul { list-style: none; }`.)

I'm not sure I have the mental stamina to rewrite the CSS on matrix.org today.

**Comment by richvdh** [comment]
(for the record, the CSS on these pages comes from https://github.com/matrix-org/matrix.org/blob/master/jekyll/_includes/head.html)

**Comment by richvdh** [comment]
ordered lists are pretty disasterous too: https://matrix.org/docs/spec/server_server/unstable.html#rules

**Comment by jryans** [comment]
Is this issue still valid? It seems like many of the problems mentioned are resolved:

* Bullets appear on https://matrix.org/docs/projects/other/sydent.html
* Bullets appear on https://matrix.org/docs/projects/other/mxisd.html
* Ordered lists at https://matrix.org/docs/spec/server_server/unstable.html#rules seem ordered

**Comment by benparsons** [comment]
Yes, this was fixed by the CSS simplification/re-do of a couple of months ago
