### ISSUE TITLE
Remove https://github.com/kamax-io/mxhsd/

### ISSUE THREAD

**Issue by dax-dev** [matrix-org/matrix.org#221]
The project decided to abandon the Matrix protocol in favor of their own.

See their [README](https://github.com/kamax-io/mxhsd/blob/master/README.md#current-status)

**Comment by benparsons** [comment]
@maxidor to confirm. Max you'd like mxhsd removed from try-matrix-now?

**Comment by maxidor** [comment]
@benparsons Please don't remove it. It is currently still aligned with the latest reverse-engineering and we might still make it compatible with the first S2S spec release if accurate enough.

**Comment by dax-dev** [comment]
Sorry for assuming then -- I was confused because the README seemed to imply that the project was moving away from Matrix.

**Comment by ara4n** [comment]
@dax-dev np - thanks for trying to help. unfortunately the situation there is a mess.
