### ISSUE TITLE
Match flexbox width with flex elements' width

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix.org#2211]
e.g. some weird line breaks due to mismatch of flex container width and combined flex elements' (incl padding, margin, gap, etc) with.
![image](https://github.com/matrix-org/matrix.org/assets/2803622/6b7d39c2-c5a0-479e-881d-66ee185802c6)

this should be able to easily be calculated for the different layouts.
in the screenshot case `--page-max-width: 57rem;` should be split up into 5 silver members per line, so
- `57rem - 2 * padding-inline == 5 * supporters-card + 4 * gap`
- `supporters-card == (57rem - 2 * 1rem - 4 * 1rem) / 5` since padding-inline and gap is 1rem
- `(border-left + padding-left + --logo-width + padding-right + border-right) == 10.2rem`
- `--logo-width := 10.2rem - 18px` with values from `.support.main #supporters .supporters-section .cards .supporters-card`
- or `--logo-width: calc((57rem - 2* 1rem - 4* 1rem) / 5 - 2* 8px - 2* 1px);`

![image](https://github.com/matrix-org/matrix.org/assets/2803622/48509363-5acc-4286-a931-78445ca33f40)
there we go, perfect alignment! for demonstration purposes I duplicated the gold supporter and switched the values with 3 elements (and hence 2 gaps). this could of course just be done nicely using more css variables...!

it isn't entirely perfect anymore when you zoom (especially zoom out), I believe due to the hardcoded pixel values. i don't think it matters much, but they could be replaced by responsive values, too?

the same technique can of course be applied to the other (ecosystem) pages with flexboxes.

ref https://github.com/matrix-org/matrix.org/pull/2165/files#diff-419d8dbf3f2b695b23249510ef4d1bddeac3c4c720faa74a8e2e861c9c67b5f1R80 and #2198

**Comment by MTRNord** [comment]
Related: #2198

**Comment by HarHarLinks** [comment]
> Related: #2198

Hey that's what I said :p
