### ISSUE TITLE
iamb description omits windows, macos support

### ISSUE THREAD

**Issue by jaredhirsch** [matrix-org/matrix.org#2222]
I was just looking at the list of Matrix clients https://matrix.org/ecosystem/clients/ and the iamb client is tagged with linux only, but there are mac and windows builds available on the github releases page: https://github.com/ulyssa/iamb/releases/tag/v0.0.8

It would be great to update the tags / blobs / labels for that client, so that people can see that it supports platforms other than linux. Thanks!

**Comment by thibaultamartin** [comment]
Closed by #2266
