### ISSUE TITLE
Please implement EFF DNT policy

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix.org#2232]
- https://www.eff.org/dnt-policy

Implementing and declaring support for the EFF DNT policy would prevent issues where PrivacyBadger learns to errorneously block matrix.org for tracking in addition to declaring your respect for privacy online.

This has been previously experienced in:

- https://github.com/element-hq/element-web/issues/9185
  - However that specific issue is in wrong repository as the policy would need to be declared in this repository.
- https://github.com/EFForg/privacybadger/issues/2480

**Comment by thibaultamartin** [comment]
We are relying on Plausible for analytics (see [the rationale here](https://ergaster.org/posts/2024/01/24-tracking-what-works/)), that do not collect PII. Other than that, m.org is a static website, so I'm not sure what's up with Privacy Badger?

Plausible [have an interesting discussion](https://github.com/plausible/analytics/discussions/646) about it, and to quote their co-founder:

> DNT is not relevant anymore: it's not part of the privacy regulations, it's used by very few people so it's abused by the adtech to target them and it's being phased out from browsers (and even browsers that offer it, don't have it on by default). and tracking it was supposed to prevent, we don't do in the first place

I tend to be rather aligned with them. The EFF's DNT Policy is rather broad. I'm confident we are not collecting PII and we are not tracking people. But we are also definitely too small to conduct a full audit of and guarantee 100% compliance with the policy.
