### ISSUE TITLE
Hover on Ecosustem menu item is broken

### ISSUE THREAD

**Issue by shadow-identity** [matrix-org/matrix.org#2278]
Repro: 
1. Go to matrix.org
2. Hover over Ecosystem menu item to see the dropdown list
3. Try to select any item in the dropdown.

https://github.com/matrix-org/matrix.org/assets/1223112/2a3492a3-91c2-453c-ae14-4b2735689591

Firefox Dev Edition 125.0b7 (64-bit)
macOS 14.4.1 (23E224)

**Comment by MTRNord** [comment]
Yeah thats known and being worked on at #2267
