### ISSUE TITLE
Doubled meta description

### ISSUE THREAD

**Issue by Ryuno-Ki** [matrix-org/matrix.org#2283]
Hey there :wave: 

today I was on the lookout for the [blog feed](https://matrix.org/atom.xml) and `view-source`d the blog page without success.

I noticed invalid HTML¹ and doubled meta description.
Naturally I was curious what the root cause might be.

You add the description once in

https://github.com/matrix-org/matrix.org/blob/37d780dd3f3b087ee3c4e4022aae12e263b691de/templates/skel.html#L33

and another time in

https://github.com/matrix-org/matrix.org/blob/37d780dd3f3b087ee3c4e4022aae12e263b691de/templates/section.html#L6

I'm not sure what the SEO impact is but it ought to be amendable with another `{% block %}` I suppose.

Keep up the good work!

¹ Missing quotation marks here:

```html
<link rel="stylesheet" href=[https://matrix.org/style.css?h=4941eab217fb09982753](view-source:https://matrix.org/style.css?h=4941eab217fb09982753) />
    <script async src=[https://matrix.org/js/components.js?h=ae3cb894d00e16ef08be](view-source:https://matrix.org/js/components.js?h=ae3cb894d00e16ef08be)></script>
```

**Comment by MTRNord** [comment]
Hi :) thanks for the report! (And sorry for the delayed reply).

The description seems indeed a little odd :D However the invalid HTML appears to be a bug of your browser as I cant reproduce it. Its valid on my side:
![image](https://github.com/matrix-org/matrix.org/assets/1374914/bf492508-2abe-4d80-b97c-6e7d93f64136)
![image](https://github.com/matrix-org/matrix.org/assets/1374914/bd703667-7b84-4375-a550-29a5f6a9d2b0)
