### ISSUE TITLE
Unsure where to post just looking for information

### ISSUE THREAD

**Issue by TheEternalSanguin123** [matrix-org/matrix.org#2351]
Extreme inability to send and receive messages using matrix.org server using Element Desktop application starting since 5/17/2024 going onto 24 hours later at 5/18/2024. Unsure what the issue is and not sure where to potentially check for updates regarding what is going on, or if I should find a different server for the time being if a very serious issue. If an incorrect place to post I can delete it if directed to the right place, just looking for information updates since Matrix is where I chat with all of my closest friends and having this level of disconnect has been uncomfortable the past days.

**Comment by ara4n** [comment]
sorry that you've been caught in the performance problems. status.matrix.org gives an idea of the health of matrix.org, and over the last few days it's been struggling due to traffic levels. we're working on it.

**Comment by TheEternalSanguin123** [comment]
Thank you for the response I saw the status post and was worried at the severity of the levels of what was going on but since it is being worked on I can rest easy as long as total collapse is not a fear that could be present in my head. Thank you for the reply and I'll just keep watching the status to see what occurs.

**Comment by MTRNord** [comment]
I think this is resolved by now? If not please feel free to reopen.
