### ISSUE TITLE
ecosystem/clients page not rendered correctly

### ISSUE THREAD

**Issue by alphapapa** [matrix-org/matrix.org#2380]
Since merging https://github.com/matrix-org/matrix.org/pull/2366, it seems that something in the `clients.html` template is not rendering correctly.  Here's a screenshot of the rendered HTML and one of the DOM, showing that the `{% for client in clients %}` block at the bottom of the template is doing something weird with the newly added client's card.

![bug](https://github.com/matrix-org/matrix.org/assets/601365/22bd7cbf-856d-48fc-b56d-2a795e9bd4f3)

![dom](https://github.com/matrix-org/matrix.org/assets/601365/115ad232-7d9d-4eb3-ac0d-4072c425adfb)

Not being familiar with Zola and Tera directly (though they are similar to Hugo), I can't discern the problem quickly enough, so I'll leave this bug report.  Thanks.

**Comment by MTRNord** [comment]
Hm this is interesting. The html generated by the template should be impossible. It adds a p tag outside of the a tag. But the content in the p tag can only exist in a span inside of the a tag according to the template... Makes me wonder if this is a bug in the template engine :/ But I am not sure whats causing it. Maybe its the link inside of the description. I will see if I can write a patch tomorrow for this. This is very much an unusual bug.
