### ISSUE TITLE
undesired hscroll on home and docs pages

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix.org#2415]
https://github.com/matrix-org/matrix.org/assets/2803622/4a1c07e7-e73d-42f9-b9a6-20232107d7f4

i use a 27" 1440p screen

**Comment by MTRNord** [comment]
@HarHarLinks since I had issues reproducing this before please check if the fix that was just deployed fixes it for you

**Comment by konan-5** [comment]
@MTRNord 
there is also undisired scroll in spec page.

**Comment by konan-5** [comment]
hello @MTRNord 
how are you today
actually, I'd like to be a part of team. is there any way that can work together?
I am looking forward to hearing from you.
Thank you

**Comment by HarHarLinks** [comment]
> @HarHarLinks since I had issues reproducing this before please check if the fix that was just deployed fixes it for you

appears to work for me
