### ISSUE TITLE
Sign Up is Broken

### ISSUE THREAD

**Issue by jwaresoft** [matrix-org/matrix.org#2470]
There are a lot of projects, so I am assuming this doesn't go on the web app proper but maybe we can find the right place.

Signing up for a matrix.org account through the element webapp per the instructions linked to matrix.org does not work.  You will never get a confirmation email, I tried on several emails from several providers and confirmed they could communicate with each other.  It is not in any spam folder.

**Comment by tulir** [comment]
There's no issue tracker for the matrix.org homeserver, but that issue is already posted on https://status.matrix.org/

**Comment by jwaresoft** [comment]
Thanks ill close this then.
