### ISSUE TITLE
how to add a project to the ecosystem page?

### ISSUE THREAD

**Issue by 8go** [matrix-org/matrix.org#2484]
How can I add the project https://github.com/8go/matrix-commander-rs

to the ecosystem page https://matrix.org/ecosystem/clients/

on the matrix.org website?

There is https://github.com/matrix-org/matrix.org/blob/main/content/ecosystem/clients/matrix-commander-rs.svg but no matrix-commander-rs.md.

Do I just submit a new https://github.com/matrix-org/matrix.org/blob/main/content/ecosystem/clients/matrix-commander-rs.md?

**Comment by thibaultamartin** [comment]
Will be fixed by https://github.com/matrix-org/matrix.org/pull/2155/, contributions more than welcome!

**Comment by 8go** [comment]
OK, from my perspective this issue can be closed as it will be tracked in #2155.
