### ISSUE TITLE
can't download images

### ISSUE THREAD

**Issue by lands39** [matrix-org/matrix.org#2518]
When i click download on an image in matrix, i can't open it. it says 404 not found even though i can open it in the app. 

Sorry if this isn't the place to report issues, i'm having a difficult time trying to find where i should do this. 

![problem](https://github.com/user-attachments/assets/26728c58-68fc-49fd-8310-25e47e3e621f)

**Comment by lands39** [comment]
more issues, i tried asking for help in the matrix room and now i can't send any messages or leave
![image](https://github.com/user-attachments/assets/378c37d5-82c0-4593-a503-4df5b7670407)

**Comment by artenax** [comment]
To understand the problem, tell us who is sender of these images? I mean which client (e.g. Element, app.element.io, alternative apps), on which system (Windows, Android), which server account (matrix.org or third-party).

**Comment by lands39** [comment]
this was happening so much that i decided to switch to a different homeserver, consider the issue closed.

**Comment by artenax** [comment]
> switch to a different homeserver

Because only `app.element.io` is broken at the request of the police?

**Comment by lands39** [comment]
all clients.

**Comment by djelton** [comment]
I have the same problem when I'm sending pictures using iobroker matrix client to my homeserver. If I'm using "Element X" on Android, I can see the thumbnail, but I can't open the image. If I'm using "Matrix Chat", then nothing is shown, not even a thumbnail. 
I'm using version 1.1 on ioBroker and 1.53 on server side (on Ubuntu 24.02 LTS).

**Comment by lands39** [comment]
i moved to a different homeserver and that fixed the issue for me
