### ISSUE TITLE
File and image sharing is broken on matrix.org

### ISSUE THREAD

**Issue by artenax** [matrix-org/matrix.org#2537]
At least with new files.
At least in unencrypted private chats.
At least in the old alternative clients Fractal 4.4.2 (GTK3) and Quaternion v0.0.95.1 (from Ubuntu 22.04 repository).
For example, I upload a file to app.element.io, but these clients report 404 when I try to download.
However, I see that these clients can download old files from history, for example from August 10, 2024.
This problem is also mentioned [here](https://github.com/matrix-org/matrix.org/issues/2518).
Perhaps you moved to a new API and broke backwards compatibility?

**Comment by artenax** [comment]
```
Debugging:

Quaternion:

Upload (Quaternion):
POST https://matrix.org/_matrix/media/r0/upload?filename=pogoda%2019%20oct%202024%20%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%BE.png

response:
"content_uri": "mxc://matrix.org/yvTXzfGUAcFeJQCnAIHVLfMM"

Download (Quaternion):
https://matrix.org/_matrix/media/r0/download/matrix.org/yvTXzfGUAcFeJQCnAIHVLfMM?allow_remote=true
"errcode": "M_NOT_FOUND"

-----

Fractal 4.4.2
proxychains4 /opt/fractal4/bin/fractal

Upload (Fractal):
POST https://matrix-client.matrix.org/_matrix/media/r0/upload?access_token=syt_YXJ0ZW5vdW0_VbxLtlOwvHKFPFFMaSRS_2Iaff8

response
"content_uri": "mxc://matrix.org/QaDTenPbOLZiWwkeGQyvCSQu"

Download (Fractal):
https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/QaDTenPbOLZiWwkeGQyvCSQu
"errcode": "M_NOT_FOUND"

Download (Quaternion):
https://matrix.org/_matrix/media/r0/download/matrix.org/QaDTenPbOLZiWwkeGQyvCSQu?allow_remote=true
"errcode": "M_NOT_FOUND"

Download (app.element.io) OK:
https://matrix-client.matrix.org/_matrix/media/v3/download/matrix.org/QaDTenPbOLZiWwkeGQyvCSQu?allow_redirect=true
OK (200 OK from service worker)
no authorization header

or
https://matrix-client.matrix.org/_matrix/client/v1/media/download/matrix.org/QaDTenPbOLZiWwkeGQyvCSQu?allow_redirect=true
OK (200 OK)
with request header:
Authorization: Bearer syt_YXS0ZW5vdW0_qfSuOrUuyLeHrbHoiytN_3KSg1U

-----

Upload (app.element.io)
blob:https://app.element.io/8dSc441b-ce92-4a5e-a6c5-6c4041b7b93f

Download (app.element.io)
https://matrix-client.matrix.org/_matrix/media/v3/download/matrix.org/iSAtAwXIhHhgIaEJYdYPQOdH?allow_redirect=true
OK

Download (Fractal):
https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/iSAtAwXIhHhgIaEJYdYPQOdH
no authorization header
answer:
"errcode": "M_NOT_FOUND"

Download (Quaternion):
https://matrix.org/_matrix/media/r0/download/matrix.org/iSAtAwXIhHhgIaEJYdYPQOdH?allow_remote=true
no authorization header
answer:
"errcode": "M_NOT_FOUND"

```

**Comment by artenax** [comment]
app.element.io sees images uploaded through older clients.

So I see that the Authorization: Bearer header is now required to download files.
You've broken backwards compatibility.

**Comment by artenax** [comment]
I compiled the git version of Quaterion. The address is a bit different, but the same 404 error.
```
Download (Quaternion):
https://matrix.org/_matrix/media/v3/download/matrix.org/nHUFNkMJNWhjFanGffEtbxWU?allow_remote=true&timeout_ms=20000&allow_redirect=false
no authorization header
answer:
"errcode": "M_NOT_FOUND"
```

**Comment by artenax** [comment]
Fractal in Flatpak works fine. But app.element.io in the browser shows images, but does not let me save them to disk, 404. Lol.

**Comment by artenax** [comment]
Using the Rewrites filter in Charles MITM Proxy, I was able to change the headers and URLs and get Fractal 4.4.2 working. At least with images.
I changed the URL parameters and attached an authorization header.
This code is specific to the Fractal 4.4.2 client.
```
Replace:
https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/*

With:
https://matrix-client.matrix.org/_matrix/client/v1/media/download/matrix.org/*
Authorization: Bearer syt_YX...
```
![001](https://github.com/user-attachments/assets/612cd18f-cee1-42d0-b8a9-c8314e53ce43)

-----

![002](https://github.com/user-attachments/assets/bb9cc675-bf0a-45c9-b2e1-df5aedd871ad)

-----

![003](https://github.com/user-attachments/assets/6758d81f-ed6d-432c-a522-e4d2a38c791b)

-----

![004](https://github.com/user-attachments/assets/d312a235-d2b0-436a-affe-c2012c0b3e17)

**Comment by artenax** [comment]
Room version: 9
Unencrypted.

**Comment by morguldir** [comment]
https://matrix.org/blog/2024/06/26/sunsetting-unauthenticated-media/

Usually backwards compatibility comes after legal and security issues like these

The reason you’re not getting a response is that this repository is for the website matrix.org, not the homeserver, the best place to ask about the server is on matrix itself. If you do want to use really old clients, there are probably other homeservers that fit you better

**Comment by KitsuneRal** [comment]
@artenax, with my Foundation hat on - it's not a problem with Matrix, it's a problem with outdated clients. Please consider reading the blog at https://matrix.org/blog before filing issues, the news about sunsetting unauthenticated media is still easy to find there and we've been talking about it for the last 5 months.

With my Quaternion hat on - I'll address your issue in Quaternion repo separately.

**Comment by artenax** [comment]
I understand. I wish the Matrix API was stable.

**Comment by artenax** [comment]
@KitsuneRal
I hope you fix Quaternion and build for win7. I don't like the way history is organized in most Jabber clients and too many settings.

@Matrix developers
Please don't break compatibility at least with text.
