### ISSUE TITLE
Too many items in the navigation bar

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix.org#260]
At certain screen sizes the layout is breaking. Sure you can fix the CSS but also I think there are just too many items in that top bar. You need some way to combine some of those things or make them accessible from other pages.

![screen shot 2018-10-28 at 12 43 00 pm](https://user-images.githubusercontent.com/5855073/47619636-259d5500-daaf-11e8-9714-f02996b7f19f.png)

Try Matrix Now and Clients could ideally could be one page.

~~TWIM probably doesn't need to be up there next to blog.~~ Although now I realize that TWIM doesn't appear in the blog anymore. Not sure what the best fix is for that.

Status could be at the bottom of the page.

You could put more things in this section of the home page. Like a button for clients, a button for servers (#95?) and hosting (modular and upcloud), and then a button for developers which would bring them to another page where they could access the spec and the client-server APIs, and code. 
![screen shot 2018-10-28 at 12 47 02 pm](https://user-images.githubusercontent.com/5855073/47619676-98a6cb80-daaf-11e8-9272-bdf31951bb73.png)

**Comment by benparsons** [comment]
This should be visually resolved, so closing. Still need to think a little about what menu items to prioritise.
