### ISSUE TITLE
Replace prominent Nheko links since Nheko isn't currently maintained

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix.org#278]
- [ ] ![screen shot 2018-11-13 at 7 00 01 pm](https://user-images.githubusercontent.com/5855073/48452803-54395200-e776-11e8-8586-23fc209c72a6.png)
- [ ] Big Try Matrix Now image
![screen shot 2018-11-13 at 7 01 04 pm](https://user-images.githubusercontent.com/5855073/48452837-79c65b80-e776-11e8-9499-71b2f41ab52a.png)

I'd vote for replacing Nheko with Fractal on the homepage maybe and the something else for Try Matrix Now. I'd suggest Seaglass but warning I am a contributor :).

**Comment by Half-Shot** [comment]
Somewhat related https://github.com/matrix-org/matrix.to/issues/46
