### ISSUE TITLE
Broken link to spec core team

### ISSUE THREAD

**Issue by jryans** [matrix-org/matrix.org#283]
On the [spec process](https://matrix.org/docs/spec/proposals) page, section 1 links to a [supposed list of the core team](https://github.com/orgs/matrix-org/teams/spec-core-team/members), but this link gives a 404 error.

If the link works for people inside the org, perhaps the team needs to be made public.

**Comment by benparsons** [comment]
Looks like team membership is only ever visible to members in the organisation, we'll need to find another way to list members.

**Comment by jryans** [comment]
There does [appear](https://developer.github.com/v3/teams/members/) to be an API for listing team members, so perhaps some build step could dump the current list somewhere...?

**Comment by turt2live** [comment]
we replaced the link

**Comment by aaronraimist** [comment]
Would be nice if it linked directly to the spec core team section. First I thought the link was incorrect, I didn't even realize the spec core team members were listed on that page.

**Comment by turt2live** [comment]
@aaronraimist https://github.com/matrix-org/matrix-doc/issues/2147
