### ISSUE TITLE
Matrix logo in nav links to blog instead of home page

### ISSUE THREAD

**Issue by jryans** [matrix-org/matrix.org#284]
On many sites, clicking the logo in a header nav bar will go to the home page of the site. However for matrix.org, the logo currently links to the blog.

Maybe it should be changed to the home page? (I'm not sure if it was intentional.)

**Comment by Half-Shot** [comment]
Sounds like a wordpress fun thing to me, but I agree.

**Comment by benparsons** [comment]
Finally this is also fixed in wordpress
