### ISSUE TITLE
C-S Swagger API tool removed from nav, quite hard to find now

### ISSUE THREAD

**Issue by jryans** [matrix-org/matrix.org#285]
In 866d7fecba4759bade7033fdab6ece8a2a262e96, the [C-S Swagger API viewer](https://matrix.org/docs/api/client-server/) was removed from the nav bar.

I agree it doesn't belong in the primary site nav bar, but it's quite hard to find at all, as there are very few links to it, and it's quite a handy tool. Maybe the [main spec page](https://matrix.org/docs/spec) should link to it?

**Comment by benparsons** [comment]
Should be addressed by https://github.com/matrix-org/matrix-doc/commit/16f17855c9365f5e59fd954ce61f404b67739112
