### ISSUE TITLE
Create a who's who page

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix.org#293]
This should fix #283

**Comment by shivam1192** [comment]
@benparsons can you please elaborate it

**Comment by MadLittleMods** [comment]
This seems solved with https://matrix.org/foundation/ which lists the guardians and spec core team

Source: [`gatsby/src/pages/foundation.js`](https://github.com/matrix-org/matrix.org/blob/ec7a9d42744e3c0ddb6613197859aa70eaf500c4/gatsby/src/pages/foundation.js)
