### ISSUE TITLE
Write FAQ about how Matrix.org HS is hosted

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix.org#298]
Some info here 
https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$15448853122944541SfWfb:matrix.org

**Comment by keithzg** [comment]
The static view link gives
> The requested URL /room/!QtykxKocfZaZOUrTwp:matrix.org/$15448853122944541SfWfb:matrix.org was not found on this server.

:*(
