### ISSUE TITLE
[Feature] Add donations via ZCash

### ISSUE THREAD

**Issue by asddsaz** [matrix-org/matrix.org#302]
**Description**: Accept donations via ZCash.
**What is ZCash**? ZCash is often considered the most popular anonymous cryptocurrency.
More info: https://www.wikipedia.org/wiki/Zcash

**Comment by thibaultamartin** [comment]
Managing a portfolio of cryptocurrencies can represent significant overhead for the finance team of the Foundation. We do not plan to accept new cryptocurrencies in the medium run
