### ISSUE TITLE
add https://github.com/ma1uta/mxtoot

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix.org#316]

**Comment by aaronraimist** [comment]
Already there https://github.com/matrix-org/matrix.org/blob/8bed937b6b17f2db831b2bd6150678e50723b278/jekyll/_posts/projects/2018-12-13-mxtoot.md

**Comment by uhoreg** [comment]
It's not showing up on https://matrix.org/docs/projects/try-matrix-now.html, though? :-/

**Comment by uhoreg** [comment]
Ah, I see, it's on https://matrix.org/docs/projects/bridges.  Never mind me then.

**Comment by aaronraimist** [comment]
It should probably be in both places though. Will be fixed by #317.
