### ISSUE TITLE
Twitter and Google JS

### ISSUE THREAD

**Issue by kayb94** [matrix-org/matrix.org#319]
Hi,

I was about to inform myself about Matrix on your website. Only heard good things about your project so far. I'm not really into web development, but I wonder:

Is it necessary to have both Twitter and Google tracking on your website? At least that's what NoScript plugin for Firefox tells me, where additional JS scripts for your website come from. And AFAIK that normally comes along with tracking.

Kind Regards
Kay

**Comment by MadLittleMods** [comment]
Hey @kayb94, It looks like Twitter is added so we can show embedded Tweets on the homepage under the `What people are saying` section.

![chrome_2021-08-17_17-02-50](https://user-images.githubusercontent.com/558581/129806639-3c91d681-0b99-4c7a-8a8b-0e2d5fc16111.png)

---


I don't see Google analytics used anymore but we do use [Matomo](https://matomo.org/), (added in https://github.com/matrix-org/matrix.org/commit/48545495afe19a40152a166baee521bca1562d07) which self-proclaims as "Google Analytics alternative that protects your data and your customers' privacy"
