### ISSUE TITLE
FAQ says 'What is a home server?' instead of homeserver

### ISSUE THREAD

**Issue by jryans** [matrix-org/matrix.org#323]
https://matrix.org/docs/guides/faq#what-is-a-home-server%3F

**Comment by aaronraimist** [comment]
https://github.com/matrix-org/matrix.org/search?p=1&q=%22home+server%22&unscoped_q=%22home+server%22

**Comment by richvdh** [comment]
Fixed in https://github.com/matrix-org/matrix.org/pull/325
