### ISSUE TITLE
Search by programming language with wrong results

### ISSUE THREAD

**Issue by mttkrb** [matrix-org/matrix.org#333]
When I'm searching on https://matrix.org/docs/projects/try-matrix-now.html for clients with C# as language the following results are shown:
- Nebuchadnezzar
- matrix-client.el 
- Emacs Maelstrom 
- FluffyChat 
- AgentSmith

In all these projects the language is not C#

**Comment by mrdemc** [comment]
Nebuchadnezzar is a C# client: https://github.com/MartijnBraam/Nebuchadnezzar
If I try the same I only get this project, the others are filtered out.

**Comment by mttkrb** [comment]
This is my search result. 
![grafik](https://user-images.githubusercontent.com/21170293/52478075-7f301800-2ba4-11e9-95fa-e4e366e806e9.png)

Ok Nebuchadnezzar is really a C# client. I was a little bit confused, because its description on the matrix page is "Linux native chat client (GTK2)"

**Comment by benparsons** [comment]
The result you're seeing is still wrong. Am taking a look.

**Comment by benparsons** [comment]
@mttkrb can you tell me if you're still seeing this result? Made various unrelated fixes and can no longer repro

**Comment by mttkrb** [comment]
Hi,
at a first look there no wrong results. 
thanks a lot.
