### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix.org#353]
the faq should really be updated.. " As of Sept 2017 we are finally in the process of incorporating it as a dedicated non-profit entity (most likely a limited by guarantee UK private company called the Matrix.org Foundation)."

**Comment by benparsons** [comment]
(thanks cos)

**Comment by richvdh** [comment]
see https://github.com/matrix-org/matrix.org/labels/faq

**Comment by afranke** [comment]
I reckon [What kind of company is Matrix.org?](https://matrix.org/faq/#what-kind-of-company-is-matrixorg) addresses this specific point. Can we close this?
