### ISSUE TITLE
Fix preview images in facebook

### ISSUE THREAD

**Issue by bradyt** [matrix-org/matrix.org#356]
If one posts https://matrix.org to facebook, the preview image is two images.

The first is blank (white on white),

![safe_image](https://user-images.githubusercontent.com/6107051/55928687-81c3e380-5bce-11e9-8854-3586c8d5925f.png)

The second is apparently "bitcoin" but too big for the preview pane.

![safe_image (1)](https://user-images.githubusercontent.com/6107051/55928688-84263d80-5bce-11e9-9004-9aca05162c55.png)

**Comment by thibaultamartin** [comment]
This should have been fixed with the opengraph tags we added for the new website. Please reopen if the previews are still broken
