### ISSUE TITLE
404 error for the RSS feed

### ISSUE THREAD

**Issue by vbrandl** [matrix-org/matrix.org#366]
While you might have other problems to worry about right now and this isn't the repository for the blog (don't know if there is one):

I noticed, that the RSS feed linked at the bottom of the page and in the HTML metadata (https://matrix.org/blog/feed/) does not exist and results in a 404 error.

**Comment by Salzi** [comment]
The "new" blog is online but the RSS feed is still not working. Any plans to reactivate it?

**Comment by jryans** [comment]
I've added this to the list of things that need to be restored. I can't offer an ETA, but I am sure it will be restored.

**Comment by irgendwie** [comment]
https://matrix.org/blog/feed/ now seems to work

**Comment by jryans** [comment]
Yes, the RSS feed has now been restored by https://github.com/matrix-org/matrix.org/commit/0bbdb1ef21af97716290d87e30223b55a7d2f119. Thanks for your patience!

**Comment by ofelt** [comment]
Would it be possible to have the full articles (not just the first two lines) in the rss feed like previously ? Thanks !

**Comment by jryans** [comment]
Yes, please see #408 for restoring the body in the feed.
