### ISSUE TITLE
matrixnotorg should be ashamed of himself

### ISSUE THREAD

**Issue by adolfintel** [matrix-org/matrix.org#368]
Instead of attacking the service, you could have contacted the developers and help them improve the security.
What you did only proves what kind of scumbag you are.

**Comment by michaelpittino** [comment]
The only one who should be ashmed is matrix.org for having simple vulnerabilities like outdated software. They are trusted with very sensitive user data and can't even keep theit jenkis up to date!?

**Comment by richvdh** [comment]
this is not the place for this debate.
