### ISSUE TITLE
[Security] Leverage DevSec to automatically increase security

### ISSUE THREAD

**Issue by stdevel** [matrix-org/matrix.org#369]
Hello matrix.org team,
as I saw in issue #361, you are using Ansible to configure your infrastructure, including SSH.
I would have commented in the former issue what I'm posting here, but unfortunately the issue was locked to contributors.

I suggest having a look at the [DevSec Hardening Framework](https://dev-sec.io/) as this could have helped you to avoid attacks like these. DevSec offers pre-configured InSpec security audit catalogs and combines these catalogs with auto-remediation code available for Ansible, Chef and Puppet. In other words - using this can automatically fix security issues.
There is a special [baseline for SSH](https://dev-sec.io/baselines/ssh/), but beyond that you will also find baselines for Linux, databases, Docker and so on.

Good luck for your further forensic analysis - hope you will get things fixed very soon.

Best wishes,
Christian.

**Comment by idnovic** [comment]
I use the devsec rules myself. They are great. A big german telecommunications company makes use of it too. iirc they were created by the telco.

**Comment by kusuriya** [comment]
:+1: here, try to incorporate some sort of hardening into your automation.
