### ISSUE TITLE
Compromise of encryption?

### ISSUE THREAD

**Issue by hook-s3c** [matrix-org/matrix.org#372]
I still think someone needs to do a diff of the javascript on the compromised server vs the new prod, just to be 100% sure the attacker didn't drop a message logger on encrypted chats, or at least make these findings public on the blog

**Comment by ara4n** [comment]
based on our initial analysis (diffing the js etc) riot/web was not tampered with.

**Comment by hook-s3c** [comment]
thanks @ara4n ! but as the DNS records were changed, then anything could have been served, right?

**Comment by jryans** [comment]
@hook-s3c The [Riot Web releases page](https://github.com/vector-im/riot-web/releases) has snapshots of each release with signatures. Comparing this with what's served on https://riot.im/app shows the same code is being served there.

As for DNS, there was a single blip to the attacker's disclosure site for a few moments. We aren't aware of a time when matrix.org content (including Riot) was served elsewhere.
