### ISSUE TITLE
stop advertising neo-nazi chatrooms

### ISSUE THREAD

**Issue by rain-1** [matrix-org/matrix.org#373]
Hello

when I go to add rooms on the matrix riot app I get shown (at least) 2 neo-nazi chatrooms which included racism, holocaust denial and sharing the recent shooting videos.

Just a suggestion to not advertise these rooms, you're really helping these people by staying neutral and allowing them to get a high position in the channels list simply by numbers (which may well be bots).

**Comment by hook-s3c** [comment]
It's likely someone is trolling, they did this yesterday

**Comment by rain-1** [comment]
It may also be worth considering whether you want to support these channels by supplying them free IRC<->matrix bridges.

**Comment by ara4n** [comment]
i've gone through the first few pages of the matrix.org roomdir and i'm not seeing the ones in question. what am i missing?

<img width="995" alt="Screenshot 2019-04-14 at 13 38 47" src="https://user-images.githubusercontent.com/1294269/56092939-b67bb780-5eba-11e9-819f-adabbd1a4386.png">

**Comment by Kruppstahl** [comment]
Here we go again, another attempt to push politics into technology. Not even to mention that no one cares about all the radicals on the left, but who cares...

One of the purposes behind a decentralized communication platform is that it's not so easy to influence it. Sure, I would ban those guys too probably, but what if next year someone comes up with the idea to ban a "against-abortion"-chatroom? And what if the climate changes further; who defines what is a "hate group"?

**Comment by aaronraimist** [comment]
It *is* a decentralized platform. They cannot be banned from Matrix, but they can be taken off of matrix.org. They are free to create their own servers and live there however they are not free to use other people’s infrastructure to host awful things. Matrix.org does not have to give them a platform.

**Comment by dasteihn** [comment]
@aaronraimist Fair enough. Regardless of that I would advise to be extremely careful when I set up the rules you use  when deplattforming people. What is acceptable and what is not; rooms cheering Hitler are bad, obviously, but what about a Mao Zedong (killed 60 million people) fanroom?

You see, currently plattforms like Facebook and YouTube (which de-monitizes conservatives like PragerU on a frequent basis) are running serious danger of censoring opinions not appearing opportunistic to the present definitions of right and wrong by some. Patreon has deplattformed several people last year out of political bias, some of whom were definitely not radicals... they can decide with whom they're working, but what makes you think PayPal will let you buy a shooter video game in 5 years when the political climate has changed after another school shooting?

My last comment: If you decide to ban groups from your plattforms, specify *exact and precise* rules. "Hate groups are forbidden" is not a precise rule for example. Who defines what "hate" is? Create a set of precise rules ("rooms who endorse murder are not permitterd", i.e.) and follow this set for each ban, no matter if it's right- or leftwingers or islamists.

**Comment by gentlecolts** [comment]
Matrix is founded on the principles of security, privacy, and decentralization.  I would be incredibly disappointed if matrix censored any groups, regardless of their political background.

**Comment by turt2live** [comment]
Matrix can't ban groups due to the federated nature. The matrix.org homeserver on the other hand has a terms of service, which does not affect the entire platform.

Is anyone able to answer Matthew's earlier question? https://github.com/matrix-org/matrix.org/issues/373#issuecomment-482966462

**Comment by rain-1** [comment]
sent an email to @ara4n with the rooms in question.

**Comment by rain-1** [comment]
> Here we go again, another attempt to push politics into technology. Not even to mention that no one cares about all the radicals on the left, but who cares...

What are you talking about? Why have you not taken the initiative and reported this "radical left" room? or does it not actually exist and you're just straw-manning?

> but what if next year someone comes up with the idea to ban a "against-abortion"-chatroom?

That's not what we're talking about. This argument makes no sense.

> what about a Mao Zedong (killed 60 million people) fanroom?

I suggest you report this room if you feel it is harmful in some way. Or did you just fabricate this as a hypothetical? If it doesn't even exist why are you even bringing it up.

> plattforms like Facebook [..]

Irrelevant, We're just talking about matrix here.

> If you decide to ban groups from your plattforms, specify exact and precise rules

Please focus on the issue with some clarity. This isn't about banning a room, this is about not providing free advertising for the chatroom in the main matrix/riot rooms list.

There is no need for any rules. There are sane rational people here capable of making decisions. You can remove a neo-nazi room that tries to pipeline people into the alt-right from a list and just stop there.

**Comment by rain-1** [comment]
@gentlecolts

> Matrix is founded on the principles of security, privacy, and decentralization. I would be incredibly disappointed if matrix censored any groups, regardless of their political background.

What if they were literally fascists?

**Comment by ara4n** [comment]
The situation is very simple: rooms which are counter to https://github.com/vector-im/policies/blob/master/docs/matrix-org/terms_and_conditions.md#61-use-of-the-service are not welcome on the Matrix.org server.

As @turt2live said in https://github.com/matrix-org/matrix.org/issues/373#issuecomment-483004481, Matrix as a whole is a decentralised network and for better or worse nobody can control what servers people choose to run and which rooms they choose to host on them. 

However, individual servers are perfectly entitled to remove rooms from their directory listing they don't want to advertise, and could also block their servers from participating in rooms.

I suggest we please avoid this conversation turning into a discussion of what the definition of evil is, however.

**Comment by hyphenrf** [comment]
@ara4n good to see swift, professional, and neutral response to the good-hearted initiative.
Is there a transparency disclosure somewhere for this kind of moderating actions?

What I mean by that is a page where matrix.org's moderators log their actions after hiding/banning/etc.. channels. I have good faith in this model of open moderation being followed here, to avoid personally motivated censorship. I just don't know where to look.

**Comment by ara4n** [comment]
We don’t keep a transparency log currently for terms of use violations of the matrix.org server, i’m afraid. It’s something we could consider in future if/when we have more folk dedicated to moderation, but frankly I’d rather spend the time working on p2p matrix or decentralised accounts so we can shut down the matrix.org server entirely - after all, running a massive server is a huge liability and pain in the ass, as we saw last week, and is an unnecessary source of centralisation.

Separately we are working on empowering users to filter out content they don’t want to see - but letting the user pick what filters to apply, which should help solve this problem in the general case rather than just for matrix.org.

Finally, it’s worth noting that we are a UK based org, and with legislation like https://www.gov.uk/government/consultations/online-harms-white-paper on the horizon, we may be legally compelled to apply certain filters to content on the matrix.org server in future - so if you don’t like those filters, you’ll need to go find a different server.

**Comment by ara4n** [comment]
we've reviewed the roomdir and this can be closed now (modulo https://github.com/vector-im/riot-web/issues/9285#issuecomment-483063976)

**Comment by Malix-Off** [comment]
Was the change made to the matrix protocol in itself or the matrix.org homeserver?
