### ISSUE TITLE
404 error for the /packages directory

### ISSUE THREAD

**Issue by killua-eu** [matrix-org/matrix.org#374]
Before #370 gets resolved, it would be great to (even manually) restore the content of the https://matrix.org/packages/ - its been already a few days that current matrix is not installable with a package manager (barrier for setting up new hs) and which breaks (non-fatally) autodeployments such as with ansible.

**Comment by ara4n** [comment]
yes. we obviously want to get packages back up asap, but given the signing keys were compromised, we want to make damn sure that we are re-publishing secure content.  meanwhile, our priority is getting the matrix.org server & services running first, and then the dev deps (git.matrix.org etc also).

**Comment by turt2live** [comment]
Packages are back now, and freshly signed. Note that it's been moved to packages.matrix.org with a new key (found by browsing)
