### ISSUE TITLE
Mobile overflow

### ISSUE THREAD

**Issue by nadonomy** [matrix-org/matrix.org#383]
![ima_c8453d4](https://user-images.githubusercontent.com/4626865/56386512-45256700-6222-11e9-9485-5a20855a2517.png)

**Comment by MadLittleMods** [comment]
I assume this is the homepage. This is better nowadays but there is a slight horizontal scrollbar at some resolutions (probably better to track in other new specific issues)

![](https://user-images.githubusercontent.com/558581/129809007-b9e07167-a80a-4cf0-b664-d3bd531d8b79.png)
