### ISSUE TITLE
Fix sitemap.xml and point to it from robots.txt  

### ISSUE THREAD

**Issue by neilisfragile** [matrix-org/matrix.org#390]

**Comment by Mikaela** [comment]
I tried to fix this at https://github.com/matrix-org/matrix.org/compare/master...Mikaela:sitemap, but it doesn't seem to be so simple as it behaves differently from other Jekyll sites I have used.

`jekyll serve` starts at http://127.0.0.1:4000/docs/ and my robots.txt is neither at http://127.0.0.1:4000/docs/robots.txt or http://127.0.0.1:4000/robots.txt .

**Comment by richvdh** [comment]
looks like `file: "/sitemap.xml"` is missing some indentation?

is the sitemap.xml generated in `jekyll/_site` by `jekyll build` ?

**Comment by Mikaela** [comment]
I added indentation. 

Yes and I can find it at http://127.0.0.1:4000/docs/sitemap.xml and my robots.txt is appears to be at http://127.0.0.1:4000/docs/robots.txt .

**Comment by richvdh** [comment]
Right, I'm not familiar with `jekyll serve`.

I think the thing to note is that only part of the site is generated by jekyll. I don't know if that means that a sitemap.xml generated by jekyll will be useless, but assuming it's better than nothing, the easiest way to get `robots.txt` into the right place is probably to stick it into [content](https://github.com/matrix-org/matrix.org/tree/master/content). All of that directory is copied to the website.

You might also need to update https://github.com/matrix-org/matrix.org/blob/master/.buildkite/pipeline.yaml#L42 to copy the generated sitemap into the right place in the target.

**Comment by Mikaela** [comment]
How about using a [sitemap index](https://www.sitemaps.org/protocol.html#index) in content pointing to the Jekyll sitemap and later the other sitemaps as they get generated?

Another option would be having multiple sitemap entries which [Google allows](https://developers.google.com/search/reference/robots_txt#sitemap)?

>  Supported by Google, Ask, Bing, Yahoo; defined on sitemaps.org.
> 
> Usage:
> 
> sitemap: `[absoluteURL]`
> 
> [absoluteURL] points to a Sitemap, Sitemap Index file or equivalent URL. The URL does not have to be on the same host as the robots.txt file. **Multiple sitemap entries may exist**. As non-group-member records, these are not tied to any specific user-agents and may be followed by all crawlers, provided it is not disallowed.

(Emphasis mine)

**Comment by thibaultamartin** [comment]
Google now seems happy with our robots.txt and sitemap.xml (according to the Google owned pagespeed.web.dev)
