### ISSUE TITLE
Highlight the state of authentication support

### ISSUE THREAD

**Issue by jryans** [matrix-org/matrix.org#396]
We should highlight the state of authentication support (LDAP, SSO, etc.) somewhere on matrix.org. It's likely quite important for many large orgs, but it's currently quite hard to figure out what's supported in that space today.

Maybe a new page similar to the client and bridge pages could summarise auth options?

**Comment by jimmycuadra** [comment]
Any progress on this? Where's the best place to look for documentation on SSO right now?

**Comment by thibaultamartin** [comment]
There is now a filter on the clients page to filter out clients that don't support SSO.

As for the servers… one is stable (Synapse), and four of them are in beta (Construct, Conduit, Dendrite). I'm not sure it's worth listing the features supported by the servers on matrix.org itself? Please reopen to talk about it if you disagree
