### ISSUE TITLE
can we publish the source for our privacy policy templates?

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix.org#417]
Currently the source for things like https://matrix.org/_matrix/consent is hidden in a private git repository. It would be nice to open it up, both for visibility for people who want to see how the consent forms have evolved over time, and to serve as examples for people wishing to set up their own privacy policy for their own homeservers.

**Comment by rubo77** [comment]
This is the conclusion of https://github.com/matrix-org/synapse/pull/3886

**Comment by ara4n** [comment]
sure. can we just move them to the github.com/vector.im/policies repo or somewhere?

**Comment by benparsons** [comment]
https://github.com/vector-im/policies is now the place to look.
