### ISSUE TITLE
https://matrix.org/security-disclosure-policy/ is gone

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix.org#425]

**Comment by ara4n** [comment]
investigating

**Comment by ara4n** [comment]
the CI is only zipping up the /blog subdirectory, meaning that the other 809 files that gatsby generates are getting lost (including the security-disclosure-policy page).  This is particularly obvious if you look at the network inspector when viewing a blogpost, where the majority of network requests 404.

I'm amazed it's working at all...?

**Comment by richvdh** [comment]
sorry, I was led to believe that the only useful output from gatsby was the `/blog` subdirectory. Currently investigating how best to reconcile the spew from gatsby with the existing spew from 3 other sources.
