### ISSUE TITLE
Link to INSTALL.md on https://matrix.org/docs/guides/installing-synapse

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix.org#427]
It should probably be the most prominent.

Right now people think that https://www.natrius.eu/dokuwiki/doku.php?id=digital:server:matrixsynapse is the official guide.

**Comment by aaronraimist** [comment]
Maybe https://github.com/PC-Admin/PC-Admin-s-Synapse-Setup-Guide should also be linked?

**Comment by benparsons** [comment]
https://www.natrius.eu/dokuwiki/doku.php?id=digital:server:matrixsynapse has served as a semi-official guide - #synapseguide:matrix.org has been used to oversee. Previously INSTALL.md was not maintained enough to link to, but you're right that's probably no longer true and we should link to it.
