### ISSUE TITLE
Remove unexpected characters from checked-in filenames

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix.org#428]
Apparently there are ?s in filenames.

**Comment by turt2live** [comment]
This is still a problem - looks like https://github.com/matrix-org/matrix.org/commit/ef9dd3d4085f840b7933ea080679b8e9b940c463 undid a bunch of the work.

**Comment by benparsons** [comment]
@turt2live could you confirm whether this is now fixed?

**Comment by turt2live** [comment]
Fixed, thanks @benparsons!
