### ISSUE TITLE
Change IP of turn.matrix.org for unblock matrix.org calls in Russia

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/matrix.org#435]
Matrix TURN server turn.matrix.org after reorganization got new IP 94.237.57.30 that, unfortunately blocked in Russia together with Telegram blocking, here is online checker:  https://isitblockedinrussia.com/?host=turn.matrix.org

So now all WebRTC calls without white IP not works for Russian users of matrix.org domain.

Same thing was be with Matrix.org synapse IP before, but was solved already. Can you select new IP for turn.matrix.org too, that is not blocked in Russia?

P.S. If I post issue in wrong project, please point me where to post issues about matrix.org Synapse server?

**Comment by richvdh** [comment]
see also https://github.com/matrix-org/matrix-federation-tester/issues/85

**Comment by MurzNN** [comment]
After #439 turn.matrix.org IP is still blocked in Russia :( Does Matrix clients allowed to use other turn server for p2p connections, different from filled on Synapse server?

**Comment by MurzNN** [comment]
Russian users still can't use Matrix call features on default server :(

Can you just move turn server to subnet, near to `jitsi.riot.im` (94.237.57.21) or `scalar.vector.im` (104.31.71.95, 104.31.70.95)? Those subnets are not blocked in Russia, and seems Russian government stop process of blocking new Telegram IP ranges (replaced them to DPI analyze).

**Comment by MurzNN** [comment]
Woow! Seems 94.237.57.30 is unblocked!!! https://isitblockedinrussia.com/?host=turn.matrix.org
