### ISSUE TITLE
Omnibox search in Chrome is broken

### ISSUE THREAD

**Issue by nadonomy** [matrix-org/matrix.org#437]
![matrix org search](https://user-images.githubusercontent.com/4626865/58253955-96fd6780-7d61-11e9-91d6-596ded1134a3.gif)

It looks like my Chrome has cached the search query path from the old WordPress site:

<img width="688" alt="Screenshot 2019-05-23 at 13 33 16" src="https://user-images.githubusercontent.com/4626865/58253973-a4b2ed00-7d61-11e9-9e3b-be4c26f04136.png">

@jryans checked design.lyft.com as an example, and found they declare `<link rel="search" type="application/opensearchdescription+xml" title="Medium" href="/osd.xml" />`. 

We should try to fix this after figuring out [site wide search](https://www.gatsbyjs.org/docs/adding-search/) in the new site.

**Comment by benparsons** [comment]
fixed
