### ISSUE TITLE
Google listing paths/sections incorrectly

### ISSUE THREAD

**Issue by nadonomy** [matrix-org/matrix.org#438]
E.g. Searching for 'Matrix hosting' yields a result which is displayed as part of 'Contact' instead of 'Blog':

<img width="651" alt="Screenshot 2019-05-23 at 17 13 35" src="https://user-images.githubusercontent.com/4626865/58268899-3deffc80-7d7e-11e9-8862-60a7a18f6630.png">

**Comment by MadLittleMods** [comment]
Looks better nowadays:

![](https://user-images.githubusercontent.com/558581/129806008-a17a38ca-307b-4b4e-8d5e-282354ebae02.png)
