### ISSUE TITLE
Swagger appears to have gone haywire

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix.org#440]
https://matrix.org/docs/api/client-server/#!/Server32administration/getWellknown
Example has 'application/json' as a property

**Comment by afranke** [comment]
The viewer has changed in the meantime (#1081) and it will soon use a newer version of the spec which is not generated the same way. Things have changed, and I am going to guess this is not relevant anymore. Feel free to reopen if you can reproduce with the current setup.
