### ISSUE TITLE
Spec has no favicon

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix.org#455]

**Comment by MadLittleMods** [comment]
https://matrix.org/docs/spec/ still has not favicon.

[spec.matrix.org](https://spec.matrix.org/) now has something:

![](https://user-images.githubusercontent.com/558581/129810904-c0c33d87-3395-441d-9051-24d32fe463f4.png)

**Comment by turt2live** [comment]
I think this is invalid for this repo now, given the spec site falls within the matrix-doc domain now
