### ISSUE TITLE
RSS feed returning guides instead of blog posts

### ISSUE THREAD

**Issue by jerrykan** [matrix-org/matrix.org#459]
I just noticed in my feed aggregator today that a whole bunch of guides have popped up in the feed, but there is no sign of the announcement about Matrix 1.0

It might be just a case that lots of new guide entries have pushed the news items out of the feed (it only seems to return 10 items), but I'm only really interested in receiving news items via the RSS feed, so filtering out non-news items would be the preferred outcome from my perspective.

**Comment by jerrykan** [comment]
Further to this, it seems that no new blog items are being added to the RSS feed provided at https://matrix.org/blog/feed - The "This Week in Matrix 2019-06-14" is not included in the feed.

**Comment by benparsons** [comment]
This should be fixed now. @jerrykan thanks for bringing it up, please re-open if you see any issues.

**Comment by jerrykan** [comment]
Looks good @benparsons Thanks!
