### ISSUE TITLE
https://matrix.org/docs/projects/bridges/ is ugly and needs definitions

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix.org#461]
As per https://news.ycombinator.com/item?id=20161469, the current layout is hard to peruse (the alignment of the cells in the tables is wonky, plus it's unclear how the check/cross lists should be read), and the whitespace is a bit broken. We also need a clear summary of the different types of bridges, as per https://matrix.org/blog/2017/03/11/how-do-i-bridge-thee-let-me-count-the-ways

**Comment by benparsons** [comment]
This page is now less ugly and has some intro text with definitions. The whitespace is fixed and the content itself is read from the individual project markdown files.

It's still not beautiful, but that can be revisited. Also it now sits at https://matrix.org/bridges/ which looks a lot better. (redirects from the previous page)
