### ISSUE TITLE
Youtube embeds can overflow the blog template

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix.org#464]
as per https://matrix.org/blog/2019/03/12/breaking-the-100-bps-barrier-with-matrix-meshsim-coap-proxy

**Comment by MadLittleMods** [comment]
Looks okay nowadays:

![](https://user-images.githubusercontent.com/558581/129806185-7c6633f5-0e2b-4b90-ad5f-ed098035357e.png)

![](https://user-images.githubusercontent.com/558581/129806190-940fc25f-666e-4f80-9114-e7c60e7bf8ba.png)
