### ISSUE TITLE
Many instances of escaped apostrophes in E2E Encryption implementation guide

### ISSUE THREAD

**Issue by JoeThielen** [matrix-org/matrix.org#474]
https://matrix.org/docs/guides/end-to-end-encryption-implementation-guide

There are currently 35 instances of visibly escaped apostrophes (`\'`) in this guide.  

Also, I could not find the guide itself in this repo (nor matrix-doc) to submit the changes myself...?

**Comment by ara4n** [comment]
ugh, we've also broken the link (it should be at https://matrix.org/docs/guides/e2e_implementation.html) and much of the formatting in general has gone missing :/

The file lives in https://github.com/matrix-org/matrix.org/tree/master/gatsby/content/docs/2016-10-18-e2e_implementation.mdx

**Comment by benparsons** [comment]
I'm setting up redirects for pages like this right now (some pages now have redirects configured), I'll check the formatting out, it was one of the few pages migrated from reStructuredText

**Comment by JoeThielen** [comment]
This page also has four instances of markdown-style web links instead of HTML links.

**Comment by Half-Shot** [comment]
I don't see any instances of this anymore, so closing.
