### ISSUE TITLE
Add ability to link specific section of Privacy Notice

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix.org#475]
https://matrix.to/#/!WGRPyrAYebnQHlImWP:matrix.org/$1560417444217zFKdZ:lant.uk?via=matrix.org&via=raim.ist&via=utzutzutz.net

**Comment by benparsons** [comment]
this already exists: https://matrix.org/legal/privacy-notice#integration-services-bots-and-widgets

I wonder if we should make all headers self-links?

**Comment by aaronraimist** [comment]
Yes
