### ISSUE TITLE
Olm and Megolm specifications 404

### ISSUE THREAD

**Issue by jimmycuadra** [matrix-org/matrix.org#478]
Links related to Olm and Megolm in the client-server spec at https://matrix.org/docs/spec/client_server/r0.5.0 return 404 Not Found (or redirect to a URL that does):

* https://matrix.org/git/olm/about/docs/signing.rst
* https://matrix.org/docs/spec/olm.html
* http://matrix.org/docs/spec/megolm.html

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix.org/commit/0d56e76b811e966f094305a82a5012d935b0c09c was supposed to fix this :/

**Comment by aaronraimist** [comment]
May have been broken by the change to strip .html from the end of URLs.

Maybe changing those to look like 
```
Redirect /docs/olm_signing https://gitlab.matrix.org/matrix-org/olm/blob/master/docs/signing.md
```
would fix it

**Comment by turt2live** [comment]
Latter two are fixed by https://github.com/matrix-org/matrix.org/commit/a7b2f71d8d26ebafe130639efaa2cbaf36410609

First one is just a spec error: https://github.com/matrix-org/matrix-doc/pull/2133

(thanks for the tip @aaronraimist!)
