### ISSUE TITLE
Website should not keep all versions on disk forever

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/matrix.org#483]
This is related to : 

https://github.com/matrix-org/buildkite-webhook-listener/issues/1

but we also need to consider which versions to keep for the website, and what roll forwards/roll back looks like.

**Comment by benparsons** [comment]
@michaelkaye is this still a problem? what actions do we need to take if so? do we need to ask @richvdh ?

**Comment by richvdh** [comment]
hello. Yes I believe we still keep old versions on the disk until they are manually cleaned out; we should somehow automate their clearance. It's unclear to me if that is better done by the deployment script (see https://github.com/matrix-org/buildkite-webhook-listener/issues/1) or a separate cronjob.

**Comment by michaelkaye** [comment]
This has been done now, and disk space is more stable
