### ISSUE TITLE
Plemora instance for matrix.org and NV

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix.org#504]
https://pleroma.social/

**Comment by uhoreg** [comment]
Any reason for preferring pleroma over some other fediverse software, such as Mastodon (which matrix.org already has, and "just" needs to be resurrected)?  Of course, aside from the fact that pleroma is written in Elixir, and therefore must be awesome.

**Comment by turt2live** [comment]
Was suggested by the community: https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$156177657232KOluG:legit.solid.moe?via=matrix.org&via=half-shot.uk&via=privacytools.io

**Comment by afranke** [comment]
Whether matrix.org uses mastodon or Pleroma or something else shouldn’t have any impact on people on the outside wanting to subscribe. People can use Pleroma on their side and subscribe to mastodon accounts.

https://mastodon.matrix.org/@matrix exists and is actively used. Closing as there isn’t nothing more to do.
