### ISSUE TITLE
Add Ruby Olm to TMN

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix.org#531]

**Comment by 14mRh4X0r** [comment]
Currently, the [gem on RubyGems](https://rubygems.org/gems/ruby_olm) is owned by @cjhdev, while [my fork](https://github.com/14mRh4X0r/ruby_olm) is the most up-to-date with Olm itself, so using it is not straightforward.

**Comment by aaronraimist** [comment]
Are you not going to submit your changes as a pull request?

**Comment by 14mRh4X0r** [comment]
I thought I already had, but apparently I hadn't… huh. Should probably do that.

**Comment by cjhdev** [comment]
> Currently, the [gem on RubyGems](https://rubygems.org/gems/ruby_olm) is owned by @cjhdev, while [my fork](https://github.com/14mRh4X0r/ruby_olm) is the most up-to-date with Olm itself, so using it is not straightforward.

Hey, nice work with your fork.

The original ruby_olm builds from source packaged with the gem. It doesn't require libolm to be installed on the system. This is what I wanted for various reasons.

Your fork requires libolm to be installed on the system. If I accept your changes then I will lose the build from source behavior. I think we should use different names.

**Comment by benparsons** [comment]
These can both be included on Matrix.org/TMN, but I have the idea that they should be considered two separate projects - @14mRh4X0r can you confirm that?

**Comment by thibaultamartin** [comment]
The project has not been updated since 2019
