### ISSUE TITLE
remove the Lua weechat script entirely from try matrix now

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix.org#537]
there continues to be mass confusion about the two weechat scripts, especially as the Lua one doesn't say anywhere to use the Python one instead, and the description of the lua one is more positive than the python one

**Comment by poljar** [comment]
Small correction, the Lua one does mention the Python one [here](https://github.com/torhve/weechat-matrix-protocol-script/#project-status-and-alternative-client).
