### ISSUE TITLE
The top bar is easily missed

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix.org#540]
I went from the homepage to develop, looking for the spec. I ended up skipping over the 4 buttons and started reading about guides.

**Comment by benparsons** [comment]
The top nav has been reorganised quite a bit since this issue was opened, feels a lot more organised now. @turt2live can you comment if this is still a concern.

**Comment by turt2live** [comment]
I still feel it's easily missed. The site is a bunch of grey on grey, which makes it visually hard to see.

**Comment by MadLittleMods** [comment]
> The current `Try Now` button in the main navigation has been invisible to me this whole time. I looked at that [PR](https://github.com/matrix-org/matrix.org/pull/924) and had to visually scan the page 3 times before I saw it. Just anecdotal and perhaps this was because when I tried `Try Now` in the main navigation didn't get me to where I wanted.
> 
> I have been always having to go to **Discover** -> **Try Matrix** in the sub-navigation. But this is just insider knowledge that took me a while to figure out I needed when reviewing all of the new Matrix clients people are adding in the PR reviews. 
> 
> *-- @MadLittleMods, https://github.com/matrix-org/matrix.org/issues/1027#issuecomment-896130095*

**Comment by thibaultamartin** [comment]
I believe the new website makes those navigation problems obsolete
