### ISSUE TITLE
Link to perspectives-project.org in FAQ is dead

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix.org#55]
maybe link to https://addons.mozilla.org/en-US/firefox/addon/perspectives/ or https://en.wikipedia.org/wiki/Convergence_(SSL) instead

**Comment by uhoreg** [comment]
or http://web.archive.org/web/20170702024706/https://perspectives-project.org/

**Comment by richvdh** [comment]
The server-server spec links to archive.org, so I've done the same here.

**Comment by netsafe** [comment]
Looks like the domain is hijacked?

**Comment by turt2live** [comment]
@netsafe I wouldn't say it's been hijacked, but the original perspectives-project.org domain doesn't show what it used to. The FAQ should be linking to an archived version of the page: https://web.archive.org/web/20170702024706/https://perspectives-project.org/

is this not what you're seeing?
