### ISSUE TITLE
Update the list of features at Clients Matrix

### ISSUE THREAD

**Issue by KitsuneRal** [matrix-org/matrix.org#561]
We have a few features that all clients support, so there's not much reason to keep them in the matrix:
- Room user list
- Show room description

At the same time, it would be great to add a few new features (subject to discussion):
- Reactions
- Message editing
- Room upgrades
- Localisations (number of languages if many)

**Comment by benparsons** [comment]
Added these suggestions. We can keep the feature list in mind - that page is already rather overloaded.
