### ISSUE TITLE
Missing link to website source repository for bug report and pull requests

### ISSUE THREAD

**Issue by Niluge-KiWi** [matrix-org/matrix.org#566]
I could not find any link to this github repo from the matrix.org website (and the github repo search did not help: `web`, `site`, `www` don't return the correct repo... only `website` does.)

A like in the footer would help a lot !

**Comment by julianschacher** [comment]
Regarding the discoverability of this repo in a search:
I think adding tags to it would help with that. At least in the GitHub organization-wide search, tags seem to have an effect.
