### ISSUE TITLE
GitHub link in footer doesn't work unless you open in new tab

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix.org#571]
![Screen Shot 2019-09-12 at 1 02 07 PM](https://user-images.githubusercontent.com/5855073/64808793-874a9e80-d55d-11e9-924f-3b62a4b2814e.png)
Clicking this GitHub icon (which links to matrix.org/code) doesn't do anything unless I CMD click it (open link in new tab).

**Comment by shivam1192** [comment]
fixed it. Review @aaronraimist
