### ISSUE TITLE
all the 'Try out the fiddle' links on https://matrix.org/docs/guides/client-server.html have died

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix.org#58]
thanks to philipp for pointing it out in https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$15110239485NWgri:xndr.de.  They probably broke when splitting off non-spec stuff from matrix-org/matrix-doc.

**Comment by richvdh** [comment]
bother

**Comment by richvdh** [comment]
they seem to have started working at some point
