### ISSUE TITLE
Deprioritize matrix.org python sdk on sdks page

### ISSUE THREAD

**Issue by non-Jedi** [matrix-org/matrix.org#590]
Couldn't figure out where the [sdks page](https://matrix.org/docs/projects/sdks/) could be edited. Since the matrix.org python sdk is not under active development and matrix-nio is while already being more featureful, it would be great if the python sdk could be shown further down the page than matrix-nio or maybe even removed entirely.

**Comment by benparsons** [comment]
This is a broader task that should have an improved top-of-page with our recommended SDKS.
