### ISSUE TITLE
Need a search button on the blog posts page

### ISSUE THREAD

**Issue by AmandineLP** [matrix-org/matrix.org#610]
so one doesn't have to go through the whole list to find what one is looking for

**Comment by benparsons** [comment]
IMO the most reliable solution to this would be to embed a DDG search box, is that considered ok? https://duckduckgo.com/search_box

**Comment by aaronraimist** [comment]
"with DDG" is kinda annoying. I think it would be better if it just said "Search". It also searches all of matrix.org, not just the blog.
