### ISSUE TITLE
would be good to have the blogs sorted by categories

### ISSUE THREAD

**Issue by AmandineLP** [matrix-org/matrix.org#611]

**Comment by benparsons** [comment]
There are categories, eg you can see all TWIM at https://matrix.org/blog/category/this-week-in-matrix/

Should we make the categories list (https://matrix.org/blog/categories/) more prominent? Right now it's just a dump of categories on the site

**Comment by shivam1192** [comment]
I think Blog management is little bit messy in matrix.org. I think there is a need to handle it.
