### ISSUE TITLE
h7 in spec has no background colour

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix.org#619]
e.g. https://matrix.org/docs/spec/client_server/r0.6.0#stripping-the-fallback .  Also, eww at having `h7`

**Comment by slondr** [comment]
`<h7>` isn't even a defined HTML tag. What's it doing in there?

**Comment by turt2live** [comment]
That's almost worse :( 

We should probably fix the levels because 7 is just... no.

**Comment by afranke** [comment]
The new spec website doesn’t seem to go below h3, and is legible. Closing as obsolete.
