### ISSUE TITLE
Make the outdated spec warning float at the top of the page

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix.org#622]
The outdated spec warning should scroll with the page so it is harder to miss if you just click a link deep in the spec and didn't start reading at the top.

> I googled for the specs, clicked the link and used Firefox's search function before even looking at the screen.

**Comment by thibaultamartin** [comment]
![image](https://github.com/matrix-org/matrix.org/assets/1688309/2d4f9f0c-8541-4d12-8c10-89281a4d1131)

This seems to be fixed

**Comment by aaronraimist** [comment]
@thibaultamartin No it is not. Not sure whether this is the appropriate repository for this issue anymore though.

The idea of the issue is when you click a link like https://spec.matrix.org/v1.1/client-server-api/#using-access-tokens. It is not obvious that you are on an old version of the spec unless you were to scroll all the way to the top of the page.

**Comment by thibaultamartin** [comment]
Oooh, emphasis on float, right! Thanks, I'm reopening it (and will move it to the right repo)
