### ISSUE TITLE
FAQ: Broken link to Which matrix clients support E2E?

### ISSUE THREAD

**Issue by steef435** [matrix-org/matrix.org#624]
Small bug: in the faq there's a link to `https://matrix.org/faq/#which-matrix-clients-support-e2e%3F`, while the ID of that section is `which-matrix-clients-support-e2e` (without the %3F). I suspect it was introduced in [this commit](https://github.com/matrix-org/matrix.org/commit/190ad8548e45059a26f6bc0c7ced1f40ef2e1aa0#diff-654744295a5adfdda7722a54be0bb4c2). I would just fix the link and pull but I'm not sure whether you would rather make gatsby not ignore the `?` in the titles instead.

I did a quick search of the HTML-file and there don't seem to be more links to ids with now missing `%3F`s.

**Comment by benparsons** [comment]
easiest to just fix the link
