### ISSUE TITLE
FAQ: no header autlinks for headers in mdx files

### ISSUE THREAD

**Issue by steef435** [matrix-org/matrix.org#625]
The headers imported from mdx-files in [faq.js](https://github.com/matrix-org/matrix.org/blob/master/gatsby/src/pages/faq.js) do not get the blue "header autolinks".

Picture since I don't know the proper name (notice the middle header):
![image](https://user-images.githubusercontent.com/1906214/71786007-dc2b8c80-3006-11ea-93dd-7d3d81f48575.png)

Related: #575 (gatsby-remark-autolink-headers is already being used if I read the config correctly though).

**Comment by benparsons** [comment]
fixed, good reminder thanks Steef
