### ISSUE TITLE
Riot.im Cookie Policy should be updated to mention other Cloudflare cookies

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix.org#633]
`cf_use_ob` and `cf_ob_info`

**Comment by aaronraimist** [comment]
Feel free to move this to https://github.com/vector-im/policies/issues, apparently that is a repo that exists

**Comment by turt2live** [comment]
Can't move across orgs, but here is fine for now I think.

**Comment by benparsons** [comment]
cc @lampholder

**Comment by deniseal** [comment]
element.io cookie policy has been updated to reflect changes to cloudflare cookies as per https://github.com/vector-im/policies/issues/24
