### ISSUE TITLE
SDK page is all messed up

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix.org#639]
<img width="1197" alt="Screen Shot 2020-01-29 at 2 01 03 PM" src="https://user-images.githubusercontent.com/5855073/73392620-ca54a680-429f-11ea-9255-b4cb93d1394f.png">

It says gomatrix with a Rust logo, Glitch in the Matrix for the iOS SDK, matrix-python has a go logo... etc

**Comment by benparsons** [comment]
Fixed, thanks for pointing this one out - it does not occur locally for me.
