### ISSUE TITLE
Incorporate Synapse docs on matrix.org

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix.org#642]
https://github.com/matrix-org/synapse/blob/master/docs/ is thorough and maintained - we should link to this from matrix.org.

**Comment by afranke** [comment]
matrix.org → Discover → Synapse installation → “can be found in the Synapse [documentation](https://matrix-org.github.io/synapse/latest)”

Seems it was fixed in the meantime. Feel free to reopen if you had something more in mind.
