### ISSUE TITLE
We don't mention that #matrix:matrix.org exists on the site.

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix.org#651]

**Comment by benparsons** [comment]
This is mentioned on https://matrix.org/clients/ and https://matrix.org/docs/projects/try-matrix-now - do you think it should be on the homepage?

**Comment by turt2live** [comment]
Yea, or somewhere more prominent. Had an awkward encounter where someone didn't know what the alias was, and it wasn't the first time

**Comment by thibaultamartin** [comment]
I feel strongly about _not_ routing newcomers to #matrix:matrix.org

At the bottom of https://matrix.org/docs/chat_basics/public-rooms/#spaces we now link to public spaces where people can find fun rooms and start interacting with them
