### ISSUE TITLE
Clicking the "Spec" link on https://matrix.org/discover does not work

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix.org#655]
Please can we just turn off the dead-link trapper thing, given it seems to mainly break things?

**Comment by SuperSandro2000** [comment]
Yes, please. This feels so wrong cause you think your browser is broken.

also the link is not dead. It 301 from https://matrix.org/docs/spec to https://matrix.org/docs/spec/

**Comment by benparsons** [comment]
This is solved. Rather than turning off the 404 behaviour, I added a custom page (which is useful anyway), and we now detect links to the only area of the site untracked by Gatsby, which is /doc/spec/*

Waiting for a re-deploy before closing.

**Comment by aaronraimist** [comment]
Now I see the 404 page for a split second and then it redirects to the spec

**Comment by benparsons** [comment]
This should now be fixed for good. By keep allowing Gatsby to handle links (including the dead-link trapper,) we get very fast page switching. The need was only to override links that are not known by Gatsby.
