### ISSUE TITLE
Rework "Try Matrix"

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix.org#665]
https://matrix.org/try-now is less featureful than https://xmpp.org/getting-started/ for example.

**Comment by thibaultamartin** [comment]
## Goals of the page

- Everyday people should be able to quickly get started using Matrix. They should be able to pick a recommended client and create an account (most probably on matrix.org for the sake of simplicity)
- Community managers should be able to quickly pick a recommended client, create an account, and join existing open communities that thrive on Matrix (ideally not exclusively tech-focused communities) to see how it looks like
- Developers are not the primary target of this page. They should be routed to the documentation to learn more about the technical aspect of Matrix
- Entrepreneurs should be convinced that Matrix is mature, robust, and interoperable enough to allow them to use it as a Foundation for their products.

Everyday people and community managers are the primary targets for this page. They need not to be overwhelmed by the information meant for developers and entrepreneurs.

## Content

TBD
