### ISSUE TITLE
Weird formatting in Olm security assessment blog post

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix.org#669]
https://matrix.org/blog/2016/11/21/matrixs-olm-end-to-end-encryption-security-assessment-released-and-implemented-cross-platform-on-riot-at-last

**Comment by aaronraimist** [comment]
Part of https://github.com/matrix-org/matrix.org/issues/392

**Comment by benparsons** [comment]
@aaronraimist I believe this is fixed, there may be other cases and we can re-open if needed, thanks for highlighting
