### ISSUE TITLE
Some projects have incorrect capitalization of their language data

### ISSUE THREAD

**Issue by aaronaxvig** [matrix-org/matrix.org#671]
For example, gatsby/content/projects/2020-01-18-mx-puppet-discord.mdx has the language as ``Typescript`` when it should be ``TypeScript``.  This makes both variations show up in the picker on https://matrix.org/docs/projects/try-matrix-now

**Comment by aaronaxvig** [comment]
I'm currently working on fixing the offending project files, just wanted to have an issue to reference with a description of the issue.

**Comment by benparsons** [comment]
@aaronaxvig good find, thanks for looking into this

**Comment by jaller94** [comment]
Project with this issue: https://github.com/matrix-org/matrix.org/blob/bf05308e60eba659dc83608e320528d1fc012f66/gatsby/content/projects/clients/quadrix.mdx

**Comment by jaller94** [comment]
This causes languages to be separate filters on https://matrix.org/docs/projects/try-matrix-now/

![Screenshot 2022-08-22 at 08-37-01 Matrix org](https://user-images.githubusercontent.com/10872136/185854958-43fb448f-5ad8-444e-9943-62e55e70deb1.png)

An automatic check on CI would be preferable to prevent this issue from coming back in the future.
