### ISSUE TITLE
replace link to hello-matrix list in FAQ with the-federation and others

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/matrix.org#673]
https://matrix.org/faq#how-do-i-get-an-account-and-get-started%3F links to the hello-matrix list, which is no longer maintained.  Maybe replace it with a link to https://the-federation.info/protocol/matrix and/or other lists of servers

**Comment by aaronraimist** [comment]
the-federation.info isn't really a replacement. It just lists all the servers it can see, as far as I know no one has signed up to include their server in that list. Most are not open for public registration and those that do have registration open may not want to be included in a list.

https://www.anchel.nl/matrix-publiclist/ is a better alternative

**Comment by aaronaxvig** [comment]
the-federation.info has an "Open signups" column which can be used to find servers with open registration.

The bottom of the hello-matrix.net claims that it was updated today.

My pull request will incorporate all three.

**Comment by aaronraimist** [comment]
> the-federation.info has an "Open signups" column which can be used to find servers with open registration.

Yes but my point is that no servers signed up to be on that list. They may have open signups but that does not mean they *want* to be included in a list. Synapse doesn't have great systems for controlling registration. Either is is open or it is closed. There is no way to whitelist registrations to specific email domains or require a secret password to register without using third party tools like https://github.com/ZerataX/matrix-registration. Some people may have registration enabled so their friends can register but not want random people to register. Whatever list is promoted on matrix.org should ensure that it is actually showing people homeservers that are willing and able to accept a large number of users joining their server.

> The bottom of the hello-matrix.net claims that it was updated today.

The timestamp at the bottom of hello-matrix.net is just the automated script running which pings all of the servers to see if they are online. The author of hello-matrix.net has not been around for months.

**Comment by aaronaxvig** [comment]
OK I altered my pull request.

**Comment by benparsons** [comment]
Closed by #678
