### ISSUE TITLE
Dead link on the Rocket.Chat.Federation page

### ISSUE THREAD

**Issue by KitsuneRal** [matrix-org/matrix.org#69]
https://matrix.org/docs/projects/as/rocket-chat-federation.html has a dead link to GitHub; it should rather link to https://github.com/RocketChat/hubot-freddie, I assume.

**Comment by aaronraimist** [comment]
Fixed by https://github.com/matrix-org/matrix.org/commit/d472f9141cd98ce5047993af1abd5780eea5ce43#diff-a9edf2179ee73fc54a862ab4b5d9f82c
