### ISSUE TITLE
Authenticate from external service or database

### ISSUE THREAD

**Issue by integrics** [matrix-org/matrix.org#690]
We're looking to add a modern chat service to Enswitch to replace our existing XMPP server, and are considering Matrix. Enswitch is a large, complex softswitch for hosted telephony services, and is used by telephone companies around the world with systems up to hundreds of thousands of users. It stores user configuration in a replicated MySQL database. One of the tables in this database is users, storing (among many other things) usernames and hashed passwords for the web interface. Is it possible to have Synapse authenticate from this table, or from some sort of radius/web service that we can write that provides an interface to this table?

**Comment by t3chguy** [comment]
Something like https://github.com/kamax-matrix/matrix-synapse-rest-password-provider may help you. For future synapse *issues* please use https://github.com/matrix-org/synapse - for future synapse *queries* please use https://matrix.to/#/#synapse:matrix.org
