### ISSUE TITLE
Update number of localizations for clients matrix

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix.org#702]
Now that they show up (https://github.com/matrix-org/matrix.org/issues/682), the numbers should get updated. Every client should have 1 rather than an X. Riot certainly is translated into more than 10 languages, I know Nio has 2, etc.

**Comment by thibaultamartin** [comment]
The number of translations is not displayed anymore on the new website (on purpose, to avoid outdated information or heavy maintenance). We now only display whether a client has translations or not
