### ISSUE TITLE
Explain the differences between similar components of Matrix.org and IPFS/libp2p in the FAQ or other section in the home page

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix.org#71]
Moved from https://github.com/matrix-org/matrix-doc/issues/796

**Comment by richvdh** [comment]
Pull requests to improve the faq are welcome; the source is https://github.com/matrix-org/matrix.org/blob/master/jekyll/_posts/guides/2015-08-19-faq.md ;)

**Comment by ShadowJonathan** [comment]
@richvdh the source is outdated now, can you point to the new place where this is being said in the docs?

**Comment by richvdh** [comment]
@benpa is the source of the faq now https://github.com/matrix-org/matrix.org/blob/6a9610bc0aadfb3f6f92103f80b6e44d4cc4609d/gatsby/src/pages/faq.js ? or is that generated somehow?

(this issue may no longer be relevant: it's 3.5 years old and the world has moved on)

**Comment by thibaultamartin** [comment]
Closing as obsolete
