### ISSUE TITLE
Download of site after build is slow

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/matrix.org#737]
Current build times: 7min for the site generation, ~30s to get the webhook there, then ~18-20min to download the site.

 - can we reduce the file size?
 - are we being rate limited somewhere?

**Comment by benparsons** [comment]
Looking at the output from buildkite, the largest artifact is the gatsby output, at 150mb. ~40mb of this is PDFs that could be moved to a static location, the rest is dynamic output it would be better to keep together.

Overall it feels like 150mb of output shouldn't take so long to download.
