### ISSUE TITLE
Convert ramblings of versions in the spec to a guide or something

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix.org#739]
https://matrix.to/#/!NasysSDfxKxZBzJJoE:matrix.org/$4SQN-eqZFa6hA-_R3CdDO4wfyP-u3W1vFGWEngHQAQ0?via=matrix.org&via=amorgan.xyz&via=pixie.town

**Comment by richvdh** [comment]
This issue seems to be lacking context.
