### ISSUE TITLE
OTWSU page is not mobile-friendly

### ISSUE THREAD

**Issue by ludwigbald** [matrix-org/matrix.org#742]
The page ends up being wider than the phone screen, https://matrix.org/open-tech-will-save-us/

**Comment by MadLittleMods** [comment]
This looks fine nowadays on mobile (also tested with Chrome for Android on Pixel 4A):

![](https://user-images.githubusercontent.com/558581/129811135-3de6992d-a0b0-450d-a6c6-e31e9b3837b0.png)
