### ISSUE TITLE
"Try Matrix"-page can be improved

### ISSUE THREAD

**Issue by ludwigbald** [matrix-org/matrix.org#743]
It's not easy enough to get started.

**Comment by ludwigbald** [comment]
There are too many pages that are called "Try Matrix now". It's confusing.

**Comment by MadLittleMods** [comment]
Closing as https://github.com/matrix-org/matrix.org/pull/761 was merged.

Still lots of room for improvement on the Try Matrix pages but we can track it in separate issues.
