### ISSUE TITLE
Add a Dashboard that shows the state of Matrix

### ISSUE THREAD

**Issue by ludwigbald** [matrix-org/matrix.org#745]
Does such a unified dashboard exist already?

I'd like to see:
- Number of Homeservers
- Homeservers ranked by health (ping, availability...)
- Number of Globally visible accounts
- Number of messages sent per day
- Estimated energy and CO2 footprint of the Matrix ecosystem per day
- New Tweets and Toots about matrix

Any additional ideas?

**Comment by thibaultamartin** [comment]
We can only do this as seen from the matrix.org homeserver. Closing as a duplicate of #67 :)
