### ISSUE TITLE
Refactor UI: Support Matrix/Shop

### ISSUE THREAD

**Issue by ludwigbald** [matrix-org/matrix.org#746]
Instead of linking to a non-existing shop page in the top bar, let's link to an overview page on how to support Matrix.

That page would then include:
- Support Matrix by using it and convincing your friends and followers to use it
- Support Matrix with money (Liberapay, Patreon etc.)
- Run a homeserver
- Build on top of Matrix or contribute to existing projects

**Comment by thibaultamartin** [comment]
The page links to the shop atm, I believe this is what people expect when they click the shop button. Adding another page in-between will likely be confusing :)
