### ISSUE TITLE
Refactor UI: Home Page Spring cleaning

### ISSUE THREAD

**Issue by ludwigbald** [matrix-org/matrix.org#748]
There are so many elements on the home page that duplicate data from other pages.

This is quite confusing. Let's remove them!
Instead, let's give the home page its own reason to exist:
- For first-time visitors, explain the gist of Matrix and persuade them to use it.
- For returning visitors, make it easy to find the links they are looking for.

**Comment by thibaultamartin** [comment]
Made obsolete by the new website
