### ISSUE TITLE
Make text lines shorter

### ISSUE THREAD

**Issue by ludwigbald** [matrix-org/matrix.org#755]
We all can't stand spaghetti code for a reason.
Let's wrap lines at min(~80 characters, screen width) to make all pages easier to read and look more professional.

The *Foundation* page is a particularily bad example when viewed on a larger screen.

**Comment by MadLittleMods** [comment]
Can someone point to some examples nowadays? I am not seeing an code snippet/fence example on the foundation page: https://matrix.org/foundation/

Would be good to lint 😀

**Comment by thibaultamartin** [comment]
Pages now have a max-width :)
