### ISSUE TITLE
Contact page shouldn't direct people to HQ for abuse concerns

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix.org#757]

**Comment by benparsons** [comment]
I don't think it does? The current text:

> The best place to get information and connect is on Matrix itself - starting in Matrix HQ (#matrix:matrix.org).
> However, if you prefer email, or have a need to be more direct:
> 
>  *   abuse@matrix.org if you need to urgently report abuse on the platform
>  *   support@matrix.org for more general support and commercial queries
>  *   security@matrix.org to disclose security issues. Also see our Security Disclosure Policy

**Comment by turt2live** [comment]
ah, turns out the person this was opened on behalf of didn't read past the first line 🤦
