### ISSUE TITLE
Formatting issues with whitespace

### ISSUE THREAD

**Issue by jugglinmike** [matrix-org/matrix.org#769]
The markup in the docs currently expects newlines to be rendered as whitespace, as per HTML. [Here's an example from the English FAQ page](https://github.com/matrix-org/matrix.org/blob/aa25cb103af819540aef262ab68be4fc743de915/gatsby/src/pages/faq.js#L236-L238):

```html
<li>Nose around in the repositories in our
<a href="https://github.com/matrix-org">GitHub organization</a> and send us some pull requests
to fix some bugs or add some features!</li>
```

If this code were interpreted as HTML, then the newline between "our" and "GitHub" would be rendered with a single whitespace character. However, [JSX interprets whitespace differently than HTML](https://reactjs.org/docs/jsx-in-depth.html), and as a result, the two words are displayed without separation:

![Screenshot from 2020-06-17 13-00-38](https://user-images.githubusercontent.com/677252/84927389-c41e6580-b09a-11ea-9e12-e8c2b39db3e4.png)

This can be corrected by explicitly adding whitespace in JSX:

```diff
-<li>Nose around in the repositories in our
+<li>Nose around in the repositories in our{' '}
 <a href="https://github.com/matrix-org">GitHub organization</a> and send us some pull requests
 to fix some bugs or add some features!</li>
```

However, making this change manually is prone to omission and regression. The Prettier tool makes this change by default, but while [Prettier is already installed in this project](https://github.com/matrix-org/matrix.org/blob/aa25cb103af819540aef262ab68be4fc743de915/gatsby/package.json#L76), it [is not configured to run against JSX files](https://github.com/matrix-org/matrix.org/blob/aa25cb103af819540aef262ab68be4fc743de915/gatsby/package.json#L63). Its usage doesn't seem to be enforced at all.

Enabling it causes a very large amount of (ostensibly harmless) formatting changes, but the resulting diff is so large that I'm reluctant to submit it without speaking with the maintainers first.

Would you folks be open to enabling Prettier and accepting the resulting formatting changes?

**Comment by benparsons** [comment]
Hey @jugglinmike, this is a great suggestion, thank you. I just ran prettier manually and amusingly it didn't catch the exact example you gave, but I get the idea. In general I support enabling Prettier. I'll update package.json and update faq.js, but I'm going to defer (not forever) doing a site-wide run for now, as it produces 800 changed files to review. We can incrementally fix files per Prettier as they're edited, and keep this issue open until a site-wide run is performed.

**Comment by thibaultamartin** [comment]
Closing in favour of #1520 for the general posts cleanup
