### ISSUE TITLE
Specification is hard to read due to font-weight

### ISSUE THREAD

**Issue by arp242** [matrix-org/matrix.org#779]
https://matrix.org/docs/spec/ is pretty much unreadable on my system due to the thin grey text.

Default:

![screenshot_2020-07-03-22-56-48_border](https://user-images.githubusercontent.com/1032692/86482128-e7782e80-bd83-11ea-8940-b3442b636493.png)

With font-weight removed:

![screenshot_2020-07-03-22-57-15_border](https://user-images.githubusercontent.com/1032692/86482130-e8a95b80-bd83-11ea-9367-a38fa8553de3.png)

And also change the colour from `#666` to `#222`:

![screenshot_2020-07-03-23-23-07_border](https://user-images.githubusercontent.com/1032692/86482281-39b94f80-bd84-11ea-94f7-888925a9f86b.png)

Font reset to standard sans-serif:

![screenshot_2020-07-03-23-23-17_border](https://user-images.githubusercontent.com/1032692/86482286-3b831300-bd84-11ea-8901-68dffd9bd770.png)

---

This is all on Firefox/Linux. Maybe it renders different on macOS and Windows? IMHO setting it to the default font-weight and less grey colour (even at the default widths, Open Sans is a fairly thin font) would greatly improve readability.

**Comment by FredHappyface** [comment]
Just to second this. 

Fonts seem quite faded on edge 84 on windows too. I definitely think it would be worth setting the font weight to 400 and the colour to a very dark grey (something like #\111 perhaps?)

**Comment by Namanl2001** [comment]
Hey, can I take this issue and work on it?

**Comment by MadLittleMods** [comment]
Does https://spec.matrix.org/ look any better for you? I don't think more effort will be put into the old doc site with the new one in-flight.

**Comment by arp242** [comment]
Yes, that one is fine. If that's the new site to replace this then it's solved. Thank you.
