### ISSUE TITLE
Fixed header takes up a lot of space on the specification page

### ISSUE THREAD

**Issue by arp242** [matrix-org/matrix.org#780]
On https://matrix.org/docs/spec/ the fixed header is 71px; my usable screen size (full screen, minus UI chrome from Firefox) is 675px, this means that the header is more than 10% of my usable screen area.

Granted, my laptop's 1366x768 resolution is not very large, but it's not an uncommon resolution either (about 15% to 20% use a similar resolution, on my programming weblog anyway).

Since the header provides very little value in reading the spec (i.e. no navigation to anything *within* the spec) it might be a good idea to unfix it, or at least make it smaller.

[related comment](https://github.com/golang/go/issues/37110#issuecomment-645215229)

**Comment by afranke** [comment]
This section of the website has been replaced with the brand new [spec website](https://spec.matrix.org) and there is a redirect in place. Closing as this has become obsolete.
