### ISSUE TITLE
Reinstate matrix.org/vrdemo page

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix.org#83]

**Comment by benparsons** [comment]
Added to https://matrix.org/docs/projects/try-matrix-now.html.

Could do with more promotion.

**Comment by t3chguy** [comment]
matrix.org/vrdemo is no longer functional, so https://matrix.org/docs/projects/other/matrix-vr-demo should be updated to remove it

**Comment by benparsons** [comment]
matrix.org/vrdemo once again exists in a static form - we would need to redeploy the original assets and make some server updates to restore the functionality itself.

**Comment by thibaultamartin** [comment]
This seems to be obsolete, and it looks like Third Room could be a better showcase of Matrix in a VR headset.

Closing in favour of to elaborate more on how we should showcase thirdroom on the new m.org #1884
