### ISSUE TITLE
Very high CPU usage on the main page

### ISSUE THREAD

**Issue by dtelyukh** [matrix-org/matrix.org#837]
**Describe the bug**
It's taking about 250% of CPU. Probably, the problem in "little alice/bob/charlie" animation.

**Screenshots**
[From the Task Manager](https://prnt.sc/unx93v)

**Desktop (please complete the following information):**
 - OS: Manjaro 20.1 Mikah (Kernel: x86_64 Linux 5.4.64-1-MANJARO)
 - Browser: Brave 
 - Version 1.12.105 (Chromium: 84.0.4147.105)

**Comment by thibaultamartin** [comment]
This should be fixed with the new website :)
