### ISSUE TITLE
Link spacing on FAQ page

### ISSUE THREAD

**Issue by f0x52** [matrix-org/matrix.org#840]
while linking someone to https://matrix.org/faq/#what-is-the-difference-between-matrix-and-xmpp%3F I noticed there's no whitespace around links in the page, which doesn't read that nicely

(oh and the %3F in the section url is a bit ugly)

**Comment by afranke** [comment]
I don’t see any whitespace issue, must have been fixed since then. Feel free to reopen with a screenshot if you still think this is an issue.
