### ISSUE TITLE
Prev/Next buttons at the bottom of blog posts are broken

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix.org#844]
The prev/next buttons at the bottom of blog posts are leading to `https://blog/2020/...` instead of `https://matrix.org/blog/2020/...`.

The code is around here: https://github.com/matrix-org/matrix.org/blob/a9af0b9accf7402152c794c0daef2c79373e156c/gatsby/src/components/PrevNext.js#L35-L51

**Comment by RetroEdit** [comment]
It looks like the issue is that there are two forward slashes getting added to the beginning of these URLs instead of one.

**Comment by benparsons** [comment]
@RetroEdit indeed that commit was a hack that has since been fixed!
