### ISSUE TITLE
problems with several error messages: Unable to decrypt

### ISSUE THREAD

**Issue by lvoss99** [matrix-org/matrix.org#871]
Dear community, 

this is my first _post_, so please forgive me if I don't use every convention correctly.
I am using the element messenger and it is one specific group chat that I receive several different errors in about why I can't read the sent message. Such as the following

** Unable to decrypt: Error: OLM.BAD_MESSAGE_MAC **

** Unable to decrypt: Error: Duplicate message index, possible replay attack: vT4f4OJSyZmjlObOmIE/CsZRY+saT4RGKhxEXA8oeSw|O2onvM62pC1io6jQKm8Nc2UyFXcd4kOmOsBIoYtZ2ik|0 **

** Unable to decrypt: Error: Mismatched room_id for inbound group session (expected !XdAQbEbtBibsXlkixO:digipeg.de, was !hyzVdkvmOKXVoNHWLm:digipeg.de) **

I have already rebooted the server what seemed to have fixed at least the second error for a couple of days. But then it reoccured now on a daily basis. The errors occur on group participants that are using the firefox browser version of the element messenger.

Have you any recommendations what to do about these issues?
I would really appreciate your help, thanks.

L

**Comment by aaronraimist** [comment]
Issues with Element should be filed on the Element repository https://github.com/vector-im/element-web/issues

This repository is for the matrix.org website.
