### ISSUE TITLE
add https://gitdab.com/cadence/Carbon

### ISSUE THREAD

**Issue by benparsons** [matrix-org/matrix.org#872]

**Comment by afranke** [comment]
Their [README](https://gitdab.com/cadence/Carbon/commit/734506a300611ed95b29750e50d14e203892c36f) itself states it is abandoned. I don’t think we want to keep “legacy” software around, do we?

**Comment by MadLittleMods** [comment]
Seems like an interesting project. We can leave it as `maturity: Not actively maintained`

**Comment by thibaultamartin** [comment]
I'm closing it right now, I'll revisit closed issues about projects when we import obsolete projects on the new website eventually.
