### ISSUE TITLE
https://matrix.org/bridges/ Signal bridge is missing

### ISSUE THREAD

**Issue by Thorgrimson** [matrix-org/matrix.org#873]
on the clickable icons and in the list you cant click on signal.
maybe you could add https://github.com/tulir/mautrix-signal there? or remove signal from the list

**Comment by tobymurray** [comment]
Agreed - tried this on Firefox and Chromium on Ubuntu, the other anchors seem to work e.g. https://matrix.org/bridges/#mumble but for Signal it flashes up and then disappears.
