### ISSUE TITLE
Element website instructions seem wrong for Linux

### ISSUE THREAD

**Issue by konomikitten** [matrix-org/matrix.org#893]
If you go to https://element.io/get-started and click on the line "Also available on Linux" you'll get the install instructions for Element Eesktop on Debian based distros. One of the commands is:

`sudo wget -O /usr/share/keyrings/riot-im-archive-keyring.gpg https://packages.riot.im/debian/riot-im-archive-keyring.gpg`

I believe this command shouldn't be writing to `/usr/` but instead be writing to `/etc/`, here is what I believe to be the correct command:

`sudo wget -O /etc/apt/trusted.gpg.d//riot-im-archive-keyring.gpg https://packages.riot.im/debian/riot-im-archive-keyring.gpg`

I have tested this on my Debian Unstable install and it works fine.

**Comment by richvdh** [comment]
> `sudo wget -O /etc/apt/trusted.gpg.d//riot-im-archive-keyring.gpg https://packages.riot.im/debian/riot-im-archive-keyring.gpg`

installing keyrings in `/etc/apt/trusted.gpg.d/` means that key is then trusted to sign *any* package in *any* apt repository. It is therefore insecure. 

For some more background on this, see https://wiki.debian.org/DebianRepository/UseThirdParty and https://unix.stackexchange.com/a/463140/11281.
