### ISSUE TITLE
About video conferencing feature

### ISSUE THREAD

**Issue by Stolyassa** [matrix-org/matrix.org#906]
Hello, I appriciate your work. Free, secure, open source and distributed social media is absolutely necessary for the humanity.

This thread is actually a question. I couldn't find any wiki, if there is an answer I'm sorry.

In element.io website it say there is video conferencing functionality. How this functionality works in matrix.org? What is the person limit for video conferencing? Is it suitable for a real university class with 200 students?

Thank you for your time. Regards.

**Comment by afranke** [comment]
Hi.

The current situation is that one-to-one calls are handled natively by some Matrix clients, which include Element and Nheko, while calls with more than two participants (also called conferencing) go through Jitsi Meet. There’s just been [an announcement](https://matrix.org/blog/2021/07/23/this-week-in-matrix-2021-07-23#voip) that Element hired @robertlong to bring native conferencing to Matrix, so in the future it is likely that Jitsi will be used less, if at all.

Now for your specific case, I would actually recommend having a look at [BigBlueButton (BBB)](https://bigbluebutton.org/). I’m a huge Matrix advocate, but I’ve used BBB for the past two years while teaching at a university and it is better suited for this. It handles large groups, is great for presentations and screensharing, and has a whiteboard.

And if your university uses Moodle, there is even integration between the two. This is currently an optional module, but [will become a standard feature for Moodle 4.0](https://moodle.com/news/moodle-4-0-toward-seamless-learning-environment/).
