### ISSUE TITLE
Matrix Logo use

### ISSUE THREAD

**Issue by alex1702** [matrix-org/matrix.org#91]
I want to ask if i can use your matrix logo in a steemit post.
The posting is about making a new Matrix-server for the steemit community and i think it looks better with a picture from your logo ;) 

Which license have the matrix logo?

**Comment by MTRNord** [comment]
Related: https://github.com/vector-im/logos/issues/1

**Comment by alex1702** [comment]
thanks

**Comment by ara4n** [comment]
as per HQ, go for it.
