### ISSUE TITLE
view.matrix.org needs a robots.txt that excludes room contents

### ISSUE THREAD

**Issue by ell1e** [matrix-org/matrix.org#910]
*retracted*

**Comment by t3chguy** [comment]
The intent of view.matrix.org is search engine indexability. That's why it uses 0 Javascript.

**Comment by ell1e** [comment]
I don't think at least in Europe you can legally just publicly index everything people say in a chatroom without informing them with a giant warning and possibly opt-in. So I would suggest that is conceptually a bad idea. Please note I am specifically referring to conversation contents being indexed here, **not** the room list or topics list, and **not** the ability to find a room via google and one-click reach the conversations. (Even though I find the latter also worth discussing as already hinted at above, but I find that to be a less immediately-dubious thing to do.)

I know the common argument is "but it's a public chatroom, there should be no expectation of privacy." This is like failing to miss the difference of a public marketplace vs being in a TV broadcast. Just because you're in public doesn't mean you expect to be recorded all the time with every single word you say as a *default* in such a widely broadcasted way that goes way beyond the public avenue you're seemingly in (which is the amount of people in the channel). Sure, people can carry on things and meme you as they could in public, but that's not the same as a constant live stream that is archived forever and *publicly indexed* with every single word.

So I think the intent of view.matrix.org is as a consequence a bad idea. I suggest not doing that.

**Comment by t3chguy** [comment]
By specifying `History` `Anyone` you are making it so that any unauthenticated user can use the Matrix API to retrieve the data. `view.matrix.org` does nothing that an API user (without just an automated guest API key which can be gotten with no vaidation by using register kind=guest) can do.

> and just to clarify further, I'm aware just about anyone could write a robot to join all chatrooms and extract al

They don't even need to join.

You can try it yourself using curl and jq:

```
curl "https://matrix.org/_matrix/client/r0/rooms/"'!OGEhHVWSdvArJzumhm:matrix.org'"/initialSync?access_token=$(curl "https://matrix.org/_matrix/client/r0/register?kind=guest" -s -XPOST -d "{}" | jq -r .access_token)" -s
```

Replace the Room ID (in single quotes) with any other room with History=Anyone.

Disabling view.matrix.org doing it just paints over the underlying possibilities at the cost of real discoverability for the network.

> I don't think at least in Europe you can legally just publicly index everything people say in a chatroom without informing them with a giant warning and possibly opt-in.

I don't believe there is a legal distinction between a public chatroom and a public forum, public forums are almost always indexed by google even in the EU.

**Comment by ell1e** [comment]
> I don't believe there is a legal distinction between a public chatroom and a public forum

The distinction comes from expectation really. It is not customary for almost any public chatroom to be indexed. As you point out, almost any public forum is publicly indexed.

>  it just paints over the underlying possibilities

Again, technical possibilities are not the same thing as legally and morally unproblematic.

I am familiar with this super pragmatic, defeatist technical view. All I am trying to say is that maybe this is not the only way to look at it, and therefore this open push for indexing might be quite unexpected for some. It certainly was for me. It is not the same thing to not technically prevent something, and to actively do it yourself. (In this vain, "how can any protocol protect" is also IMHO the wrong thing to remark.)

(Just a reminder: not a lawyer, so take everything I said with a bucket of salt.)

**Comment by t3chguy** [comment]
> Again, technical possibilities are not the same thing as legally and morally unproblematic.

Sure but just making it such that only nefarious users can access these indexes vs everyone for real discoverability would just give a fake sense of confidence/security?

> but I think what the user expects to be done with the data is often important for privacy and data protection laws.

Right, but matrix-static is not a data controller, it doesn't even store any data whatsoever, so it itself by translating the data available in JSON to HTML won't be breaking any such data protection laws.

**Comment by ell1e** [comment]
Why is that sense fake? There is some true, actual, higher sense of confidentiality if it is not publicly indexed. And just because someone else *could* do it doesn't mean it absolutely *will* happen. I think you're drawing some too pragmatic conclusions here.

**Comment by t3chguy** [comment]
> Why is that sense fake? There is some true, actual, higher sense of confidentiality if it is not publicly indexed. 

Because there will be other indexes going around, just not on Google, maybe dark net/whatever.

If you're simply objecting to matrix.org being both a Data Controller and also hosting this helpful tool for discovery of the network's rooms (by their content) then you should know that there are many other matrix-static instances which are allowing the indexing different public room subsets to engines like Google. 

If view.matrix.org's robots.txt changes, I bet someone else will host one (given how few resources it takes) without that robots.txt change and completely nullify this whole conversation.

**Comment by ell1e** [comment]
> Because there will be other indexes going around, just not on Google, maybe dark net/whatever.

The dark web also shares login data, still you can't just put it onto your own personal website legally. So I'm not sure I see a relevant point in this argument, personally.

> If view.matrix.org's robots.txt changes, I bet someone else will host one (given how few resources it takes) without that robots.txt change and completely nullify this whole conversation.

Or maybe not? Especially if matrix.org puts out a statement to tell people not to, I don't see that as a necessity. Also, if that statement existed people might have a way better position to tell others to stop if they do it, since now it actually goes against the express wishes of not only possibly the users, but also the technical data provider.

I think you completely putting technical possibility == **needs to necessarily happen** as the same thing is really not helpful, and afaik doesn't reflect law either. (On which I could be completely wrong, I'm not a lawyer.)

**Comment by ell1e** [comment]
Just to explain further, yes security by obscurity doesn't help much if it comes to passwords etc.

But if you ask me, when it just comes to broad general data the situation is much more of a gray area: especially when people might try to find dirt on you as a specific singled out target, having a higher cost associated with tracking down that data can make a real practical difference (in possibly somebody going into that giving up earlier). So I think if you look at this from a data protection angle, putting it into the google index does actually make a difference even though if *technically* you could still crawl matrix directly to get this. The difference is basically shouting into the world that the data relating to a specific nickname even is on matrix and a specific channel at that, removing one additional barrier from easily getting to it in a very targeted way. This barrier could in a specific case very well mean the difference of being actually stalked vs not being found by pure chance.

Now of course there is a valid point that others could just have it indexed to google, but here I think it is still relevant whether you actively encourage or discourage it as a home server admin. Both because in the law afaik intent matters if lawyers e.g. look at what you're encouraging or discouraging as a home server operator beyond the plain technical possibilities, and because practically it is a barrier to many people if there is a statement out there telling them not to do it. While that doesn't guarantee nobody will, it still changes the probabilities. (Again though, I am not a lawyer, so my guesses here could be completely wrong.)

I hope this discussion is of some value, I realize there is upsides and downsides to everything, and privacy isn't the only thing worth achieving in this world. But I honestly think pushing conversation data into the google index is ultimately not a good thing to do, all things considered.

**Comment by t3chguy** [comment]
> but also the technical data provider.

Matrix.org is just 1 data provider in the Matrix federation. Given that rooms are not owned by any one server, one could ask any of the many servers (1158 for Matrix HQ: https://view.matrix.org/room/!OGEhHVWSdvArJzumhm:matrix.org/servers ) for that same data and thus host a matrix-static against it.

> I don't see that as a necessity

Sure, I don't see it as a necessity, but if view.matrix.org disables it then all that will happen is my personal test instance will rank higher in search results and fill the gap.

> actively encourage or discourage it as a home server admin

The issue is as a Homeserver Admin it is not your say at all, as you don't own the rooms, they are decentralized units shared between the many servers which have at least a single user in that room. As a room admin it is your say, and actually even under your control, you can change the History visibility to not include people who have not yet joined the room which will include things like matrix-static.

**Comment by ell1e** [comment]
> Sure, I don't see it as a necessity, but if view.matrix.org disables it then all that will happen is my personal test instance will rank higher in search results and fill the gap.

Then just use a robots.txt there too? That the data is so highly shared IMHO just makes it more important to set a good example on where to not spill it, so I see that actually as a pretty good argument that what view.matrix.org does now is a quite damaging precedent.

As for the room admin argument: in the room admin UI nowhere does it say "guests can read history" is supposed to mean everybody is encouraged to push it into the google index. Conversely, if I put it to "members only (since they joined)" how is that going to stop anyone from having a bot join all channels and put all logs into the google index, too? So I feel like it is just your personal definition that the room history setting implies this. Now maybe that aligns up with the expectations of room admins, maybe it doesn't. If you feel like it should, maybe the room admin UI would need clarifications then. But I feel like the actual problem still is that view.matrix.org has no proper robots.txt. There is no need to set this "super-spreader" example with the data usage just because it is possible.

In any case, I am repeating myself.

To move this forward, I encourage that there is some sort of discussion or vote among whoever runs matrix.org, if that happens to be multiple people. But if this back and forth showed anything, than hopefully that neither of our views is obviously clear cut which means maybe it might be worth talking about this with more people than just two.
