### ISSUE TITLE
The faq webpage is not responsive for mobile view

### ISSUE THREAD

**Issue by 2580ayush2580** [matrix-org/matrix.org#914]
The website is not responsive at breakpoints Mobile S-320px and Mobile M-375px. It has some content that overflows on the x-axis as shown in the screenshot.

**To Reproduce**
1. Go to [faq page](https://matrix.org/faq/)
2. Click on Inspect Element
3. See an error

**Expected behavior**
The webpage should have a 100% width and no x-axis overflow.

**Screenshots**

![bug](https://user-images.githubusercontent.com/56980422/103445855-09a12980-4c9f-11eb-915e-c5dbe048fc81.png)
(![bug2](https://user-images.githubusercontent.com/56980422/103445935-c5625900-4c9f-11eb-8140-418752208ff4.png))

**Desktop:**
 - OS: Ubuntu 20.04.1 LTS
 - Browser : Chrome
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Smartphone :**
 - Device: VIVO 1726
 - OS: Android 8.1.0
 - Browser: Chrome
 - Version: 87.0.4280.101

**Comment by 2580ayush2580** [comment]
Shall I proceed to work on this?

**Comment by afranke** [comment]
> Shall I proceed to work on this?

Sure, if you can provide a PR that fixes it, that would be appreciated!

**Comment by MadLittleMods** [comment]
For reference on anyone wanting to fix this:

> I think we can just add `overflow-wrap: break-word;` to the whole [`.mxcontent`](https://github.com/matrix-org/matrix.org/blob/65e38713c5d6fe809d0f53033873ae1d6bfb90b0/gatsby/static/css/webflow-overrides.css#L300-L302) or `body` in the CSS.
> 
> It looks like it has enough browser support on its own as well, https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap#browser_compatibility
> 
> For reference, I see that it's used on GitHub and StackOverflow everywhere as well.
>
> *-- https://github.com/matrix-org/matrix.org/pull/916#discussion_r639321827*

**Comment by thibaultamartin** [comment]
Closing, since the FAQ has been deprecated and is only kept online for archive purposes
