### ISSUE TITLE
home page layout is mangled in Big Sur Safari on M1

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix.org#915]
<img width="1440" alt="D828C8C0-0C8E-4B7A-8657-32B6B4B5F113" src="https://user-images.githubusercontent.com/1294269/103489183-74bb3f00-4e0a-11eb-9384-40c976ec0f52.png">

**Comment by t3chguy** [comment]
Moved to https://github.com/vector-im/element.io/issues/9
