### ISSUE TITLE
Project card areas badly defined and hard to read on Try Matrix Now

### ISSUE THREAD

**Issue by domoritz** [matrix-org/matrix.org#925]
**Describe the bug**
At https://matrix.org/docs/projects/try-matrix-now, it's really difficult to see what caption belongs to which screenshot.

**Expected behavior**
The UI should use gray boxes like at https://matrix.org/clients/. 

**Screenshots**
<img width="1433" alt="Screen Shot 2021-01-09 at 10 50 50" src="https://user-images.githubusercontent.com/589034/104088678-e19a6300-5268-11eb-8cd4-85ade94f9756.png">

**Comment by prsndp** [comment]
Hey @domoritz,  I want to work on this UI issue.

**Comment by thibaultamartin** [comment]
Try Matrix on the upcoming website looks like

![image](https://user-images.githubusercontent.com/1688309/234932133-c8824677-a2cc-4667-ae53-6df59327d88d.png)

And it sends to the clients page, which now looks like

![image](https://user-images.githubusercontent.com/1688309/234932205-04d0ade0-27f6-4e9b-87de-d6af5e74a0bf.png)
