### ISSUE TITLE
Slack link on matrix.org is broken

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix.org#93]
" matrix.org front page links to /docs/projects/as/slackbridge.html instead of /docs/projects/as/matrix-appservice-slack.html?"

it should ideally link to a slack-inviter for matrixdotorg.slack.com

**Comment by aaronraimist** [comment]
@benparsons can you generate a slack link?
![screen shot 2018-10-28 at 2 31 52 pm](https://user-images.githubusercontent.com/5855073/47620920-49b46280-dabe-11e8-9e7d-e3cc43281cd2.png)

**Comment by benparsons** [comment]
Personally I'm not even on matrixdotorg.slack.com. @richvdh do you know if that's still an expected activation channel? If not, I'll just point the link to the newly updated /docs/projects/as/matrix-appservice-slack.html

**Comment by ara4n** [comment]
my rationale was that to show off bridging by saying "if you really want to use matrix HQ via slack, you can. here's the invite link".

**Comment by benparsons** [comment]
I don't think that would be a very good experience for a new user, as right now you'd only ever be able to view HQ. Might be better to just link to the newly improved Slack bridge itself.

**Comment by aaronraimist** [comment]
You think it would be better to link to a slack bridge that you have to setup yourself vs a link where you can click to just start talking? A person who has just heard of Matrix is probably not going to go through the trouble of setting up a homeserver and bridge themselves just to try it out.

Ideally for me those links to IRC, Slack, and Gitter would allow you to just jump in and start chatting **ASAP** without any setup (other than an account).

Once a new user sees "Oh yeah this matrix thing is kind of cool, I can just jump in from IRC or Slack or one of the native matrix clients" then they can dig in to setting up a homeserver and bridge.

**Comment by benparsons** [comment]
I'm not proposing that as a starting point, just saying that joining a Slack bridge with only HQ running is not amazing either.

Right now I'm trying to find out the admin of that Slack instance so we can update it to point to new HQ and create an invite page.

**Comment by benparsons** [comment]
this is obsolete
