### ISSUE TITLE
Add SchildiChat

### ISSUE THREAD

**Issue by vachan-maker** [matrix-org/matrix.org#932]
Please include Schildi Chat, a fork of Element in https://matrix.org/clients
Schildi Chat is available on Android, Desktop and Web.
Official Website: https://schildi.chat
Official Website: https://github.com/SchildiChat

**Comment by vachan-maker** [comment]
@benparsons any update on this

**Comment by TR-SLimey** [comment]
I'm afraid you'll probably have to do it yourself by submitting a pull request.

**Comment by vachan-maker** [comment]
@TR-SLimey Can you tell me briefly on how to do it?

**Comment by TR-SLimey** [comment]
@vachan-maker sure!

There's a step-by-step description in the README under the [How to add your project to Try Matrix Now](https://github.com/matrix-org/matrix.org/#how-to-add-your-project-to-try-matrix-now) section so you should be able to follow that.

Essentially, what it boils down to is:
- Fork this repo
- Git clone the forked repository onto your computer
- Checkout a new branch, for example, `git checkout -b add-schildi`
- Add the necessary files*, like the images and description, to the fork
- Open a pull request to the master branch of this repo with the changes you made

\* - The files needed are described in the section of the README I've linked, or if you prefer an example, I just opened a pull request to add Syphon yesterday, so you can use that as a reference :D Here it is: #961
