### ISSUE TITLE
Add matrix-appservice-bridge to the SDK page

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/matrix.org#935]
Add [`matrix-appservice-bridge`](https://github.com/matrix-org/matrix-appservice-bridge) to the SDK page, https://matrix.org/sdks/

**Comment by afranke** [comment]
Duplicate of #862?

**Comment by MadLittleMods** [comment]
Good find @afranke, I've created https://github.com/matrix-org/matrix.org/pull/1030 to fix the issue overall 👍
