### ISSUE TITLE
Add messages to favorites

### ISSUE THREAD

**Issue by lukaszpolowczyk** [matrix-org/matrix.org#939]
I need a feature:
Add the selected message to "Favorites".
Later I want to view my "favorite" messages in one place.

These are the things I want to refer to later or I need something else.

Currently, I can only add a link to the message to the bookmark in the web browser.
I can't do this in the app.

This feature exists at slack.com.

**Comment by benparsons** [comment]
This is the repository for the matrix.org website, but importantly it sounds like this is a product feature rather than something for the protocol. Since I can't transfer to other orgs, I will close this issue and suggest you open a new issue on https://github.com/vector-im/element-web

**Comment by lukaszpolowczyk** [comment]
Ok. I just had a problem choosing the right repository.

Relevant subject:
https://github.com/vector-im/element-web/issues/16331
