### ISSUE TITLE
Debian repository signing key has expired

### ISSUE THREAD

**Issue by hho** [matrix-org/matrix.org#973]
**Describe the bug**
The GPG key used for signing the Debian repository on https://packages.matrix.org/debian/ has expired. It's no longer possible to `apt update` from that repository.

**To Reproduce**
1. Add https://packages.matrix.org/debian/ to apt's package sources
2. Add the keyring from https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg to `apt-key add`
3. `apt update` fails with

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packages.matrix.org/debian buster InRelease: The following signatures were invalid: EXPKEYSIG F473DD4473365DE1 matrix.org packages <packages@matrix.org>
W: Failed to fetch https://packages.matrix.org/debian/dists/buster/InRelease  The following signatures were invalid: EXPKEYSIG F473DD4473365DE1 matrix.org packages <packages@matrix.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Expected behavior**
apt updates its local package cache.

**Server**
OS: Debian 10 (Buster)

**Comment by turt2live** [comment]
We just fixed this - you'll have to reacquire the key and try again.

**Comment by richvdh** [comment]
related: https://github.com/vector-im/element-web/issues/16960

**Comment by hho** [comment]
@rg-artcom: There was an update to the `matrix-org-archive-keyring` package last month (1.2 to 1.3), which contains the renewed keys. Worked flawlessly for me.

**Comment by gigawhitlocks** [comment]
Thank you for the additional info, but I had to manually `sudo apt-get install matrix-org-archive-keyring` to be able to continue updating my system normally without the error shown.

Leaving this comment for other people coming from Google, like I did, so they can figure out what to do.

That said, I'm disappointed to see that this is apparently a reoccurring issue that requires admin intervention to keep Synapse updated.

**Comment by richvdh** [comment]
> That said, I'm disappointed to see that this is apparently a reoccurring issue that requires admin intervention to keep Synapse updated.

It should not require admin intervention: `matrix-synapse-py3` depends on `matrix-org-archive-keyring`, which exists to update the key.

This issue was superceded by #10389.
