### ISSUE TITLE
amadine.jpg isn't in color

### ISSUE THREAD

**Issue by hwittenborn** [matrix-org/matrix.org#981]
[amadine.jpg](https://github.com/matrix-org/matrix.org/blob/master/gatsby/static/images/guardians/amandine.jpg) isn't in color, despite the rest of the images in the guardians folder being so.

**Comment by afranke** [comment]
The only page that uses those portraits is https://matrix.org/foundation/ which displays *all* of them in greyscale, so how is this an issue anyway?

**Comment by hwittenborn** [comment]
Tapping the portraits on that page shows them in color, again all except for the one under amandine.jpg though.

**Comment by afranke** [comment]
Ha, right!

@AmandineLP would you be able to provide me with a color version of that picture (or another one if you want to seize the opportunity to get it updated)? I can then take care of the PR.

**Comment by AmandineLP** [comment]
Ah yes it's a B&W one. I'll see if I can find another coloured one to replace it.
