### ISSUE TITLE
Introduction page should warn about homeserver lock-in (kind of vendor lock-in)

### ISSUE THREAD

**Issue by laolux** [matrix-org/matrix.org#990]
**Is your feature request related to a problem? Please describe.**
New users are not warned about homeserver lock-in (akin to vendor lock-in). On the page [introduction/How can I try it out?](https://matrix.org/docs/guides/introduction#how-can-i-try-it-out) there is a small list of publicly available homeservers, but no warning that homeservers cannot be changed later without loosing data in encrypted chats.

**Describe the solution you'd like**
I think it would be good if new users were informed that they should choose their homeserver carefully, as they will not be able to switch to a different homeserver later without loosing data in encrypted chats.

**Describe alternatives you've considered**
A different and in my opinion favorable solution would be to implement functionality which actually does allow users to change their homeserver and keep the history in encrypted chats. This seems to be especially challenging for chats which have the option `Who can read history? Members only (since the point in time of selecting this option)` set. But then again, changing homeserver does not mean that someone new is joining the chat, only that someone is known under a new address now.

**Additional context**
I think it is good to give newcomers some guidance how to quickly try out matrix, but it should be clearly mentioned that in order to use matrix productively one needs to carefully choose a good homeserver. I think many users will simply pick a homeserver from the list and will be happy because it works and it is advertised as decentralized and open (no vendor lock-in, so implies users are free to choose and move). However, they may later discover that they want to change to a new homeserver for whatever reason (maybe their homeserver announced it will be retiring) and then find out that despite matrix being an open system, they are still stuck with their homeserver operator and cannot simply leave and move elsewhere without potentially loosing valuable chat history. I think matrix should be more open about the fact that there is something akin to vendor lock-in and that homeservers do not freely share their data silos with each other.

**Comment by aaronraimist** [comment]
@laolux I agree. Just wanted to note though that when the room is set to "Members only (since the point in time of selecting this option)" you will not lose messages if you join the room with a new account. You would only lose messages if the room is set to "Members only (since they were invited)" or "Members only (since they joined)".

> But then again, changing homeserver does not mean that someone new is joining the chat, only that someone is known under a new address now.

From an emotional level this is true but not at a technical level. The protocol doesn't currently specify any way to know that @alice:server1.com is the same human as @alice:server2.com. If the username is different it is a separate user.

**Comment by thibaultamartin** [comment]
The docs of the upcoming version of m.org have been updated, and mention it. Once #1570 exists, I will link to it from this section of the docs so people have a more complete view of what is possible.

I'm closing this issue to keep track of what's left to be done before the launch of the new website.
